import type { LawType } from '../../shared/lawTypes';

export interface LexaraLegalDomainProfile {
  displayName: string;
  specialistDirective: string;
  coreIssues: readonly string[];
  procedureAndDeadlineFocus: readonly string[];
  authorityPriorities: readonly string[];
  jurisdictionQuestions: readonly string[];
  remediesAndOutcomes: readonly string[];
  adjacentDomains: readonly string[];
  researchHints: readonly string[];
  preferredOfficialDomains: readonly string[];
}

function domain(
  displayName: string,
  specialistDirective: string,
  coreIssues: string[],
  procedureAndDeadlineFocus: string[],
  authorityPriorities: string[],
  jurisdictionQuestions: string[],
  remediesAndOutcomes: string[],
  adjacentDomains: string[],
  researchHints: string[],
  preferredOfficialDomains: string[] = [],
): LexaraLegalDomainProfile {
  return {
    displayName,
    specialistDirective,
    coreIssues,
    procedureAndDeadlineFocus,
    authorityPriorities,
    jurisdictionQuestions,
    remediesAndOutcomes,
    adjacentDomains,
    researchHints,
    preferredOfficialDomains,
  };
}

/**
 * Canonical LEXARA practice-area specialization registry.
 *
 * Every bookshelf law type must have an explicit profile. The Record<LawType, ...>
 * type makes additions fail compilation until the new practice area receives a
 * specialization instead of silently falling back to a generic legal prompt.
 *
 * These profiles are issue-spotting and research-routing guidance, not a static
 * statement of controlling law. Current, jurisdiction-specific primary authority
 * remains mandatory whenever the answer turns on law, procedure, or a deadline.
 */
export const LEXARA_LEGAL_DOMAIN_PROFILES = {
  'law-enforcement-accountability': domain(
    'Law Enforcement Accountability',
    'Analyze police and other law-enforcement conduct as a civil-rights and accountability specialist. Separate constitutional claims, statutory causes of action, state tort theories, municipal liability, individual defenses, and available administrative remedies.',
    ['Fourth Amendment seizure and force', 'First Amendment retaliation and recording', 'due process and equal protection', '42 U.S.C. § 1983 elements', 'Monell municipal liability', 'qualified and absolute immunity issues', 'state tort claims and immunities', 'evidence preservation and body-camera/public-record evidence'],
    ['limitations and claim-presentation deadlines', 'administrative complaint procedures', 'federal pleading and service rules', 'preservation letters and spoliation', 'exhaustion only where legally required'],
    ['U.S. Constitution and U.S. Code', 'U.S. Supreme Court and controlling circuit precedent', 'state constitution/statutes/cases for state claims', 'official department policies only as factual or policy evidence'],
    ['state and locality', 'federal circuit', 'agency involved', 'custodial status and incident date'],
    ['damages', 'injunctive/declaratory relief', 'suppression only in the underlying criminal matter where applicable', 'administrative discipline/complaint', 'state-law remedies'],
    ['constitutional-law', 'civil-rights-law', 'criminal-law', 'tort-law', 'foia-open-records-law'],
    ['section 1983', 'Fourth Amendment', 'qualified immunity', 'Monell', 'police misconduct'],
    ['constitution.congress.gov', 'uscode.house.gov', 'supremecourt.gov', 'uscourts.gov', 'justice.gov'],
  ),
  'criminal-law': domain(
    'Criminal Law',
    'Analyze criminal matters as a defense-oriented criminal-law specialist, keeping substantive offenses, constitutional procedure, evidentiary questions, charging posture, plea consequences, sentencing exposure, and collateral consequences distinct.',
    ['offense elements and mens rea', 'charging instruments', 'Fourth/Fifth/Sixth Amendment issues', 'search and seizure', 'interrogation and Miranda', 'evidence admissibility', 'affirmative defenses and justification', 'pleas, sentencing, probation, and collateral consequences'],
    ['arraignment and detention', 'discovery', 'suppression and pretrial motions', 'speedy-trial rules', 'plea deadlines', 'trial preservation', 'notice of appeal'],
    ['current criminal statutes', 'rules of criminal procedure and evidence', 'controlling appellate precedent', 'sentencing statutes/guidelines'],
    ['state or federal prosecution', 'court and charging jurisdiction', 'charge level', 'custody/status and next court date'],
    ['dismissal', 'suppression', 'acquittal', 'plea resolution', 'sentencing mitigation', 'appeal', 'post-conviction relief'],
    ['constitutional-law', 'procedural-law', 'appellate-law', 'post-conviction-law', 'juvenile-law'],
    ['elements of offense', 'criminal procedure', 'suppression', 'sentencing', 'constitutional defense'],
    ['uscourts.gov', 'uscode.house.gov', 'constitution.congress.gov', 'ussc.gov'],
  ),
  'civil-law': domain(
    'Civil Law',
    'Analyze general civil disputes as a civil-litigation specialist. Identify the actual cause of action, elements, burdens, defenses, damages, jurisdiction, procedure, and proof rather than treating “civil law” as one substantive rule set.',
    ['cause-of-action identification', 'duty/breach/causation/damages where applicable', 'standing and capacity', 'affirmative defenses', 'damages and equitable relief', 'evidence and burdens of proof', 'settlement and ADR'],
    ['limitations and repose', 'pre-suit notice', 'subject-matter/personal jurisdiction', 'venue', 'service', 'pleading', 'discovery', 'dispositive motions', 'trial and appeal preservation'],
    ['applicable state statutes and cases', 'federal statutes where implicated', 'civil-procedure and evidence rules', 'controlling court precedent'],
    ['state', 'court system', 'location of parties/events', 'amount in controversy', 'dates of injury/breach/discovery'],
    ['damages', 'declaratory relief', 'injunction', 'specific performance where available', 'settlement', 'fees/costs where authorized'],
    ['contract-law', 'tort-law', 'procedural-law', 'property-law', 'consumer-protection'],
    ['civil cause of action', 'statute of limitations', 'civil procedure', 'damages', 'affirmative defense'],
    ['uscourts.gov', 'govinfo.gov'],
  ),
  'family-law': domain(
    'Family Law',
    'Analyze family-law matters as a domestic-relations specialist with strong jurisdiction discipline. Treat custody, support, divorce, parentage, adoption, protection orders, and property division as distinct proceedings governed primarily by state law.',
    ['divorce/dissolution grounds', 'jurisdiction and residency', 'custody and best-interests factors', 'parentage', 'child support', 'spousal support', 'marital property/debt division', 'domestic violence and protective orders', 'adoption and guardianship'],
    ['temporary orders', 'mandatory disclosures', 'service', 'hearing deadlines', 'modification standards', 'appealability', 'UCCJEA interstate custody issues', 'UIFSA interstate support issues'],
    ['state family code/statutes', 'state supreme/appellate precedent', 'state court rules/forms', 'federal statutes only where they actually govern interstate/federal overlays'],
    ['state', 'county/court', 'marital/residency history', 'children’s home states and dates', 'existing orders'],
    ['custody/parenting orders', 'support orders', 'property division', 'dissolution', 'protective orders', 'modification/enforcement'],
    ['procedural-law', 'property-law', 'juvenile-law', 'constitutional-law'],
    ['best interests child', 'UCCJEA', 'UIFSA', 'family court procedure', 'support guidelines'],
    ['acf.hhs.gov'],
  ),
  'juvenile-law': domain(
    'Juvenile Law',
    'Analyze juvenile matters as a specialist in delinquency, dependency/child-protection, status-offense, transfer, confidentiality, and youth-rights procedure. Never collapse delinquency and dependency into the same legal framework.',
    ['juvenile-court jurisdiction', 'delinquency allegations', 'dependency/neglect standards', 'transfer/waiver to adult court', 'right to counsel and interrogation protections', 'disposition and rehabilitation', 'confidentiality and sealing', 'school consequences'],
    ['detention hearings', 'adjudication/disposition', 'permanency timelines in dependency cases', 'transfer hearings', 'appeals', 'record sealing/expungement'],
    ['state juvenile codes and court rules', 'controlling constitutional precedent', 'federal child-welfare statutes where applicable', 'state appellate decisions'],
    ['state', 'age at alleged conduct', 'delinquency versus dependency posture', 'custody/detention status', 'existing family-court orders'],
    ['diversion', 'dismissal', 'adjudication/disposition', 'services', 'placement', 'reunification/permanency', 'sealing/expungement'],
    ['criminal-law', 'family-law', 'education law issues', 'constitutional-law'],
    ['juvenile delinquency', 'dependency', 'transfer to adult court', 'juvenile rights', 'record sealing'],
    ['childwelfare.gov', 'ojjdp.ojp.gov'],
  ),
  'appellate-law': domain(
    'Appellate Law',
    'Analyze appeals as an appellate specialist. Start with appealability, jurisdiction, deadline, record preservation, standard of review, harmless/prejudicial error, and available relief before evaluating merits.',
    ['final versus interlocutory orders', 'appellate jurisdiction', 'preservation and waiver', 'standard of review', 'record sufficiency', 'harmless error', 'mootness', 'standing', 'briefing and oral argument'],
    ['notice-of-appeal deadlines', 'post-judgment motions affecting time', 'record/transcript designation', 'briefing schedules', 'rehearing/reconsideration', 'certiorari/discretionary review'],
    ['applicable appellate rules', 'controlling appellate precedent', 'trial-court record', 'statutes governing appellate jurisdiction'],
    ['state or federal system', 'trial court', 'date and type of order/judgment', 'post-judgment motions', 'issues preserved below'],
    ['affirmance', 'reversal', 'vacatur', 'remand', 'modification', 'stay pending appeal', 'rehearing or higher review'],
    ['procedural-law', 'post-conviction-law', 'constitutional-law'],
    ['appealability', 'notice of appeal', 'standard of review', 'preservation error', 'appellate jurisdiction'],
    ['uscourts.gov', 'supremecourt.gov'],
  ),
  'constitutional-law': domain(
    'Constitutional Law',
    'Analyze constitutional questions as a constitutional-law specialist. Identify the government actor, source of constitutional protection, incorporation/state-action issues, level or standard of scrutiny, remedy vehicle, immunity, and jurisdiction.',
    ['state action', 'First Amendment', 'Second Amendment where implicated', 'Fourth Amendment', 'Fifth/Fourteenth Amendment due process', 'equal protection', 'takings', 'religion clauses', 'federalism and preemption', 'standing and justiciability'],
    ['proper cause of action/remedial vehicle', 'injunctive standing', 'exhaustion where applicable', 'limitations', 'preservation for appeal'],
    ['constitutional text', 'U.S. Supreme Court', 'controlling circuit/state high-court precedent', 'federal/state constitutional statutes and remedial provisions'],
    ['federal versus state constitution', 'government actor', 'federal circuit', 'type of challenged action'],
    ['declaratory/injunctive relief', 'damages where a valid cause of action exists', 'suppression in criminal cases', 'invalidating or limiting government action'],
    ['civil-rights-law', 'law-enforcement-accountability', 'administrative-law', 'criminal-law'],
    ['constitutional standard', 'state action', 'strict scrutiny', 'due process', 'equal protection'],
    ['constitution.congress.gov', 'supremecourt.gov', 'uscourts.gov', 'uscode.house.gov'],
  ),
  'property-law': domain(
    'Property Law',
    'Analyze real-property ownership and use disputes as a property-law specialist, distinguishing title, possession, boundaries, easements, covenants, adverse possession, nuisance, co-ownership, and takings.',
    ['title and chain of title', 'deeds and conveyances', 'easements', 'covenants/servitudes', 'boundaries', 'adverse possession', 'co-tenancy/partition', 'nuisance', 'land-use restrictions', 'takings'],
    ['recording acts', 'limitations/repose', 'quiet-title requirements', 'lis pendens', 'survey/expert evidence', 'partition procedure'],
    ['state property statutes', 'county recording rules/records', 'state appellate precedent', 'local land-use codes'],
    ['state/county', 'property location', 'recorded instruments', 'possession history', 'survey/title evidence'],
    ['quiet title', 'declaratory/injunctive relief', 'damages', 'partition', 'easement declaration', 'specific performance'],
    ['real-estate-law', 'contract-law', 'municipal-government-law', 'tort-law'],
    ['property title', 'easement', 'adverse possession', 'recording act', 'partition'],
    [],
  ),
  'real-estate-law': domain(
    'Real Estate Law',
    'Analyze real-estate transactions and disputes as a real-estate specialist, separating purchase/sale contracts, disclosure, financing, title, closing, leasing, foreclosure, and broker duties.',
    ['purchase agreements', 'seller disclosure', 'title defects', 'escrow/closing', 'mortgage and deed of trust', 'foreclosure', 'broker/agent duties', 'leases', 'HOA/condominium issues', 'fair-housing overlays'],
    ['contract contingencies', 'rescission/notice deadlines', 'recording', 'foreclosure notices and cure periods', 'limitations', 'closing obligations'],
    ['state real-estate statutes/cases', 'county recording rules', 'federal mortgage-servicing and fair-housing law where applicable', 'local ordinances'],
    ['property state/county', 'residential/commercial', 'transaction posture', 'loan type', 'recorded documents and dates'],
    ['rescission', 'specific performance', 'damages', 'quiet title', 'injunction', 'loan workout/foreclosure defenses where legally supported'],
    ['property-law', 'contract-law', 'banking-financing-law', 'public-housing-law'],
    ['real estate contract', 'seller disclosure', 'title', 'foreclosure', 'mortgage servicing'],
    ['consumerfinance.gov', 'hud.gov'],
  ),
  'contract-law': domain(
    'Contract Law',
    'Analyze contract matters as a contract specialist. Determine formation, governing law, interpretation, conditions, performance/breach, defenses, damages, and available equitable remedies before recommending a theory.',
    ['offer/acceptance/consideration', 'authority/capacity', 'statute of frauds', 'contract interpretation', 'conditions', 'material breach', 'anticipatory repudiation', 'warranties', 'mistake/fraud/duress/unconscionability', 'damages and mitigation'],
    ['notice-and-cure clauses', 'limitations', 'choice-of-law/forum clauses', 'arbitration', 'UCC versus common law', 'preservation of contract documents'],
    ['governing state statutes and cases', 'UCC as enacted by the relevant state', 'federal statutes only if applicable', 'contract text itself'],
    ['governing-law clause', 'state and place of performance', 'goods versus services', 'merchant status', 'written/oral/electronic agreement'],
    ['expectation/reliance/restitution damages', 'specific performance', 'rescission/reformation', 'declaratory relief', 'attorney fees where authorized'],
    ['business/securities issues', 'consumer-protection', 'real-estate-law', 'tort-law'],
    ['contract formation', 'UCC', 'breach', 'damages', 'statute of frauds'],
    [],
  ),
  'civil-rights-law': domain(
    'Civil Rights Law',
    'Analyze civil-rights matters as a specialist in constitutional and statutory anti-discrimination and rights-enforcement frameworks. Identify the protected right, actor, cause of action, exhaustion requirements, defenses/immunities, and remedy.',
    ['42 U.S.C. § 1983', 'federal anti-discrimination statutes', 'state civil-rights statutes', 'state action/color of law', 'equal protection/due process', 'retaliation', 'disability rights', 'voting and public-accommodation rights'],
    ['administrative exhaustion where required', 'charge/notice deadlines', 'limitations', 'standing', 'class/representative issues', 'injunctive-relief requirements'],
    ['statutory text and regulations', 'Supreme Court/controlling circuit precedent', 'official agency guidance where delegated/enforcement relevant', 'state civil-rights law'],
    ['state', 'federal circuit', 'public/private actor', 'protected status or protected conduct', 'administrative charge history'],
    ['damages', 'injunctive/declaratory relief', 'reinstatement/accommodation where applicable', 'fees where authorized', 'administrative relief'],
    ['constitutional-law', 'employment-labor-law', 'law-enforcement-accountability', 'public-housing-law'],
    ['civil rights cause of action', 'section 1983', 'discrimination', 'retaliation', 'administrative exhaustion'],
    ['justice.gov', 'eeoc.gov', 'ada.gov', 'uscode.house.gov'],
  ),
  'tort-law': domain(
    'Tort Law',
    'Analyze tort matters as a tort specialist. Identify duty, standard of care, breach, factual and proximate causation, damages, comparative fault, immunities, special duties, and intentional-tort elements as applicable.',
    ['negligence', 'premises liability', 'intentional torts', 'defamation/privacy torts', 'products liability', 'professional negligence', 'causation', 'damages', 'comparative/contributory fault', 'governmental immunity'],
    ['limitations/repose', 'pre-suit notice or expert affidavit requirements', 'government claim presentment', 'evidence preservation', 'expert testimony'],
    ['state tort statutes and cases', 'rules of evidence/procedure', 'special statutory schemes for medical/products/government claims'],
    ['state', 'location/date of injury', 'defendant type', 'discovery date', 'medical/property evidence'],
    ['compensatory damages', 'punitive damages where legally available', 'injunction in appropriate torts', 'settlement'],
    ['civil-law', 'insurance-law', 'consumer-protection', 'law-enforcement-accountability'],
    ['negligence elements', 'proximate cause', 'comparative fault', 'statute of limitations', 'damages'],
    [],
  ),
  'probate-estate-law': domain(
    'Probate and Estate Law',
    'Analyze probate and estate matters as a specialist in wills, intestacy, estate administration, fiduciary duties, creditor claims, contests, beneficiary rights, and transfer-on-death mechanisms.',
    ['will validity and interpretation', 'intestacy', 'personal representative authority', 'creditor claims', 'elective/spousal rights', 'will contests and undue influence', 'fiduciary accounting', 'nonprobate assets', 'estate tax interface'],
    ['probate opening and notice', 'creditor claim periods', 'contest deadlines', 'inventory/accounting', 'distribution/closing', 'appeals'],
    ['state probate code and court rules', 'state appellate precedent', 'federal tax law where relevant', 'governing testamentary instruments'],
    ['decedent domicile', 'property locations', 'date of death', 'existence/version of will', 'probate already opened'],
    ['admission/rejection of will', 'appointment/removal of fiduciary', 'accounting', 'distribution', 'surcharge', 'construction/reformation where available'],
    ['trusts-law', 'tax-law', 'property-law', 'family-law'],
    ['probate', 'intestacy', 'will contest', 'personal representative', 'creditor claim'],
    [],
  ),
  'administrative-law': domain(
    'Administrative Law',
    'Analyze agency matters as an administrative-law specialist. Identify the agency’s statutory authority, procedural posture, exhaustion/finality, standard and scope of review, rulemaking/adjudication distinction, and available stay or judicial review.',
    ['agency jurisdiction', 'rulemaking', 'adjudication', 'licensing/benefits', 'due process', 'statutory interpretation', 'arbitrary/capricious review', 'substantial evidence', 'deference doctrines where currently applicable'],
    ['administrative exhaustion', 'final agency action', 'petition/reconsideration deadlines', 'record building', 'stay requests', 'judicial-review filing deadlines'],
    ['enabling statute', 'APA or state administrative-procedure act', 'agency regulations/orders', 'controlling judicial precedent'],
    ['federal/state/local agency', 'specific agency and program', 'decision date', 'administrative appeal history', 'finality'],
    ['reconsideration', 'administrative appeal', 'license/benefit relief', 'stay', 'judicial review', 'vacatur/remand'],
    ['municipal-government-law', 'constitutional-law', 'procedural-law', 'foia-open-records-law'],
    ['administrative procedure act', 'final agency action', 'exhaustion', 'judicial review', 'arbitrary capricious'],
    ['govinfo.gov', 'ecfr.gov', 'federalregister.gov'],
  ),
  'trusts-law': domain(
    'Trusts Law',
    'Analyze trust matters as a trust-law specialist, focusing on creation/validity, interpretation, trustee powers and fiduciary duties, beneficiary rights, modification/termination, accounting, creditor issues, and tax overlays.',
    ['trust formation', 'revocable/irrevocable status', 'trustee fiduciary duties', 'beneficiary information/accounting', 'investment and distribution standards', 'breach of trust', 'modification/termination', 'creditor/spendthrift issues', 'special-needs considerations'],
    ['notice/accounting requirements', 'limitations on fiduciary claims', 'court petitions', 'trustee removal/succession', 'tax filing/administration deadlines'],
    ['state trust code and cases', 'trust instrument', 'probate court rules', 'federal tax statutes/regulations where relevant'],
    ['governing state', 'settlor/trustee/beneficiary roles', 'revocability', 'trust situs', 'relevant instrument provisions'],
    ['accounting', 'injunction', 'surcharge', 'trustee removal', 'modification/termination', 'construction', 'distribution'],
    ['probate-estate-law', 'tax-law', 'property-law'],
    ['trustee fiduciary duty', 'trust accounting', 'trust modification', 'spendthrift', 'breach of trust'],
    ['uniformlaws.org'],
  ),
  'immigration-law': domain(
    'Immigration Law',
    'Analyze immigration matters as an immigration specialist while strictly distinguishing USCIS benefits adjudication, EOIR removal proceedings, consular matters, detention/bond, asylum/protection, and federal-court review.',
    ['status and admission/parole history', 'family/employment petitions', 'adjustment/consular processing', 'naturalization', 'inadmissibility/deportability', 'asylum/withholding/CAT', 'removal defenses', 'waivers', 'detention/bond', 'immigration consequences of crimes'],
    ['filing windows and priority dates', 'responding to notices/RFEs', 'immigration-court filing and hearing deadlines', 'BIA appeals/motions', 'petition for review deadlines', 'one-year asylum issue and exceptions'],
    ['INA/U.S. Code', 'regulations', 'USCIS Policy Manual where applicable', 'EOIR Policy Manual and precedent', 'controlling federal circuit/Supreme Court decisions'],
    ['current status', 'entry/admission history', 'A-number/proceeding posture', 'immigration court location', 'criminal history', 'family/employment basis'],
    ['status/benefit grant', 'waiver', 'termination/cancellation of removal where available', 'asylum/protection', 'bond/custody relief', 'administrative/federal review'],
    ['criminal-law', 'family-law', 'administrative-law', 'appellate-law'],
    ['immigration status', 'removal proceedings', 'asylum', 'adjustment of status', 'BIA appeal'],
    ['uscis.gov', 'justice.gov', 'ecfr.gov', 'uscode.house.gov'],
  ),
  'banking-financing-law': domain(
    'Banking and Financing Law',
    'Analyze banking and financing matters as a specialist in lending, servicing, consumer credit, secured transactions, foreclosure, banking regulation, and lender/borrower remedies.',
    ['loan formation/disclosures', 'TILA/RESPA where applicable', 'mortgage servicing', 'foreclosure', 'UCC secured transactions', 'guaranties', 'usury', 'deposit/account disputes', 'fair lending', 'debt collection interface'],
    ['notice/cure and acceleration', 'foreclosure timelines', 'servicing error/information requests', 'limitations', 'perfection/priority deadlines'],
    ['federal statutes/regulations and CFPB rules', 'state lending/foreclosure law', 'UCC as enacted', 'contract/loan documents'],
    ['state', 'consumer/commercial transaction', 'loan type', 'collateral location', 'servicer/lender identity', 'default and notice dates'],
    ['damages', 'rescission where statutorily available', 'injunction', 'servicing correction', 'loan workout', 'priority enforcement'],
    ['real-estate-law', 'contract-law', 'consumer-protection', 'securities-law'],
    ['TILA', 'RESPA', 'mortgage servicing', 'foreclosure', 'secured transaction'],
    ['consumerfinance.gov', 'ecfr.gov', 'occ.treas.gov', 'federalreserve.gov'],
  ),
  'insurance-law': domain(
    'Insurance Law',
    'Analyze insurance matters as a coverage and claims specialist. Separate policy interpretation, coverage grants/exclusions, conditions, claim handling, insurer defenses, regulatory requirements, and bad-faith theories.',
    ['policy coverage', 'exclusions/endorsements', 'notice/cooperation', 'duty to defend/indemnify', 'valuation', 'claim handling', 'bad faith', 'subrogation', 'ERISA preemption where applicable'],
    ['claim notice/proof-of-loss', 'internal appeal where applicable', 'suit-limitation clauses', 'statutory limitations', 'regulatory complaint'],
    ['policy language', 'state insurance statutes/regulations', 'state appellate precedent', 'federal ERISA law for covered benefit plans'],
    ['state', 'policy type', 'claim and denial dates', 'policy/endorsement language', 'employer-plan status'],
    ['coverage/declaration', 'benefits/payment', 'defense/indemnity', 'bad-faith/statutory damages where available', 'regulatory relief'],
    ['tort-law', 'contract-law', 'healthcare issues', 'consumer-protection'],
    ['insurance coverage', 'bad faith', 'duty to defend', 'claim denial', 'policy exclusion'],
    ['naic.org', 'dol.gov'],
  ),
  'employment-labor-law': domain(
    'Employment and Labor Law',
    'Analyze workplace matters as an employment-and-labor specialist. Separate wage/hour, discrimination, retaliation, leave/accommodation, labor-organizing, classification, contract, and state-law claims with their distinct exhaustion and deadline rules.',
    ['Title VII/ADA/ADEA/EPA where applicable', 'state anti-discrimination law', 'FLSA wage/overtime', 'FMLA', 'retaliation', 'reasonable accommodation', 'worker classification', 'NLRA protected concerted activity', 'employment agreements and restrictive covenants'],
    ['EEOC/state charge deadlines', 'wage-claim limitations', 'FMLA notices', 'NLRB charge timing', 'internal grievance/arbitration', 'litigation deadlines'],
    ['statutes/regulations', 'EEOC/DOL/NLRB official materials', 'controlling federal/state precedent', 'state wage/employment law'],
    ['state/work location', 'employer size/type', 'employment dates', 'protected status/conduct', 'union/CBA status', 'administrative filings'],
    ['back/front pay', 'reinstatement', 'accommodation', 'wages/liquidated damages where authorized', 'injunction', 'administrative relief'],
    ['civil-rights-law', 'contract-law', 'administrative-law'],
    ['employment discrimination', 'FLSA', 'FMLA', 'NLRA', 'retaliation'],
    ['eeoc.gov', 'dol.gov', 'nlrb.gov'],
  ),
  'military-veterans-law': domain(
    'Military/Veterans Law',
    'Analyze military and veterans matters as a specialist while separating VA benefits, discharge characterization/upgrades, military administrative actions, courts-martial/UCMJ issues, and federal judicial review.',
    ['VA disability/service connection', 'effective dates and ratings', 'decision review/appeals', 'discharge upgrades/corrections', 'military administrative boards', 'UCMJ/court-martial rights', 'USERRA employment protections'],
    ['VA Supplemental Claim/Higher-Level Review/Board deadlines', 'CAVC deadlines', 'discharge-review/correction-board limitations', 'military appellate deadlines'],
    ['Title 38 statutes/regulations', 'VA official guidance and decisions as appropriate', 'UCMJ/Manual for Courts-Martial', 'service regulations', 'federal veterans/military appellate precedent'],
    ['service branch', 'active/veteran status', 'decision/discharge date', 'claim/appeal lane', 'court-martial versus administrative posture'],
    ['benefits award/rating/effective-date correction', 'remand/review', 'discharge upgrade', 'record correction', 'military appellate relief'],
    ['employment-labor-law', 'administrative-law', 'appellate-law', 'criminal-law'],
    ['VA decision review', 'discharge upgrade', 'CAVC', 'UCMJ', 'USERRA'],
    ['va.gov', 'benefits.va.gov', 'uscourts.cavc.gov', 'defense.gov'],
  ),
  'foia-open-records-law': domain(
    'FOIA/Open Records Law',
    'Analyze public-record matters as a transparency-law specialist. Separate federal FOIA from state/local open-records statutes, identify the correct agency, scope the request, analyze exemptions, exhaustion, fees, timeliness, and judicial remedies.',
    ['agency/record identification', 'reasonable description', 'search adequacy', 'FOIA exemptions', 'segregability', 'fees/fee waivers', 'expedited processing', 'state open-records exemptions', 'privacy/confidentiality overlays'],
    ['request perfection', 'statutory response timing', 'administrative appeal', 'constructive exhaustion', 'litigation timing', 'preservation'],
    ['5 U.S.C. § 552 and DOJ OIP guidance for federal FOIA', 'agency FOIA regulations', 'state open-records statutes/cases', 'controlling federal circuit precedent'],
    ['federal versus state/local agency', 'state', 'request/response dates', 'records sought', 'exemption cited'],
    ['record production', 'reprocessing/new search', 'fee reduction/waiver', 'injunction', 'fees/costs where authorized'],
    ['administrative-law', 'constitutional-law', 'privacy/cyber issues'],
    ['FOIA exemption', 'administrative appeal', 'segregability', 'adequate search', 'open records'],
    ['justice.gov', 'foia.gov', 'govinfo.gov'],
  ),
  'cyber-technology-law': domain(
    'Cyber Technology Law',
    'Analyze technology, privacy, cybersecurity, platform, and computer-misuse matters as a cyber-law specialist. Identify the data/system, actor, authorization, contract, regulatory regime, incident obligations, evidence, and jurisdiction before selecting a theory.',
    ['data breach', 'privacy statutes', 'computer access/authorization', 'electronic communications', 'platform terms/contracts', 'cybersecurity duties', 'consumer deception', 'biometric/data rights', 'digital evidence', 'AI/automated-system issues'],
    ['breach-notification deadlines', 'regulator/consumer notice', 'preservation/forensics', 'limitations', 'incident-response sequencing'],
    ['applicable federal/state statutes and regulations', 'FTC/agency enforcement guidance', 'state attorney-general material', 'controlling cases'],
    ['affected states/countries', 'data type', 'consumer/business context', 'system owner/operator', 'incident dates', 'contract terms'],
    ['injunction', 'statutory/actual damages where authorized', 'regulatory response', 'contractual remedies', 'security/corrective measures'],
    ['consumer-protection', 'contract-law', 'intellectual-property-law', 'international-law'],
    ['data breach law', 'privacy', 'computer fraud abuse', 'FTC data security', 'breach notification'],
    ['ftc.gov', 'cisa.gov', 'nist.gov'],
  ),
  'intellectual-property-law': domain(
    'Intellectual Property Law',
    'Analyze IP matters as a specialist who first classifies the right correctly—patent, trademark, copyright, trade secret, publicity, or contract—and then applies the distinct ownership, validity, infringement, defense, registration, and remedy frameworks.',
    ['patentability/infringement', 'trademark protectability/likelihood of confusion', 'copyright ownership/infringement/fair use', 'trade-secret status/misappropriation', 'licensing/assignment', 'work made for hire', 'online infringement procedures'],
    ['registration/prosecution deadlines', 'maintenance/renewal', 'opposition/cancellation', 'DMCA processes where applicable', 'limitations and laches/equitable timing'],
    ['Patent Act/Lanham Act/Copyright Act/DTSA', 'USPTO/Copyright Office rules and records', 'Federal Circuit/controlling court precedent', 'state trade-secret/right-of-publicity law'],
    ['type of IP', 'creation/use/registration dates', 'ownership chain', 'market/territory', 'federal registration status'],
    ['injunction', 'damages/profits/statutory damages where authorized', 'registration/cancellation', 'licensing', 'seizure/destruction in qualifying cases'],
    ['contract-law', 'cyber-technology-law', 'business/securities issues', 'international-law'],
    ['patent', 'trademark likelihood confusion', 'copyright fair use', 'trade secret', 'license'],
    ['uspto.gov', 'copyright.gov', 'uscode.house.gov'],
  ),
  'public-housing-law': domain(
    'Public Housing Law',
    'Analyze subsidized and public-housing matters as a housing-law specialist. Distinguish public housing, Housing Choice Voucher/Section 8, project-based assistance, private landlord law, fair-housing rights, and housing-authority administrative procedure.',
    ['eligibility/termination', 'voucher obligations', 'rent calculations', 'inspection/habitability', 'reasonable accommodation', 'fair housing/discrimination', 'grievance/hearing rights', 'eviction interface', 'portability'],
    ['notice and hearing deadlines', 'recertification', 'reasonable-accommodation process', 'eviction procedure', 'administrative/judicial review'],
    ['HUD statutes/regulations/guidance', 'program documents', 'state landlord-tenant law', 'local housing-authority rules', 'Fair Housing Act/ADA/Section 504 where applicable'],
    ['program type', 'housing authority/project', 'state/locality', 'notice/termination date', 'disability/accommodation issue if raised'],
    ['continued assistance', 'recalculation', 'reasonable accommodation', 'hearing/reversal', 'injunction', 'fair-housing remedies'],
    ['real-estate-law', 'civil-rights-law', 'administrative-law', 'consumer-protection'],
    ['Housing Choice Voucher', 'public housing termination', 'HUD grievance', 'reasonable accommodation housing', 'Fair Housing Act'],
    ['hud.gov', 'ecfr.gov'],
  ),
  'procedural-law': domain(
    'Procedural Law',
    'Analyze procedural questions as a civil/criminal procedure specialist without assuming the merits. Identify the governing court, rule set, jurisdiction, posture, filing/service requirements, evidentiary record, deadlines, preservation, and consequence of noncompliance.',
    ['subject-matter/personal jurisdiction', 'venue', 'pleading', 'service', 'motions', 'discovery', 'evidence procedure', 'trial practice', 'judgment/post-judgment', 'appeal preservation'],
    ['rule-based deadlines', 'computation/extensions', 'filing/service methods', 'local rules/standing orders', 'waiver/forfeiture', 'relation back'],
    ['applicable federal/state procedural rules', 'local court rules', 'statutes governing jurisdiction/timing', 'controlling procedural precedent'],
    ['court and jurisdiction', 'civil/criminal/administrative posture', 'document/order dates', 'service dates', 'next deadline/hearing'],
    ['filing/response', 'extension', 'dismissal/avoidance of default', 'discovery relief', 'reconsideration', 'appeal preservation'],
    ['appellate-law', 'civil-law', 'criminal-law', 'administrative-law'],
    ['civil procedure', 'criminal procedure', 'local rule', 'service', 'filing deadline'],
    ['uscourts.gov'],
  ),
  'securities-law': domain(
    'Securities Law',
    'Analyze securities matters as a specialist in offerings, broker/dealer and adviser regulation, disclosure, antifraud, trading, fiduciary duties, exemptions, and enforcement, while separating federal and state blue-sky regimes.',
    ['security/investment-contract status', 'registration/exemptions', 'material misstatements/omissions', 'Rule 10b-5 and scienter', 'insider trading', 'broker-dealer/adviser duties', 'private offerings', 'market manipulation', 'state blue-sky law'],
    ['filing/registration deadlines', 'rescission periods where applicable', 'limitations/repose', 'SEC/FINRA proceedings', 'arbitration'],
    ['Securities Act/Exchange Act/Advisers Act', 'SEC rules/releases and filings', 'controlling federal precedent', 'FINRA rules where applicable', 'state securities statutes'],
    ['transaction/issuer location', 'public/private security', 'investor status', 'offering exemption claimed', 'broker/adviser involvement'],
    ['rescission', 'damages', 'injunction', 'regulatory/enforcement outcomes', 'arbitration remedies'],
    ['banking-financing-law', 'contract-law', 'consumer-protection', 'international-law'],
    ['securities fraud', '10b-5', 'private offering exemption', 'broker dealer', 'investment adviser'],
    ['sec.gov', 'finra.org', 'uscode.house.gov'],
  ),
  'international-law': domain(
    'International Law',
    'Analyze cross-border matters as an international-law specialist. First identify whether the issue is public international law, private international/conflict of laws, treaty implementation, cross-border litigation, arbitration, trade, sanctions, or transnational transaction.',
    ['treaty status and domestic implementation', 'choice of law', 'forum/jurisdiction', 'service abroad', 'foreign sovereign immunity', 'judgment recognition/enforcement', 'international arbitration', 'sanctions/export controls', 'cross-border evidence'],
    ['treaty-specific deadlines', 'service/convention procedure', 'arbitration timelines', 'recognition/enforcement procedure', 'sanctions licensing'],
    ['treaty text/status from official sources', 'implementing statutes/regulations', 'controlling domestic precedent', 'foreign law only with verified jurisdiction-specific sources'],
    ['countries involved', 'forum', 'nationality/residence', 'contract choice-of-law/forum clauses', 'government/sovereign involvement'],
    ['recognition/enforcement', 'arbitration award/remedies', 'injunction/damages under domestic cause of action', 'regulatory license/compliance'],
    ['contract-law', 'securities-law', 'cyber-technology-law', 'immigration-law'],
    ['treaty', 'Hague Convention', 'foreign judgment', 'international arbitration', 'sanctions'],
    ['state.gov', 'treaties.un.org', 'justice.gov', 'ofac.treasury.gov'],
  ),
  'tax-law': domain(
    'Tax Law',
    'Analyze tax matters as a tax-procedure and substantive-tax specialist. Identify tax type, taxpayer/entity, tax year, assessment/collection posture, administrative rights, deadlines, penalties, collection alternatives, and court forum.',
    ['income/payroll/excise/estate-gift tax as applicable', 'filing/status', 'deductions/credits/basis', 'audit/examination', 'assessment and penalties', 'collection liens/levies', 'refund claims', 'Tax Court/refund litigation', 'state/local tax'],
    ['return/amendment', 'notice-response and deficiency deadlines', 'refund claim limits', 'collection due process', 'appeal/petition deadlines', 'collection statutes'],
    ['Internal Revenue Code/Treasury regulations', 'IRS official procedures/notices as appropriate', 'Tax Court/Supreme/controlling circuit precedent', 'state tax law for state issues'],
    ['federal/state/local tax', 'tax years', 'notice type/date', 'entity/taxpayer status', 'assessment/collection stage'],
    ['administrative appeal', 'abatement', 'refund', 'installment/collection alternative', 'Tax Court/refund action', 'injunctive relief only where legally permitted'],
    ['probate-estate-law', 'trusts-law', 'business/securities issues', 'administrative-law'],
    ['taxpayer bill of rights', 'notice of deficiency', 'collection due process', 'refund claim', 'tax court'],
    ['irs.gov', 'ustaxcourt.gov', 'uscode.house.gov'],
  ),
  'environmental-law': domain(
    'Environmental Law',
    'Analyze environmental matters as a regulatory and litigation specialist. Identify the regulated medium/activity, permit, agency, statute, responsible parties, enforcement posture, cleanup/remediation duties, citizen-suit prerequisites, and state-law overlays.',
    ['Clean Air Act', 'Clean Water Act', 'CERCLA', 'RCRA', 'NEPA', 'permitting', 'hazardous waste/cleanup', 'agency enforcement', 'citizen suits', 'environmental review', 'state environmental statutes'],
    ['permit/notice/comment', 'administrative appeal', 'citizen-suit notice', 'limitations', 'cleanup/enforcement orders', 'judicial review'],
    ['federal environmental statutes/regulations', 'EPA official materials/actions', 'state environmental agency law', 'controlling precedent'],
    ['state/site', 'agency/permit', 'pollutant/activity', 'owner/operator history', 'enforcement/notice status'],
    ['permit relief', 'compliance/remediation', 'injunction', 'cost recovery/contribution where authorized', 'civil penalties/enforcement resolution'],
    ['administrative-law', 'property-law', 'tort-law', 'municipal-government-law'],
    ['EPA regulation', 'Clean Water Act', 'Clean Air Act', 'CERCLA', 'RCRA'],
    ['epa.gov', 'ecfr.gov'],
  ),
  'municipal-government-law': domain(
    'Municipal/Government Law',
    'Analyze local-government matters as a municipal-law specialist. Identify governmental authority, charter/statute, ordinance, zoning/land-use rule, meeting/procurement/public-record requirements, immunity, administrative remedy, and judicial-review path.',
    ['municipal powers/home rule', 'ordinances', 'zoning/land use', 'permits/licenses', 'code enforcement', 'public meetings', 'procurement', 'government contracts', 'municipal liability/immunity', 'local taxation/fees'],
    ['local administrative appeal', 'zoning/variance hearing deadlines', 'claim notice', 'judicial review', 'referendum/election timing where relevant'],
    ['state constitution/statutes', 'municipal charter/code', 'local rules/records', 'state appellate precedent', 'federal constitutional overlay'],
    ['state/locality', 'municipal body', 'ordinance/decision', 'decision/notice date', 'administrative appeal taken'],
    ['permit/variance', 'administrative reversal', 'declaratory/injunctive relief', 'damages where authorized', 'mandamus/special review where available'],
    ['administrative-law', 'property-law', 'constitutional-law', 'foia-open-records-law'],
    ['municipal ordinance', 'zoning appeal', 'home rule', 'government immunity', 'local administrative review'],
    [],
  ),
  'post-conviction-law': domain(
    'Post Conviction',
    'Analyze post-conviction matters as a collateral-review specialist. First determine whether the conviction is state or federal, whether direct review is complete, the custody/status requirement, judgment finality date, prior collateral filings, and the exact remedy being considered. Keep direct appeal, state post-conviction, federal habeas under 28 U.S.C. § 2254, and federal-prisoner relief under 28 U.S.C. § 2255 analytically separate.',
    ['ineffective assistance under Strickland and related prejudice standards', 'Brady disclosure and Napue false-testimony issues', 'jurisdictional/constitutional error', 'newly discovered evidence', 'actual innocence gateway versus freestanding innocence claims', 'involuntary plea', 'sentencing error cognizable on collateral review', 'state post-conviction claims', '§ 2254 exhaustion/deference', '§ 2255 collateral attack'],
    ['judgment finality', 'AEDPA one-year limitation and statutory/equitable tolling', 'state post-conviction filing deadlines', 'exhaustion', 'procedural default/cause/prejudice', 'second-or-successive authorization', 'relation back/amendment', 'certificate of appealability', 'prison mailbox rule where applicable'],
    ['28 U.S.C. §§ 2244, 2253, 2254, and 2255', 'Rules Governing § 2254 and § 2255 Cases', 'controlling U.S. Supreme Court and circuit precedent', 'state post-conviction statute/rule and state high-court precedent', 'trial/appellate record'],
    ['state versus federal conviction', 'sentencing court and current custody', 'federal circuit/state', 'judgment and mandate/finality dates', 'direct appeal history', 'every prior state/federal collateral filing and disposition'],
    ['vacatur/set-aside/correction where authorized', 'new trial', 'resentencing', 'release or conditional writ', 'evidentiary hearing where legally available', 'certificate of appealability and appellate review'],
    ['criminal-law', 'appellate-law', 'constitutional-law', 'procedural-law'],
    ['28 USC 2244 limitation successive', '28 USC 2254 exhaustion procedural default AEDPA', '28 USC 2255 collateral attack', 'Strickland ineffective assistance', 'Brady Napue', 'Schlup McQuiggin actual innocence', 'certificate of appealability'],
    ['uscourts.gov', 'uscode.house.gov', 'supremecourt.gov'],
  ),
  'agricultural-law': domain(
    "Agricultural Law",
    "Analyze agricultural matters as an agricultural-law specialist. Resolve the governing federal, state, and local framework, the land or operation involved, agency jurisdiction, contract or program terms, and available administrative or judicial remedies.",
    ["farm and ranch operations","agricultural contracts","USDA programs","crop and livestock regulation","agricultural land use","food production regulation","farm lending and liens"],
    ["agency deadlines and administrative exhaustion","permit and program deadlines","contract limitations","appeal and judicial-review timing"],
    ["federal agricultural statutes and regulations","USDA and agency materials","state agricultural statutes","controlling appellate precedent"],
    ["state and county","farm or business structure","agency/program involved","land or commodity involved","relevant notices and deadlines"],
    ["program benefits","contract damages","administrative relief","injunction/declaratory relief","permit or compliance relief"],
    ["property-law","contract-law","environmental-law","banking-financing-law"],
    ["USDA program","farm contract","agricultural lien","right to farm","agricultural regulation"],
    ["usda.gov","ecfr.gov"],
  ),
  'banking-consumer-credit-debt-law': domain(
    "Banking/Consumer Credit and Debt Law",
    "Analyze consumer banking, credit, and debt matters as a consumer-finance specialist. Identify the creditor or furnisher, account type, transaction history, disclosures, collection activity, credit reporting, governing federal/state protections, and dispute history.",
    ["consumer loans and credit","debt collection","credit reporting","bank account disputes","lending disclosures","servicing","repossessions","consumer financial fraud"],
    ["dispute and validation deadlines","limitations periods","credit-reporting reinvestigation timing","notice and cure requirements"],
    ["federal consumer-finance statutes and regulations","CFPB regulations and official interpretations","state consumer-credit law","controlling appellate precedent"],
    ["state","creditor/collector/furnisher","account type","consumer versus business purpose","dates of notices/disputes"],
    ["correction/deletion","statutory damages where authorized","actual damages","injunctive/declaratory relief","defense to collection","regulatory complaint"],
    ["banking-financing-law","contract-law","securities-law","bankruptcy-law"],
    ["FCRA dispute","FDCPA validation","TILA disclosure","ECOA credit","debt collection","consumer lending"],
    ["consumerfinance.gov","ftc.gov","ecfr.gov"],
  ),
  'bankruptcy-law': domain(
    "Bankruptcy Law",
    "Analyze bankruptcy matters as a bankruptcy-law specialist. Identify chapter, debtor eligibility, petition status, estate property, automatic-stay issues, exemptions, secured and unsecured claims, dischargeability, plan posture, and bankruptcy-court procedure.",
    ["Chapter 7","Chapter 11","Chapter 13","automatic stay","discharge and dischargeability","exemptions","claims and priorities","avoidance actions","plans","creditor remedies"],
    ["petition and meeting deadlines","proof-of-claim deadlines","objection and adversary deadlines","plan deadlines","appeal timing"],
    ["Bankruptcy Code","Federal Rules of Bankruptcy Procedure","local bankruptcy rules","controlling Supreme Court and circuit precedent"],
    ["bankruptcy district","chapter","debtor type","petition date","case number/status","prior bankruptcies"],
    ["discharge","reorganization plan","stay relief or enforcement","claim allowance/disallowance","avoidance recovery","dismissal or conversion"],
    ["banking-consumer-credit-debt-law","contract-law","property-law","tax-law"],
    ["11 USC automatic stay","Chapter 7 discharge","Chapter 13 plan","proof of claim","bankruptcy exemption"],
    ["uscourts.gov","uscode.house.gov"],
  ),
  'business-corporate-law': domain(
    "Business/Corporate Law",
    "Analyze business and corporate matters as a business-law specialist. Identify entity type and jurisdiction, formation and governing documents, ownership and control, fiduciary duties, transaction structure, regulatory obligations, and dispute posture.",
    ["entity formation","corporations and LLCs","governance","fiduciary duties","shareholder and member disputes","mergers and acquisitions","business contracts","dissolution"],
    ["filing and notice deadlines","governance procedures","limitations periods","transaction closing requirements"],
    ["state entity statutes","governing documents","contracts","federal law where applicable","controlling state and federal precedent"],
    ["formation state","entity type","ownership/control","governing documents","transaction or dispute date"],
    ["damages","injunction","accounting","dissolution","buyout","rescission","declaratory relief"],
    ["contract-law","securities-law","tax-law","employment-labor-law"],
    ["corporate fiduciary duty","LLC operating agreement","shareholder dispute","business formation","merger"],
    ["sec.gov"],
  ),
  'disability-law': domain(
    "Disability Law",
    "Analyze disability-rights matters as a disability-law specialist. Identify the protected status and statutory framework, covered entity, requested accommodation or access, interactive process where applicable, adverse action, administrative prerequisites, and available remedies.",
    ["ADA employment","public accommodations","government services","reasonable accommodation","accessibility","disability discrimination","rehabilitation act"],
    ["administrative charge deadlines","notice requirements","limitations periods","exhaustion where required"],
    ["ADA and Rehabilitation Act","implementing regulations","EEOC/DOJ guidance","state disability law","controlling precedent"],
    ["state","employment/public service/public accommodation context","covered entity","accommodation request","adverse action date"],
    ["accommodation","injunction","reinstatement","damages where authorized","fees/costs where authorized"],
    ["civil-rights-law","employment-labor-law","education-law","administrative-law"],
    ["ADA accommodation","disability discrimination","Section 504","accessibility"],
    ["ada.gov","eeoc.gov","ecfr.gov"],
  ),
  'education-law': domain(
    "Education Law",
    "Analyze education matters as an education-law specialist. Identify institution type, student status, governing federal/state law, disciplinary or special-education procedure, administrative record, deadlines, and available review.",
    ["student rights","school discipline","IDEA special education","Section 504","Title IX","higher education disputes","school governance"],
    ["IDEA procedural deadlines","disciplinary appeal deadlines","Title IX procedures","administrative exhaustion","judicial-review timing"],
    ["federal education statutes and regulations","state education code","agency rules","school policies","controlling precedent"],
    ["state and school district/institution","K-12 or higher education","public or private","student status","decision and notice dates"],
    ["IEP/services","accommodation","disciplinary reversal","injunction","damages where authorized","administrative or judicial review"],
    ["disability-law","civil-rights-law","administrative-law","constitutional-law"],
    ["IDEA due process","Title IX education","student discipline","Section 504 school"],
    ["ed.gov","ecfr.gov"],
  ),
  'health-medical-law': domain(
    "Health/Medical Law",
    "Analyze healthcare and medical-law matters as a health-law specialist. Identify provider and payer roles, patient status, privacy and consent issues, regulatory framework, billing or coverage posture, professional duties, and administrative or litigation remedies.",
    ["patient rights","HIPAA and health privacy","informed consent","healthcare regulation","medical billing","provider licensing","healthcare fraud and compliance"],
    ["administrative appeal deadlines","privacy complaint timing","limitations periods","licensing and reimbursement deadlines"],
    ["federal healthcare statutes and regulations","HHS/CMS rules and guidance","state health and licensing law","controlling precedent"],
    ["state","provider/facility/payer","patient relationship","service and notice dates","consent/privacy facts"],
    ["record correction/access","administrative relief","coverage/payment relief","damages where authorized","injunction","licensing remedy"],
    ["insurance-law","personal-injury-medical-malpractice-law","administrative-law","disability-law"],
    ["HIPAA privacy","informed consent","medical billing dispute","healthcare regulation"],
    ["hhs.gov","cms.gov","ecfr.gov"],
  ),
  'landlord-tenant-law': domain(
    "Landlord-Tenant Law",
    "Analyze landlord-tenant matters as a housing-law specialist. Identify tenancy type, lease terms, property jurisdiction, rent and deposit history, habitability conditions, notices, eviction posture, anti-retaliation or discrimination issues, and available remedies.",
    ["leases","eviction","security deposits","habitability","rent disputes","repairs","retaliation","tenant privacy","lease termination"],
    ["notice periods","eviction response and hearing deadlines","deposit-return deadlines","limitations periods"],
    ["state landlord-tenant statutes","local housing codes","lease","court rules","federal housing law where applicable"],
    ["state/locality","residential or commercial","lease status","notice type/date","court filing status"],
    ["possession","dismissal or defense to eviction","repairs","rent abatement where authorized","deposit recovery","damages or injunction"],
    ["public-housing-law","property-law","contract-law","civil-rights-law"],
    ["eviction notice","security deposit","habitability","lease termination","tenant retaliation"],
    ["hud.gov"],
  ),
  'personal-injury-medical-malpractice-law': domain(
    "Personal Injury/Medical Malpractice Law",
    "Analyze injury and medical-malpractice matters as a plaintiff- and defense-neutral tort specialist. Identify duty, breach, causation, damages, responsible parties, comparative fault, insurance, expert requirements, pre-suit procedure, and limitations or repose.",
    ["negligence","medical malpractice","wrongful death","premises liability","product-related injury","causation","damages","professional standard of care"],
    ["statutes of limitation and repose","pre-suit notice or screening requirements","expert affidavit/certificate requirements","discovery and filing deadlines"],
    ["state tort and malpractice statutes","evidence and civil-procedure rules","controlling state precedent","professional regulations where relevant"],
    ["state","injury and discovery dates","defendants/providers","treatment timeline","claim notices already sent"],
    ["compensatory damages","medical expenses","lost income","injunctive relief where applicable","settlement","wrongful-death/survival remedies"],
    ["tort-law","health-medical-law","insurance-law","procedural-law"],
    ["medical malpractice standard of care","personal injury negligence","statute of repose","expert affidavit"],
    [],
  ),
} satisfies Record<LawType, LexaraLegalDomainProfile>;

export function getLexaraLegalDomainProfile(lawType?: string): LexaraLegalDomainProfile | undefined {
  if (!lawType) return undefined;
  const normalized = lawType.trim().toLowerCase().replace(/\s+/g, '-') as LawType;
  return LEXARA_LEGAL_DOMAIN_PROFILES[normalized];
}

export function formatLexaraDomainSpecialization(profile?: LexaraLegalDomainProfile): string {
  if (!profile) return '';

  return [
    `SELECTED-BOOK SPECIALIZATION: ${profile.displayName}`,
    profile.specialistDirective,
    `Core issue-spotting: ${profile.coreIssues.join('; ')}.`,
    `Procedure/deadline focus: ${profile.procedureAndDeadlineFocus.join('; ')}.`,
    `Authority hierarchy for this domain: ${profile.authorityPriorities.join('; ')}.`,
    `Jurisdiction facts to resolve when material: ${profile.jurisdictionQuestions.join('; ')}.`,
    `Potential remedies/outcomes to test: ${profile.remediesAndOutcomes.join('; ')}.`,
    `Adjacent domains to spot without losing the selected specialization: ${profile.adjacentDomains.join('; ')}.`,
    'Treat this profile as a research map, not as controlling law. Verify current jurisdiction-specific primary authority before stating a legal rule, deadline, or citation as reliable.',
  ].join('\n');
}
