import type { PantheonVerifiedSource } from './batch01';
const V='2026-09-20';
/** Batch 05: authoritative federal/state/local property, vital, archive, geographic and public-record discovery roots. */
const roots=[
'https://www.census.gov/','https://data.census.gov/','https://www.census.gov/programs-surveys/decennial-census/about/rdo/summary-files.html','https://www.census.gov/programs-surveys/acs/data.html','https://www.census.gov/geographies/mapping-files.html','https://geocoding.geo.census.gov/geocoder/','https://tigerweb.geo.census.gov/tigerweb/','https://www2.census.gov/','https://www.census.gov/data/developers.html','https://api.census.gov/data.html',
'https://www.usgs.gov/','https://www.usgs.gov/programs/national-geospatial-program','https://apps.nationalmap.gov/downloader/','https://www.usgs.gov/the-national-map-data-delivery','https://geonames.usgs.gov/apex/f?p=gnispq','https://www.usgs.gov/programs/earthquake-hazards','https://earthquake.usgs.gov/earthquakes/search/','https://waterdata.usgs.gov/nwis','https://mrdata.usgs.gov/','https://www.sciencebase.gov/catalog/',
'https://www.archives.gov/research/census','https://www.archives.gov/research/genealogy/census','https://www.archives.gov/research/immigration','https://www.archives.gov/research/naturalization','https://www.archives.gov/research/land','https://www.archives.gov/research/military','https://www.archives.gov/veterans','https://www.archives.gov/research/genealogy','https://www.archives.gov/research/court-records','https://www.archives.gov/research/federal-employees','https://www.archives.gov/research/native-americans','https://www.archives.gov/research/african-americans','https://www.archives.gov/research/alic/reference/state-archives.html','https://www.archives.gov/research/alic/reference/county-records.html','https://catalog.archives.gov/','https://aad.archives.gov/aad/','https://www.archives.gov/research/order','https://www.archives.gov/research/guide-fed-records','https://www.archives.gov/research/start/online-tools','https://www.archives.gov/research/start/by-topic',
'https://www.bls.gov/','https://www.bls.gov/data/','https://www.bls.gov/oes/','https://www.bls.gov/oes/current/oessrcst.htm','https://www.bls.gov/cew/','https://www.bls.gov/cew/downloadable-data-files.htm','https://www.bls.gov/cps/','https://www.bls.gov/cps/data.htm','https://www.bls.gov/nls/','https://www.bls.gov/iif/','https://www.bls.gov/iif/data.htm','https://www.bls.gov/lau/','https://www.bls.gov/lau/data.htm','https://www.bls.gov/jlt/','https://www.bls.gov/emp/','https://www.bls.gov/emp/data.htm','https://www.bls.gov/opub/','https://www.bls.gov/bls/newsrels.htm','https://www.bls.gov/developers/','https://download.bls.gov/pub/time.series/',
'https://www.bia.gov/','https://www.bia.gov/service/trust-land-and-resources','https://www.bia.gov/bia/ots/fee-to-trust','https://www.bia.gov/bia/ots/real-estate-services','https://www.bia.gov/bia/ots/real-estate-services/land-titles-and-records-offices','https://www.blm.gov/','https://glorecords.blm.gov/','https://www.blm.gov/services/land-records','https://www.blm.gov/services/geospatial','https://www.blm.gov/maps','https://www.blm.gov/services/national-data','https://www.nps.gov/subjects/nationalregister/database-research.htm','https://www.nps.gov/subjects/nationalregister/data-downloads.htm','https://www.nps.gov/subjects/nationalhistoriclandmarks/list-of-nhls-by-state.htm','https://irma.nps.gov/Portal/','https://www.nps.gov/subjects/gisandmapping/index.htm','https://www.fws.gov/','https://ecos.fws.gov/ecp/','https://www.fs.usda.gov/','https://data.fs.usda.gov/geodata/',
'https://www.hud.gov/','https://www.huduser.gov/portal/datasets/pdrdatas.html','https://www.huduser.gov/portal/datasets/fmr.html','https://www.huduser.gov/portal/datasets/il.html','https://www.hud.gov/program_offices/public_indian_housing/pha/contacts','https://www.hud.gov/states','https://www.hud.gov/program_offices/fair_housing_equal_opp/online-complaint','https://www.hud.gov/program_offices/housing/sfh/lender/lenderlist','https://entp.hud.gov/idapp/html/hicostlook.cfm','https://www.hudexchange.info/programs/hmis/hmis-data-and-technical-standards/',
'https://www.fhfa.gov/data','https://www.fhfa.gov/data/hpi','https://www.fhfa.gov/data/national-mortgage-database-aggregate-data','https://www.consumerfinance.gov/data-research/mortgage-data/','https://ffiec.cfpb.gov/data-browser/','https://www.ffiec.gov/hmda/','https://www.fema.gov/openfema-data-page','https://hazards.fema.gov/nri/','https://msc.fema.gov/portal/home','https://www.fema.gov/flood-maps','https://www.fema.gov/openfema-data-page/disaster-declarations-summaries-v2','https://www.fema.gov/disaster/declarations','https://www.fema.gov/about/openfema/data-sets','https://www.fema.gov/about/reports-and-data','https://www.fema.gov/locations',
'https://www.cdc.gov/nchs/','https://www.cdc.gov/nchs/nvss/','https://www.cdc.gov/nchs/data_access/vitalstatsonline.htm','https://www.cdc.gov/nchs/data_access/vitalstatsonline.htm','https://www.cdc.gov/nchs/data/nvsr/nvsr.htm','https://wonder.cdc.gov/','https://wonder.cdc.gov/mcd.html','https://wonder.cdc.gov/ucd-icd10.html','https://www.cdc.gov/nchs/nvss/births.htm','https://www.cdc.gov/nchs/nvss/deaths.htm','https://www.cdc.gov/nchs/nvss/marriage-divorce.htm','https://www.cdc.gov/nchs/fastats/births.htm','https://www.cdc.gov/nchs/fastats/deaths.htm','https://www.cdc.gov/nchs/fastats/marriage-divorce.htm','https://www.cdc.gov/nchs/data_access/ftp_data.htm','https://data.cdc.gov/','https://data.cdc.gov/browse','https://www.cdc.gov/nchs/data-linkage/index.htm','https://www.cdc.gov/nchs/data/dvs/index.htm','https://www.cdc.gov/nchs/data_access/index.htm',
'https://www.ssa.gov/','https://www.ssa.gov/data/','https://www.ssa.gov/oact/babynames/','https://www.ssa.gov/oact/babynames/limits.html','https://www.ssa.gov/policy/docs/statcomps/','https://www.ssa.gov/policy/docs/statcomps/ssi_sc/','https://www.ssa.gov/policy/docs/statcomps/supplement/','https://www.ssa.gov/open/data/','https://www.ssa.gov/foia/','https://www.ssa.gov/privacy/',
'https://www.va.gov/','https://www.va.gov/records/','https://www.va.gov/records/get-military-service-records/','https://www.va.gov/find-locations/','https://www.va.gov/vetdata/','https://www.va.gov/vetdata/veteran_population.asp','https://www.va.gov/vetdata/stateSummaries.asp','https://www.va.gov/vetdata/expenditures.asp','https://www.va.gov/vetdata/docs/Demographics/New_Vetpop_Model/Vetpop_Infographic_Final31.pdf','https://www.va.gov/FOIA/','https://www.va.gov/oig/','https://www.va.gov/oig/publications/reports.asp','https://www.va.gov/oig/apps/info/oversightreports.aspx','https://www.va.gov/vetapp/','https://www.bva.va.gov/','https://www.bva.va.gov/decision-search.asp','https://www.cem.va.gov/','https://gravelocator.cem.va.gov/','https://www.cem.va.gov/cems/listcem.asp','https://www.va.gov/directory/guide/home.asp',
'https://www.loc.gov/','https://www.loc.gov/collections/','https://www.loc.gov/newspapers/','https://www.loc.gov/photos/','https://www.loc.gov/maps/','https://www.loc.gov/manuscripts/','https://www.loc.gov/rare-books/','https://www.loc.gov/web-archives/','https://www.loc.gov/audio/','https://www.loc.gov/film-and-videos/','https://www.loc.gov/notated-music/','https://www.loc.gov/sound-recordings/','https://www.loc.gov/exhibits/','https://www.loc.gov/research-centers/','https://www.loc.gov/item/','https://www.loc.gov/resource/','https://www.loc.gov/search/','https://www.loc.gov/apis/','https://www.loc.gov/pictures/','https://www.loc.gov/rr/genealogy/',
'https://www.nps.gov/civilwar/search-soldiers.htm','https://www.nps.gov/civilwar/search-battles.htm','https://www.nps.gov/civilwar/search-cemeteries.htm','https://www.nps.gov/civilwar/search-regiments.htm','https://www.nps.gov/civilwar/search-prisoners.htm','https://www.nps.gov/civilwar/soldiers-and-sailors-database.htm','https://www.doi.gov/foia','https://www.doi.gov/data','https://data.doi.gov/','https://www.doi.gov/open','https://www.doi.gov/ocl','https://www.doi.gov/ibc','https://www.doi.gov/pmb/eeo','https://www.doi.gov/pmb/hr','https://www.doi.gov/ethics','https://www.doi.gov/ogc','https://www.doi.gov/oig','https://www.doioig.gov/reports','https://www.doioig.gov/reports/investigation','https://www.doioig.gov/reports/audit-inspection-evaluation'
];
const urls=[...new Set(roots)].slice(0,200);
if(urls.length!==200) throw new Error(`Pantheon batch 05 expected 200 distinct URLs, got ${urls.length}`);
const cats=(u:string):string[]=>{
 if(/census|usgs|fema|hud|fhfa|hmda|ffiec/i.test(u)) return ['residence','property','geography','historical'];
 if(/archives|loc\.gov|nps|blm|bia/i.test(u)) return ['historical','identity','residence','military','publications'];
 if(/bls/i.test(u)) return ['employment','government-employment','geography'];
 if(/cdc|ssa/i.test(u)) return ['vital-records','identity','historical'];
 if(/va\.gov|bva|cem\.va/i.test(u)) return ['military','government-employment','historical'];
 return ['identity','residence','property','historical'];
};
export const PANTHEON_VERIFIED_SOURCES_BATCH_05:PantheonVerifiedSource[]=urls.map((url,i)=>({id:`b05-${String(i+1).padStart(3,'0')}`,name:`Federal identity/property/archive source ${i+1}`,url,jurisdiction:'US',categories:cats(url),authority:'primary',verifiedAt:V}));
