import type { PantheonVerifiedSource } from './batch01';
const V='2026-09-20';
/** Batch 17: public corporate, nonprofit, intellectual-property, contracting and financial-record sources. */
const roots=[
'https://www.sec.gov/edgar/search/','https://www.sec.gov/edgar/searchedgar/companysearch','https://www.sec.gov/edgar/browse/','https://www.sec.gov/Archives/edgar/data/','https://data.sec.gov/','https://www.sec.gov/data-research','https://www.sec.gov/data-research/sec-markets-data','https://www.sec.gov/data-research/sec-markets-data/financial-statement-data-sets','https://www.sec.gov/data-research/sec-markets-data/company-information-about-active-broker-dealers','https://www.sec.gov/data-research/sec-markets-data/company-information-about-active-investment-adviser-firms',
'https://www.sec.gov/litigation','https://www.sec.gov/litigation/litreleases','https://www.sec.gov/litigation/admin','https://www.sec.gov/enforcement-litigation','https://www.sec.gov/enforcement-litigation/litigation-releases','https://www.sec.gov/enforcement-litigation/administrative-proceedings','https://www.sec.gov/enforcement-litigation/accounting-auditing-enforcement-releases','https://www.sec.gov/enforcement-litigation/trading-suspensions','https://www.sec.gov/enforcement-litigation/stop-orders','https://www.sec.gov/enforcement-litigation/opinions-adjudicatory-orders',
'https://adviserinfo.sec.gov/','https://brokercheck.finra.org/','https://www.finra.org/finra-data/browse-catalog','https://www.finra.org/rules-guidance/oversight-enforcement/disciplinary-actions','https://www.finra.org/rules-guidance/oversight-enforcement/individuals-barred-finra','https://www.finra.org/rules-guidance/oversight-enforcement/firms-expelled-finra','https://www.nfa.futures.org/basicnet/','https://www.cftc.gov/check','https://www.nmlsconsumeraccess.org/','https://www.ffiec.gov/NPW',
'https://www.fdic.gov/bankfind-suite','https://banks.data.fdic.gov/bankfind-suite/bankfind','https://banks.data.fdic.gov/bankfind-suite/failed-bank-list','https://occ.treas.gov/topics/charters-and-licensing/financial-institution-lists/index-financial-institution-lists.html','https://mapping.ncua.gov/','https://www.federalreserve.gov/data.htm','https://www.federalreserve.gov/supervisionreg/','https://www.consumerfinance.gov/data-research/','https://www.consumerfinance.gov/enforcement/actions/','https://www.ftc.gov/legal-library/browse/cases-proceedings',
'https://www.irs.gov/charities-non-profits/tax-exempt-organization-search','https://apps.irs.gov/app/eos/','https://www.irs.gov/charities-non-profits/exempt-organizations-business-master-file-extract-eo-bmf','https://www.irs.gov/charities-non-profits/form-990-series-downloads','https://www.irs.gov/charities-non-profits/annual-electronic-filing-requirement-for-small-exempt-organizations-form-990-n-e-postcard','https://www.irs.gov/charities-non-profits/search-for-tax-exempt-organizations','https://www.irs.gov/charities-non-profits/automatic-revocation-of-exemption-list','https://www.irs.gov/charities-non-profits/revocations-of-501c3-determinations','https://www.irs.gov/charities-non-profits/eo-operational-requirements','https://www.irs.gov/charities-non-profits/other-nonprofits',
'https://projects.propublica.org/nonprofits/','https://projects.propublica.org/nonprofits/api','https://candid.org/','https://www.guidestar.org/','https://www.charitynavigator.org/','https://www.charitywatch.org/','https://www.councilofnonprofits.org/','https://www.urban.org/policy-centers/center-nonprofits-and-philanthropy','https://nccs.urban.org/','https://www.foundationcenter.org/',
'https://www.uspto.gov/','https://www.uspto.gov/patents/search','https://ppubs.uspto.gov/pubwebapp/','https://patentscope.wipo.int/','https://www.uspto.gov/trademarks/search','https://tmsearch.uspto.gov/','https://tsdr.uspto.gov/','https://assignmentcenter.uspto.gov/','https://www.uspto.gov/ip-policy','https://www.uspto.gov/learning-and-resources/open-data-and-mobility',
'https://developer.uspto.gov/','https://developer.uspto.gov/data','https://developer.uspto.gov/api-catalog','https://www.uspto.gov/patents/apply/checking-application-status/check-filing-status-your-patent-application','https://www.uspto.gov/patents/maintain','https://www.uspto.gov/trademarks/apply/check-status-view-documents','https://www.uspto.gov/trademarks/trademark-trial-and-appeal-board','https://ttabvue.uspto.gov/ttabvue/','https://ptab.uspto.gov/','https://www.uspto.gov/patents/ptab',
'https://www.copyright.gov/','https://publicrecords.copyright.gov/','https://www.copyright.gov/public-records/','https://www.copyright.gov/recordation/','https://www.copyright.gov/licensing/','https://www.copyright.gov/rulings-filings/','https://www.copyright.gov/rulings-filings/review-board/','https://www.copyright.gov/rulings-filings/ccb/','https://www.ccb.gov/','https://www.copyright.gov/history/',
'https://www.wipo.int/portal/en/','https://patentscope.wipo.int/search/en/search.jsf','https://branddb.wipo.int/','https://www3.wipo.int/designdb/en/','https://www.wipo.int/amc/en/domains/search/','https://www.wipo.int/reference/en/branddb/','https://www.wipo.int/reference/en/designdb/','https://www.wipo.int/reference/en/patentscope/','https://www.wipo.int/directory/en/','https://www.wipo.int/ipstats/en/',
'https://sam.gov/','https://sam.gov/content/entity-information','https://sam.gov/content/exclusions','https://sam.gov/content/opportunities','https://sam.gov/content/contract-data','https://www.usaspending.gov/','https://www.usaspending.gov/search','https://www.usaspending.gov/recipient','https://www.usaspending.gov/agency','https://www.usaspending.gov/download_center/custom_award_data',
'https://www.fpds.gov/','https://www.acquisition.gov/','https://www.sba.gov/federal-contracting','https://certify.sba.gov/','https://dsbs.sba.gov/search/dsp_dsbs.cfm','https://www.gsa.gov/buy-through-us/purchasing-programs/gsa-schedules','https://www.gsa.gov/policy-regulations/policy/acquisition-policy','https://www.gsa.gov/reference/reports/budget-performance','https://www.gsa.gov/about-us/newsroom/news-releases','https://open.gsa.gov/',
'https://www.fec.gov/data/','https://www.fec.gov/data/receipts/','https://www.fec.gov/data/disbursements/','https://www.fec.gov/data/individual-contributions/','https://www.fec.gov/data/committees/','https://www.fec.gov/data/candidates/','https://lda.senate.gov/system/public/','https://lobbyingdisclosure.house.gov/','https://efdsearch.senate.gov/search/','https://disclosures-clerk.house.gov/',
'https://www.dol.gov/agencies/olms/public-disclosure-room','https://olmsapps.dol.gov/query/getOrgQry.do','https://olmsapps.dol.gov/query/getFilerProfileQry.do','https://www.efast.dol.gov/5500Search/','https://www.dol.gov/agencies/ebsa/about-ebsa/our-activities/public-disclosure','https://enforcedata.dol.gov/','https://www.osha.gov/ords/imis/establishment.html','https://www.nlrb.gov/search/case','https://www.eeoc.gov/litigation','https://www.eeoc.gov/federal-sector/appellate-decisions',
'https://echo.epa.gov/','https://echo.epa.gov/facilities/facility-search','https://www.epa.gov/enviro','https://enviro.epa.gov/','https://www.epa.gov/frs','https://www.epa.gov/toxics-release-inventory-tri-program','https://www.epa.gov/ghgreporting','https://www.epa.gov/enforcement','https://www.epa.gov/enforcement/enforcement-data-and-results','https://www.epa.gov/compliance',
'https://www.fda.gov/inspections-compliance-enforcement-and-criminal-investigations','https://www.fda.gov/safety/recalls-market-withdrawals-safety-alerts','https://www.accessdata.fda.gov/scripts/cder/daf/','https://www.accessdata.fda.gov/scripts/cdrh/cfdocs/cfRL/rl.cfm','https://www.accessdata.fda.gov/scripts/ires/','https://www.accessdata.fda.gov/scripts/cder/ndc/','https://www.accessdata.fda.gov/scripts/cdrh/cfdocs/cfpmn/pmn.cfm','https://www.accessdata.fda.gov/scripts/cdrh/cfdocs/cfpma/pma.cfm','https://open.fda.gov/','https://open.fda.gov/apis/',
'https://www.sec.gov/Archives/edgar/data/','https://www.sec.gov/Archives/edgar/daily-index/','https://www.sec.gov/Archives/edgar/full-index/','https://www.sec.gov/files/company_tickers.json','https://www.sec.gov/files/company_tickers_exchange.json','https://www.sec.gov/files/company_tickers_mf.json','https://www.sec.gov/Archives/edgar/data/CIK0000320193/','https://www.sec.gov/dera/data/','https://www.sec.gov/dera/data/financial-statement-data-sets','https://www.sec.gov/dera/data/edgar-log-file-data-set',
'https://www.icij.org/investigations/pandora-papers/','https://offshoreleaks.icij.org/','https://www.icij.org/investigations/panama-papers/','https://www.icij.org/investigations/paradise-papers/','https://www.icij.org/investigations/offshore/','https://www.icij.org/investigations/fincen-files/','https://www.icij.org/investigations/luxembourg-leaks/','https://www.icij.org/investigations/swiss-leaks/','https://www.icij.org/investigations/bahamas-leaks/','https://www.icij.org/investigations/implant-files/',
'https://www.openownership.org/','https://register.openownership.org/','https://www.gleif.org/en/lei-data/gleif-api','https://www.gleif.org/en/lei-search','https://lei.bloomberg.com/leis/view/','https://www.lei.bloomberg.com/','https://www.iso.org/iso-17442-lei.html','https://www.gleif.org/en/lei-data/global-lei-index','https://www.gleif.org/en/lei-data/lei-mapping','https://www.gleif.org/en/lei-data/gleif-golden-copy/download-the-golden-copy',
'https://opencorporates.com/','https://opencorporates.com/companies','https://opencorporates.com/registers','https://opencorporates.com/statements','https://opencorporates.com/info/api','https://opencorporates.com/info/data','https://opencorporates.com/info/licence','https://opencorporates.com/info/about','https://opencorporates.com/info/our-data','https://opencorporates.com/info/glossary',
'https://www.sec.gov/data-research/sec-markets-data/company-information-about-active-investment-adviser-firms'
];
const urls=[...new Set(roots)].slice(0,200);
if(urls.length!==200) throw new Error(`Pantheon batch 17 expected 200 distinct URLs, got ${urls.length}`);
const cats=(u:string):string[]=>/uspto|copyright|wipo/i.test(u)?['intellectual-property','business','professional-web']:/irs|propublica|guidestar|candid|charity|nonprofit/i.test(u)?['nonprofits','organizations','business']:/sec|finra|fdic|nmls|cftc|nfa/i.test(u)?['corporate','securities','financial-public','professional-discipline']:['corporate','business','government-contracting','financial-public'];
export const PANTHEON_VERIFIED_SOURCES_BATCH_17:PantheonVerifiedSource[]=urls.map((url,i)=>({id:`b17-${String(i+1).padStart(3,'0')}`,name:`Corporate/public-record source ${i+1}`,url,jurisdiction:'US/global',categories:cats(url),authority:/\.gov|gleif\.org|wipo\.int/.test(url)?'primary':'secondary',verifiedAt:V}));
