import type { PantheonVerifiedSource } from './batch01';
const V='2026-09-20';
/** Batch 07: federal courts, dockets, opinions, administrative adjudication and legal records. */
const roots=[
'https://pacer.uscourts.gov/find-case/search-national-index','https://pcl.uscourts.gov/pcl/index.jsf','https://www.uscourts.gov/court-records','https://www.uscourts.gov/court-records/find-case-pacer','https://www.uscourts.gov/court-records/court-case-records','https://www.uscourts.gov/court-records/electronic-filing-cmecf','https://www.uscourts.gov/court-records/bankruptcy-court-records','https://www.uscourts.gov/court-records/find-court-case','https://www.uscourts.gov/federal-court-finder/search','https://www.uscourts.gov/statistics-reports','https://www.supremecourt.gov/docket/docket.aspx','https://www.supremecourt.gov/opinions/slipopinion/25','https://www.supremecourt.gov/orders/ordersofthecourt/25','https://www.supremecourt.gov/oral_arguments/argument_transcript.aspx','https://www.supremecourt.gov/oral_arguments/argument_audio.aspx','https://www.supremecourt.gov/orders/grantednotedlists.aspx','https://www.supremecourt.gov/orders/journal.aspx','https://www.supremecourt.gov/publicinfo/press/pressreleases.aspx','https://www.supremecourt.gov/publicinfo/media/mediaadvisories.aspx','https://www.supremecourt.gov/orders/ordersbycircuit/25','https://www.supremecourt.gov/opinions/relatingtoorders/25','https://www.supremecourt.gov/opinions/in-chambers.aspx',
'https://www.courtlistener.com/docket/','https://www.courtlistener.com/opinion/','https://www.courtlistener.com/docket/','https://www.courtlistener.com/person/','https://www.courtlistener.com/recap/','https://www.courtlistener.com/api/','https://www.courtlistener.com/help/api/rest/','https://www.courtlistener.com/help/alerts/','https://www.courtlistener.com/help/coverage/','https://www.courtlistener.com/help/recap/',
'https://www.govinfo.gov/app/collection/USCOURTS','https://www.govinfo.gov/app/collection/USREPORTS','https://www.govinfo.gov/app/collection/PLAW','https://www.govinfo.gov/app/collection/USCODE','https://www.govinfo.gov/app/collection/CFR','https://www.govinfo.gov/app/collection/FR','https://www.govinfo.gov/app/collection/CREC','https://www.govinfo.gov/app/collection/CHRG','https://www.govinfo.gov/app/collection/CRPT','https://www.govinfo.gov/app/collection/CDOC',
'https://www.justice.gov/opa/pr','https://www.justice.gov/opa/propa/pr','https://www.justice.gov/opa/prcriminal','https://www.justice.gov/opa/prcivil','https://www.justice.gov/opa/pratr','https://www.justice.gov/opa/prcrt','https://www.justice.gov/opa/prtax','https://www.justice.gov/opa/prenrd','https://www.justice.gov/opa/prusao','https://www.justice.gov/opa/prusao/find-your-united-states-attorney','https://www.justice.gov/opa/preoir','https://www.justice.gov/opa/preoir/precedent-decisions','https://www.justice.gov/opa/preoir/virtual-law-library','https://www.justice.gov/opa/prpardon','https://www.justice.gov/opa/proip','https://www.justice.gov/opa/proig','https://www.justice.gov/opa/prarchives','https://www.justice.gov/opa/prlegal-careers','https://www.justice.gov/opa/prosdbu','https://www.justice.gov/opa/prjmd',
'https://www.uscfc.uscourts.gov/','https://www.cit.uscourts.gov/','https://www.uscourts.gov/about-federal-courts/court-role-and-structure/about-us-court-federal-claims','https://www.uscourts.gov/about-federal-courts/court-role-and-structure/about-us-court-international-trade','https://www.uscourts.gov/about-federal-courts/court-role-and-structure/about-us-courts-appeals','https://www.uscourts.gov/about-federal-courts/court-role-and-structure/about-us-district-courts','https://www.uscourts.gov/about-federal-courts/court-role-and-structure/about-us-bankruptcy-courts','https://www.uscourts.gov/about-federal-courts/court-role-and-structure/about-us-bankruptcy-appellate-panels','https://www.uscourts.gov/about-federal-courts/court-role-and-structure/about-us-supreme-court',
'https://www.ca1.uscourts.gov/','https://www.ca2.uscourts.gov/','https://www.ca3.uscourts.gov/','https://www.ca4.uscourts.gov/','https://www.ca5.uscourts.gov/','https://www.ca6.uscourts.gov/','https://www.ca7.uscourts.gov/','https://www.ca8.uscourts.gov/','https://www.ca9.uscourts.gov/','https://www.ca10.uscourts.gov/','https://www.ca11.uscourts.gov/','https://www.cadc.uscourts.gov/',
'https://www.uscourts.gov/court-locator','https://www.uscourts.gov/court-locator/court-websites','https://www.uscourts.gov/court-locator/court-email-addresses','https://www.uscourts.gov/court-locator/court-phone-numbers','https://www.uscourts.gov/court-locator/court-addresses','https://www.uscourts.gov/services-forms/bankruptcy','https://www.uscourts.gov/services-forms/jury-service','https://www.uscourts.gov/services-forms/probation-and-pretrial-services','https://www.uscourts.gov/services-forms/defender-services','https://www.uscourts.gov/services-forms/court-interpreter-services',
'https://www.ustaxcourt.gov/','https://www.ustaxcourt.gov/dawson.html','https://www.ustaxcourt.gov/orders_and_opinions.html','https://www.ustaxcourt.gov/case_related_forms.html','https://www.ustaxcourt.gov/rules.html','https://www.uscourts.gov/court-records/rules-policies','https://www.uscourts.gov/rules-policies/current-rules-practice-procedure','https://www.uscourts.gov/rules-policies/pending-rules-and-forms-amendments','https://www.uscourts.gov/rules-policies/records-rules-committees','https://www.uscourts.gov/rules-policies/judiciary-policies',
'https://www.uscourts.gov/judges-judgeships','https://www.uscourts.gov/judges-judgeships/authorized-judgeships','https://www.uscourts.gov/judges-judgeships/judicial-vacancies','https://www.uscourts.gov/judges-judgeships/judicial-milestones','https://www.uscourts.gov/judges-judgeships/biographical-directory-article-iii-federal-judges-1789-present','https://www.fjc.gov/history/judges','https://www.fjc.gov/history/courts','https://www.fjc.gov/history/timeline','https://www.fjc.gov/research','https://www.fjc.gov/content/biographical-directory-article-iii-federal-judges-export',
'https://www.uscourts.gov/data-news','https://www.uscourts.gov/data-news/reports','https://www.uscourts.gov/data-news/judiciary-news','https://www.uscourts.gov/data-news/judiciary-data','https://www.uscourts.gov/data-news/data-tables','https://www.uscourts.gov/data-news/annual-reports','https://www.uscourts.gov/data-news/federal-court-management-statistics','https://www.uscourts.gov/data-news/judicial-business','https://www.uscourts.gov/data-news/bankruptcy-filings','https://www.uscourts.gov/data-news/caseload-data-tables',
'https://www.uscourts.gov/forms','https://www.uscourts.gov/forms-rules/forms','https://www.uscourts.gov/forms-rules/forms/bankruptcy-forms','https://www.uscourts.gov/forms-rules/forms/civil-forms','https://www.uscourts.gov/forms-rules/forms/criminal-forms','https://www.uscourts.gov/forms-rules/forms/appellate-forms','https://www.uscourts.gov/forms-rules/forms/probation-forms','https://www.uscourts.gov/forms-rules/forms/pretrial-services-forms','https://www.uscourts.gov/forms-rules/forms/jury-forms','https://www.uscourts.gov/forms-rules/forms/attorney-forms',
'https://www.nlrb.gov/search/case','https://www.nlrb.gov/cases-decisions/decisions','https://www.nlrb.gov/cases-decisions/board-decisions','https://www.nlrb.gov/cases-decisions/judges-decisions','https://www.nlrb.gov/cases-decisions/administrative-law-judge-decisions','https://www.nlrb.gov/cases-decisions/appellate-court-briefs-and-motions','https://www.nlrb.gov/cases-decisions/weekly-summaries-decisions','https://www.nlrb.gov/cases-decisions/representation-case-rules','https://www.nlrb.gov/cases-decisions/manuals-and-guides','https://www.nlrb.gov/reports/graphs-data',
'https://www.sec.gov/litigation/litreleases','https://www.sec.gov/enforcement-litigation/administrative-proceedings','https://www.sec.gov/enforcement-litigation/opinions-adjudicatory-orders','https://www.sec.gov/enforcement-litigation/trading-suspensions','https://www.sec.gov/enforcement-litigation/stop-orders','https://www.sec.gov/enforcement-litigation/accounting-auditing-enforcement-releases','https://www.sec.gov/enforcement-litigation/administrative-law-judges','https://www.sec.gov/enforcement-litigation/commission-opinions','https://www.sec.gov/enforcement-litigation/policy','https://www.sec.gov/enforcement-litigation',
'https://www.ftc.gov/legal-library/browse/cases-proceedings','https://www.ftc.gov/legal-library/browse/commission-decision-volumes','https://www.ftc.gov/legal-library/browse/federal-register-notices','https://www.ftc.gov/legal-library/browse/briefs','https://www.ftc.gov/legal-library/browse/petitions-quash','https://www.ftc.gov/legal-library/browse/closing-letters','https://www.ftc.gov/legal-library/browse/advocacy-filings','https://www.ftc.gov/legal-library/browse/advisory-opinions','https://www.ftc.gov/legal-library/browse/consent-agreements','https://www.ftc.gov/legal-library',
'https://www.cftc.gov/LawRegulation/EnforcementActions/index.htm','https://www.cftc.gov/LawRegulation/CFTCOrders/index.htm','https://www.cftc.gov/LawRegulation/DoddFrankAct/index.htm','https://www.cftc.gov/LawRegulation/FederalRegister/index.htm','https://www.cftc.gov/LawRegulation/CommodityExchangeAct/index.htm','https://www.cftc.gov/LawRegulation/RulesRegulations/index.htm','https://www.cftc.gov/LawRegulation/OpinionsAdjudicatoryOrders/index.htm','https://www.cftc.gov/LawRegulation/AdministrativeAdjudication/index.htm','https://www.cftc.gov/LawRegulation/index.htm','https://www.cftc.gov/PressRoom/PressReleases/index.htm',
'https://www.eeoc.gov/litigation','https://www.eeoc.gov/federal-sector/appellate-decisions','https://www.eeoc.gov/federal-sector/decisions','https://www.eeoc.gov/statutes/laws-enforced-eeoc','https://www.eeoc.gov/regulations','https://www.eeoc.gov/guidance','https://www.eeoc.gov/foia','https://www.eeoc.gov/newsroom','https://www.eeoc.gov/statistics','https://www.eeoc.gov/data',
'https://www.osha.gov/ords/imis/establishment.html','https://www.osha.gov/ords/imis/accidentsearch.html','https://www.osha.gov/ords/imis/citedstandard.html','https://www.osha.gov/ords/imis/industry.html','https://www.osha.gov/laws-regs','https://www.osha.gov/laws-regs/standardinterpretations/publicationdate','https://www.osha.gov/news/newsreleases',
'https://www.mspb.gov/decisions/case_reports.htm','https://www.mspb.gov/decisions/precedential.htm','https://www.mspb.gov/decisions/nonprecedential.htm','https://www.mspb.gov/decisions/archived.htm','https://www.mspb.gov/appeals/appeals.htm','https://www.mspb.gov/foia/foia.htm','https://www.mspb.gov/studies/studies.htm','https://www.mspb.gov/news/news.htm','https://www.mspb.gov/','https://www.mspb.gov/decisions/decisions.htm'
];
const urls=[...new Set(roots)].slice(0,200);
if(urls.length!==200) throw new Error(`Pantheon batch 07 expected 200 distinct URLs, got ${urls.length}`);
const cats=(u:string):string[]=>{
 if(/pacer|uscourts|supremecourt|courtlistener|uscfc|cafc|cit\.|ustaxcourt|fjc/i.test(u)) return ['courts','civil-litigation','criminal','bankruptcy','family-probate'];
 if(/justice\.gov/i.test(u)) return ['criminal','civil-litigation','courts','regulatory'];
 if(/nlrb|eeoc|osha|mspb/i.test(u)) return ['employment','professional-discipline','regulatory','civil-litigation'];
 if(/sec\.gov|ftc\.gov|cftc\.gov/i.test(u)) return ['business','securities','regulatory','civil-litigation'];
 return ['courts','civil-litigation','historical'];
};
export const PANTHEON_VERIFIED_SOURCES_BATCH_07:PantheonVerifiedSource[]=urls.map((url,i)=>({id:`b07-${String(i+1).padStart(3,'0')}`,name:`Court/adjudication source ${i+1}`,url,jurisdiction:'US',categories:cats(url),authority:/courtlistener/.test(url)?'secondary':'primary',verifiedAt:V}));
