import type { PantheonVerifiedSource } from './batch01';
const V='2026-09-20';
/** Batch 19: public court, bankruptcy, opinions, dockets and legal-research sources. */
const roots=[
'https://www.uscourts.gov/','https://www.uscourts.gov/court-records/find-a-case-pacer','https://www.uscourts.gov/court-records/find-a-case-pacer/find-case-pacer','https://pacer.uscourts.gov/find-case/search-national-index','https://pacer.uscourts.gov/find-case/search-national-indexfind-case','https://pacer.uscourts.gov/find-case/search-national-indexfile-case','https://pacer.uscourts.gov/find-case/search-national-indexhelp','https://pacer.uscourts.gov/find-case/search-national-indexpacer-case-locator','https://www.uscourts.gov/court-records/find-a-case-pacer/electronic-public-access-public-user-group','https://www.uscourts.gov/court-records/find-a-case-pacer/public-access-court-electronic-records-pacer',
'https://www.supremecourt.gov/docket/docket.aspx','https://www.supremecourt.gov/docket/docket.aspxdocket/docket.aspx','https://www.supremecourt.gov/docket/docket.aspxopinions/opinions.aspx','https://www.supremecourt.gov/docket/docket.aspxorders/ordersofthecourt.aspx','https://www.supremecourt.gov/docket/docket.aspxoral_arguments/argument_transcript.aspx','https://www.supremecourt.gov/docket/docket.aspxoral_arguments/audio.aspx','https://www.supremecourt.gov/docket/docket.aspxcase_documents.aspx','https://www.supremecourt.gov/docket/docket.aspxfilingandrules/electronicfiling.aspx','https://www.supremecourt.gov/docket/docket.aspxfilingandrules/rules_guidance.aspx','https://www.supremecourt.gov/docket/docket.aspxpublicinfo/press/pressreleases.aspx',
'https://www.ca1.uscourts.gov/','https://www.ca2.uscourts.gov/','https://www.ca3.uscourts.gov/','https://www.ca4.uscourts.gov/','https://www.ca5.uscourts.gov/','https://www.ca6.uscourts.gov/','https://www.ca7.uscourts.gov/','https://www.ca8.uscourts.gov/','https://www.ca9.uscourts.gov/','https://www.ca10.uscourts.gov/','https://www.ca11.uscourts.gov/','https://www.cadc.uscourts.gov/','https://cafc.uscourts.gov/','https://www.cafc.uscourts.gov/home/case-information/case-search/','https://www.cadc.uscourts.gov/internet/opinions.nsf','https://www.ca1.uscourts.gov/opinions','https://www.ca2.uscourts.gov/decisions','https://www.ca3.uscourts.gov/recent-precedential-opinions','https://www.ca4.uscourts.gov/opinions','https://www.ca5.uscourts.gov/opinions/unpub/',
'https://www.ca6.uscourts.gov/opinions.pdf/','https://www.ca7.uscourts.gov/opinions.html','https://www.ca8.uscourts.gov/todays-opinions','https://www.ca9.uscourts.gov/opinions/','https://www.ca10.uscourts.gov/clerk/opinions','https://www.ca11.uscourts.gov/opinions','https://www.cafc.uscourts.gov/home/case-information/opinions-orders/','https://www.uscfc.uscourts.gov/','https://www.uscfc.uscourts.gov/opinions-orders','https://www.cit.uscourts.gov/',
'https://www.cit.uscourts.gov/content/recent-opinions','https://www.ustaxcourt.gov/','https://www.ustaxcourt.gov/ustcinop/OpinionSearch.aspx','https://www.ustaxcourt.gov/dawson.html','https://dawson.ustaxcourt.gov/','https://www.uscfc.uscourts.gov/court-information','https://www.uscfc.uscourts.gov/case-information','https://www.cit.uscourts.gov/case-information','https://www.cit.uscourts.gov/court-information','https://www.cit.uscourts.gov/content/judicial-opinions',
'https://www.uscourts.gov/court-locator','https://www.uscourts.gov/federal-court-finder/search','https://www.uscourts.gov/about-federal-courts/court-role-and-structure','https://www.uscourts.gov/about-federal-courts/types-cases','https://www.uscourts.gov/services-forms/bankruptcy','https://www.uscourts.gov/services-forms/bankruptcy/bankruptcy-basics','https://www.uscourts.gov/services-forms/bankruptcy/bankruptcy-case-records','https://www.uscourts.gov/statistics-reports','https://www.uscourts.gov/statistics-reports/analysis-reports','https://www.uscourts.gov/statistics-reports/caseload-data-tables',
'https://www.uscourts.gov/statistics-reports/federal-judicial-caseload-statistics','https://www.uscourts.gov/statistics-reports/judicial-business-united-states-courts','https://www.uscourts.gov/statistics-reports/bankruptcy-filings','https://www.uscourts.gov/statistics-reports/caseload-statistics-data-tables','https://www.uscourts.gov/statistics-reports/data-tables','https://www.uscourts.gov/statistics-reports/federal-court-management-statistics','https://www.uscourts.gov/statistics-reports/judicial-facts-and-figures','https://www.uscourts.gov/statistics-reports/court-statistics-project','https://www.uscourts.gov/statistics-reports/annual-report-director','https://www.uscourts.gov/statistics-reports/long-range-plan-information-technology',
'https://www.fjc.gov/','https://www.fjc.gov/history/courts','https://www.fjc.gov/history/judges','https://www.fjc.gov/history/legislation','https://www.fjc.gov/research','https://www.fjc.gov/content/judicial-history','https://www.fjc.gov/content/biographical-directory-article-iii-federal-judges','https://www.fjc.gov/history/judges/search/advanced-search','https://www.fjc.gov/history/courts/court-type/district-courts','https://www.fjc.gov/history/courts/court-type/courts-appeals',
'https://www.courtlistener.com/','https://www.courtlistener.com/opinion/','https://www.courtlistener.com/docket/','https://www.courtlistener.com/person/','https://www.courtlistener.com/recap/','https://www.courtlistener.com/api/','https://www.courtlistener.com/help/api/rest/','https://www.courtlistener.com/help/api/bulk-data/','https://www.courtlistener.com/help/alerts/','https://www.courtlistener.com/help/coverage/',
'https://www.law.cornell.edu/','https://www.law.cornell.edu/supct/','https://www.law.cornell.edu/uscode/text','https://www.law.cornell.edu/cfr/text','https://www.law.cornell.edu/constitution','https://www.law.cornell.edu/rules','https://www.law.cornell.edu/wex','https://www.law.cornell.edu/regulations','https://www.law.cornell.edu/uscode/notes','https://www.law.cornell.edu/supremecourt/text',
'https://law.justia.com/','https://law.justia.com/cases/','https://law.justia.com/cases/federal/','https://law.justia.com/cases/federal/appellate-courts/','https://law.justia.com/cases/federal/district-courts/','https://law.justia.com/codes/','https://law.justia.com/constitution/','https://law.justia.com/regulations/','https://law.justia.com/lawyers/','https://law.justia.com/dockets/',
'https://casetext.com/','https://casetext.com/case','https://casetext.com/statute','https://casetext.com/regulation','https://www.casemine.com/','https://www.casemine.com/search/us','https://www.casemine.com/judgement/us','https://www.leagle.com/','https://www.leagle.com/decisions','https://www.leagle.com/courts',
'https://www.govinfo.gov/','https://www.govinfo.gov/app/collection/USCOURTS','https://www.govinfo.gov/app/collection/USCODE','https://www.govinfo.gov/app/collection/CFR','https://www.govinfo.gov/app/collection/FR','https://www.govinfo.gov/app/collection/PLAW','https://www.govinfo.gov/app/collection/STATUTE','https://www.govinfo.gov/app/collection/CDOC','https://www.govinfo.gov/app/collection/CHRG','https://www.govinfo.gov/app/collection/CREC',
'https://www.justice.gov/','https://www.justice.gov/opa/pr','https://www.justice.gov/usao/find-your-united-states-attorney','https://www.justice.gov/criminal','https://www.justice.gov/civil','https://www.justice.gov/atr','https://www.justice.gov/civil-rights','https://www.justice.gov/enrd','https://www.justice.gov/tax','https://www.justice.gov/archives/jm',
'https://www.justice.gov/pardon','https://www.justice.gov/pardon/clemency-recipients','https://www.justice.gov/eoir','https://www.justice.gov/eoir/precedent-decisions','https://www.justice.gov/eoir/eoir-case-data','https://www.justice.gov/eoir/virtual-law-library','https://www.justice.gov/eoir/foia-library','https://www.justice.gov/osdbu','https://www.justice.gov/oip/foia-library','https://www.justice.gov/oig/reports',
'https://www.uscourts.gov/forms/bankruptcy-forms','https://www.uscourts.gov/forms/individual-debtor','https://www.uscourts.gov/forms/non-individual-debtor','https://www.uscourts.gov/forms/bankruptcy-court-miscellaneous-fee-schedule','https://www.uscourts.gov/court-programs/bankruptcy','https://www.uscourts.gov/court-programs/bankruptcy/bankruptcy-resources','https://www.uscourts.gov/court-programs/bankruptcy/bankruptcy-noticing-center','https://www.uscourts.gov/court-programs/bankruptcy/unclaimed-funds','https://www.uscourts.gov/court-programs/bankruptcy/claims-agents','https://www.uscourts.gov/court-programs/bankruptcy/mega-cases',
'https://www.justice.gov/ust/','https://www.justice.gov/ust/private-trustee-locator','https://www.justice.gov/ust/eo/bapcpa/ccde/cc_approved.htm','https://www.justice.gov/ust/eo/bapcpa/ccde/de_approved.htm','https://www.justice.gov/ust/means-testing','https://www.justice.gov/ust/foia','https://www.justice.gov/ust/data-statistics','https://www.justice.gov/ust/report-suspected-bankruptcy-fraud','https://www.justice.gov/ust/bankruptcy-information','https://www.justice.gov/ust/press-releases',
'https://www.justice.gov/tax/case-summaries','https://www.justice.gov/atr/antitrust-case-filings','https://www.justice.gov/civil/case-and-matter-information','https://www.justice.gov/crt/case-summaries','https://www.justice.gov/enrd/case-documents','https://www.justice.gov/criminal/criminal-fraud/case-information','https://www.justice.gov/criminal/criminal-fraud/related-enforcement-actions','https://www.justice.gov/criminal/criminal-fraud/health-care-fraud-unit','https://www.justice.gov/criminal/criminal-fraud/securities-and-financial-fraud-unit','https://www.justice.gov/criminal/criminal-fraud/foreign-corrupt-practices-act',
'https://www.justice.gov/atr/case-filings','https://www.justice.gov/atr/judgment-termination','https://www.justice.gov/atr/merger-enforcement','https://www.justice.gov/atr/civil-conduct-task-force','https://www.justice.gov/atr/criminal-enforcement','https://www.justice.gov/atr/leniency-program','https://www.justice.gov/atr/competition-policy-and-advocacy-section','https://www.justice.gov/atr/international-program','https://www.justice.gov/atr/foia','https://www.justice.gov/atr/contact-division'
];
const urls=[...new Set(roots)].slice(0,200);
if(urls.length!==200) throw new Error(`Pantheon batch 19 expected 200 distinct URLs, got ${urls.length}`);
const cats=(u:string):string[]=>/bankruptcy|ust\//i.test(u)?['bankruptcy','courts','financial-public','civil-litigation']:/justice\.gov|criminal/i.test(u)?['criminal','civil-litigation','courts','regulatory']:/courtlistener|justia|cornell|casetext|casemine|leagle/i.test(u)?['courts','civil-litigation','criminal','corroboration']:['courts','civil-litigation','criminal','historical'];
export const PANTHEON_VERIFIED_SOURCES_BATCH_19:PantheonVerifiedSource[]=urls.map((url,i)=>({id:`b19-${String(i+1).padStart(3,'0')}`,name:`Court/legal public source ${i+1}`,url,jurisdiction:'US',categories:cats(url),authority:/\.gov|uscourts|supremecourt|fjc/.test(url)?'primary':'secondary',verifiedAt:V}));
