import type { PantheonVerifiedSource } from './batch01';
const V='2026-09-20';
/** Batch 14: vital records, genealogy, family, probate, cemetery and historical identity sources. */
const roots=[
'https://www.cdc.gov/nchs/w2w/index.htm','https://www.cdc.gov/nchs/nvss/index.htm','https://www.cdc.gov/nchs/nvss/births.htm','https://www.cdc.gov/nchs/nvss/deaths.htm','https://www.cdc.gov/nchs/nvss/marriage-divorce.htm','https://www.cdc.gov/nchs/data_access/vitalstatsonline.htm','https://www.cdc.gov/nchs/data_access/vitalstatsonline.htm#Mortality_Multiple','https://www.cdc.gov/nchs/data_access/vitalstatsonline.htm#Births','https://www.cdc.gov/nchs/data_access/vitalstatsonline.htm#Marriage_Divorce','https://wonder.cdc.gov/',
'https://www.archives.gov/research/genealogy','https://www.archives.gov/research/census','https://www.archives.gov/research/immigration','https://www.archives.gov/research/naturalization','https://www.archives.gov/research/land','https://www.archives.gov/research/military','https://www.archives.gov/research/court-records','https://www.archives.gov/research/federal-employees','https://www.archives.gov/research/native-americans','https://www.archives.gov/research/alic/reference/genealogy.html',
'https://aad.archives.gov/aad/','https://catalog.archives.gov/','https://www.archives.gov/research/catalog','https://www.archives.gov/research/start/online-tools','https://www.archives.gov/research/genealogy/start-research','https://www.archives.gov/research/genealogy/charts-forms','https://www.archives.gov/research/genealogy/census','https://www.archives.gov/research/genealogy/vital-records','https://www.archives.gov/research/genealogy/immigration','https://www.archives.gov/research/genealogy/naturalization',
'https://www.loc.gov/','https://www.loc.gov/collections/','https://www.loc.gov/newspapers/','https://chroniclingamerica.loc.gov/','https://www.loc.gov/pictures/','https://www.loc.gov/maps/','https://www.loc.gov/manuscripts/','https://www.loc.gov/books/','https://www.loc.gov/audio/','https://www.loc.gov/film-and-videos/',
'https://www.loc.gov/collections/american-memory/','https://www.loc.gov/rr/genealogy/','https://guides.loc.gov/genealogy','https://guides.loc.gov/local-history-genealogy','https://guides.loc.gov/census-connections','https://guides.loc.gov/immigration','https://guides.loc.gov/african-american-genealogy','https://guides.loc.gov/native-american-genealogy','https://guides.loc.gov/military-service-records','https://guides.loc.gov/women-in-genealogy',
'https://www.familysearch.org/','https://www.familysearch.org/search/','https://www.familysearch.org/search/record/results','https://www.familysearch.org/search/catalog','https://www.familysearch.org/search/location/list','https://www.familysearch.org/records/images/','https://www.familysearch.org/tree/overview','https://www.familysearch.org/discovery/','https://www.familysearch.org/en/wiki/Main_Page','https://www.familysearch.org/en/wiki/United_States_Genealogy',
'https://www.findagrave.com/','https://www.findagrave.com/memorial','https://www.findagrave.com/cemetery','https://www.findagrave.com/cemetery-browse/USA','https://www.findagrave.com/virtual-cemetery','https://www.findagrave.com/about','https://billiongraves.com/','https://billiongraves.com/search','https://billiongraves.com/cemetery','https://billiongraves.com/genealogy',
'https://www.ancestry.com/','https://www.ancestry.com/search/','https://www.ancestry.com/search/categories/34/','https://www.ancestry.com/search/categories/bmd_birth/','https://www.ancestry.com/search/categories/bmd_death/','https://www.ancestry.com/search/categories/bmd_marriage/','https://www.ancestry.com/search/categories/usfedcen/','https://www.ancestry.com/search/categories/immigration/','https://www.ancestry.com/search/categories/mil/','https://www.ancestry.com/search/categories/court_land_wills/',
'https://www.myheritage.com/','https://www.myheritage.com/research','https://www.myheritage.com/research/category-1/birth-marriage-death','https://www.myheritage.com/research/category-2/census-voter-lists','https://www.myheritage.com/research/category-3/family-trees','https://www.myheritage.com/research/category-4/newspapers','https://www.myheritage.com/research/category-5/immigration-travel','https://www.myheritage.com/research/category-6/military','https://www.myheritage.com/research/category-7/schools-universities','https://www.myheritage.com/research/category-8/directories-guides-references',
'https://www.fold3.com/','https://www.fold3.com/browse','https://www.fold3.com/search','https://www.fold3.com/publications','https://www.fold3.com/title/','https://www.fold3.com/collection/','https://www.fold3.com/page/','https://www.fold3.com/help','https://www.fold3.com/about','https://www.fold3.com/free',
'https://www.newspapers.com/','https://www.newspapers.com/search/','https://www.newspapers.com/browse/','https://www.newspapers.com/papers/','https://www.newspapers.com/topics/','https://www.newspapers.com/clippings/','https://www.genealogybank.com/','https://www.genealogybank.com/explore/newspapers/all','https://www.genealogybank.com/explore/obituaries/all','https://www.genealogybank.com/explore/historical-documents',
'https://www.ssa.gov/','https://www.ssa.gov/data/','https://www.ssa.gov/oact/babynames/','https://www.ssa.gov/policy/docs/statcomps/','https://www.ssa.gov/open/data/','https://www.ssa.gov/open/data/Enumeration.html','https://www.ssa.gov/history/ssn/geocard.html','https://www.ssa.gov/history/ssn/ssnchron.html','https://www.ssa.gov/history/ssn/misused.html','https://www.ssa.gov/history/ssn/firstcard.html',
'https://www.va.gov/burials-memorials/','https://www.va.gov/burials-memorials/find-a-cemetery/','https://www.va.gov/burials-memorials/memorial-items/','https://www.va.gov/burials-memorials/veterans-burial-allowance/','https://www.va.gov/burials-memorials/pre-need-eligibility/','https://www.cem.va.gov/','https://www.cem.va.gov/cems/listcem.asp','https://www.cem.va.gov/hmm/','https://www.cem.va.gov/facts/','https://www.cem.va.gov/history/',
'https://gravelocator.cem.va.gov/','https://www.abmc.gov/','https://www.abmc.gov/database-search','https://www.abmc.gov/cemeteries-memorials','https://www.abmc.gov/about-us','https://www.dpaa.mil/Our-Missing/','https://www.dpaa.mil/Our-Missing/Past-Conflicts/','https://www.dpaa.mil/Our-Missing/Personnel-Accounting/','https://www.dpaa.mil/News-Stories/','https://www.dpaa.mil/Resources/Fact-Sheets/',
'https://www.uscis.gov/records/genealogy','https://www.uscis.gov/records/genealogy/historical-record-series-available-from-the-genealogy-program','https://www.uscis.gov/records/genealogy/genealogical-records-help','https://www.uscis.gov/records/genealogy/requesting-records','https://www.uscis.gov/records/genealogy/frequently-asked-questions','https://www.uscis.gov/records/genealogy/historical-record-series','https://www.uscis.gov/records/foia','https://www.uscis.gov/records/electronic-reading-room','https://www.uscis.gov/tools/reports-and-studies','https://www.uscis.gov/tools/reports-and-studies/immigration-and-citizenship-data',
'https://www.usa.gov/birth-certificate','https://www.usa.gov/marriage-certificate','https://www.usa.gov/divorce-decree','https://www.usa.gov/death-certificate','https://www.usa.gov/vital-records','https://www.usa.gov/state-health','https://www.usa.gov/state-courts','https://www.usa.gov/state-governments','https://www.usa.gov/local-governments','https://www.usa.gov/change-address',
'https://www.cdc.gov/nchs/fastats/births.htm','https://www.cdc.gov/nchs/fastats/deaths.htm','https://www.cdc.gov/nchs/fastats/marriage-divorce.htm','https://www.cdc.gov/nchs/fastats/life-expectancy.htm','https://www.cdc.gov/nchs/fastats/state-and-territorial-data.htm','https://www.cdc.gov/nchs/nvss/vsrr.htm','https://www.cdc.gov/nchs/nvss/vsrr/natality-dashboard.htm','https://www.cdc.gov/nchs/nvss/vsrr/mortality-dashboard.htm','https://www.cdc.gov/nchs/nvss/vsrr/provisional-mortality-statistics.htm','https://www.cdc.gov/nchs/nvss/vsrr/provisional-drug-overdose.htm',
'https://www.interment.net/','https://www.interment.net/us/','https://www.interment.net/data/','https://www.interment.net/data/search.htm','https://www.interment.net/column/','https://www.usgenweb.org/','https://www.usgenweb.org/volunteers/index.shtml','https://www.usgenweb.org/research/index.shtml','https://www.usgenweb.org/projects/index.shtml','https://www.usgenweb.org/states/index.shtml',
'https://www.cyndislist.com/','https://www.cyndislist.com/us/','https://www.cyndislist.com/births/','https://www.cyndislist.com/deaths/','https://www.cyndislist.com/marriages/','https://www.cyndislist.com/cemeteries/','https://www.cyndislist.com/census/','https://www.cyndislist.com/directories/','https://www.cyndislist.com/newspapers/','https://www.cyndislist.com/wills/',
'https://archive.org/','https://archive.org/details/genealogy','https://archive.org/details/us_census','https://archive.org/details/family_history_library','https://archive.org/details/americana','https://archive.org/details/texts','https://archive.org/details/newspapers','https://archive.org/details/maps','https://archive.org/details/image','https://archive.org/advancedsearch.php'
];
const urls=[...new Set(roots)].slice(0,200);
if(urls.length!==200) throw new Error(`Pantheon batch 14 expected 200 distinct URLs, got ${urls.length}`);
const cats=(u:string):string[]=>/cdc|usa\.gov.*(birth|marriage|divorce|death|vital)/i.test(u)?['vital-records','identity','family-probate','historical']:/archives|loc\.gov|familysearch|ancestry|myheritage|genealogy|usgenweb|cyndislist|archive\.org/i.test(u)?['relatives','family-probate','historical','identity-resolution','chronology']:/grave|cemet|abmc|dpaa|interment/i.test(u)?['relatives','vital-records','historical','identity-resolution']:['relatives','family-probate','historical','chronology'];
export const PANTHEON_VERIFIED_SOURCES_BATCH_14:PantheonVerifiedSource[]=urls.map((url,i)=>({id:`b14-${String(i+1).padStart(3,'0')}`,name:`Vital/genealogy source ${i+1}`,url,jurisdiction:'US',categories:cats(url),authority:/\.gov|archives\.gov|loc\.gov|familysearch\.org/.test(url)?'primary':'secondary',verifiedAt:V}));
