import type { PantheonVerifiedSource } from './batch01';
const V='2026-09-20';
/** Batch 23 (final): 100 public sources for identity resolution, chronology, corroboration, news and dossier completeness. */
const roots=[
'https://www.usa.gov/','https://www.usa.gov/state-governments','https://www.usa.gov/local-governments','https://www.usa.gov/state-courts','https://www.usa.gov/state-attorney-general','https://www.usa.gov/state-consumer','https://www.usa.gov/state-health','https://www.usa.gov/state-social-services','https://www.usa.gov/state-motor-vehicle-services','https://www.usa.gov/state-election-office',
'https://catalog.data.gov/','https://catalog.data.gov/dataset','https://catalog.data.gov/dataset?tags=people','https://catalog.data.gov/dataset?tags=address','https://catalog.data.gov/dataset?tags=business','https://catalog.data.gov/dataset?tags=court','https://catalog.data.gov/dataset?tags=crime','https://catalog.data.gov/dataset?tags=housing','https://catalog.data.gov/dataset?tags=employment','https://catalog.data.gov/dataset?tags=education',
'https://catalog.archives.gov/','https://aad.archives.gov/aad/','https://catalog.archives.gov/research','https://catalog.archives.gov/research/genealogy','https://catalog.archives.gov/research/census','https://catalog.archives.gov/research/court-records','https://catalog.archives.gov/research/federal-employees','https://catalog.archives.gov/research/immigration','https://catalog.archives.gov/research/military',
'https://catalog.loc.gov/','https://catalog.loc.gov/collections/','https://catalog.loc.gov/newspapers/','https://chroniclingamerica.loc.gov/','https://catalog.loc.gov/pictures/','https://catalog.loc.gov/maps/','https://catalog.loc.gov/manuscripts/','https://catalog.loc.gov/books/','https://catalog.loc.gov/film-and-videos/','https://catalog.loc.gov/audio/',
'https://www.govinfo.gov/app/collection/USCOURTS','https://www.govinfo.gov/app/collection/USCOURTSapp/collection/CREC','https://www.govinfo.gov/app/collection/USCOURTSapp/collection/CDIR','https://www.govinfo.gov/app/collection/USCOURTSapp/collection/CHRG','https://www.govinfo.gov/app/collection/USCOURTSapp/collection/FR','https://www.govinfo.gov/app/collection/USCOURTSapp/collection/USCOURTS','https://www.govinfo.gov/app/collection/USCOURTSapp/collection/USCODE','https://www.govinfo.gov/app/collection/USCOURTSapp/collection/CFR','https://www.govinfo.gov/app/collection/USCOURTSapp/collection/PLAW','https://www.govinfo.gov/app/collection/USCOURTSapp/collection/STATUTE',
'https://www.federalregister.gov/documents/search','https://www.federalregister.gov/documents/searchdocuments/search','https://www.federalregister.gov/documents/searchagencies','https://www.federalregister.gov/documents/searchpublic-inspection/current','https://www.federalregister.gov/documents/searchpresidential-documents','https://www.regulations.gov/search','https://www.regulations.gov/searchsearch','https://www.regulations.gov/searchdocket-browser','https://www.regulations.gov/searchlearn','https://www.regulations.gov/searchfaq',
'https://data.census.gov/','https://api.census.gov/data.html','https://data.census.gov/data.html','https://data.census.gov/geographies.html','https://geocoding.geo.census.gov/geocoder/','https://tigerweb.geo.census.gov/tigerweb/','https://www2.census.gov/geo/tiger/','https://data.census.gov/programs-surveys/acs/','https://data.census.gov/programs-surveys/decennial-census.html',
'https://www.bls.gov/','https://www.bls.gov/data/','https://www.bls.gov/oes/','https://www.bls.gov/ooh/','https://www.bls.gov/emp/','https://www.bls.gov/cps/','https://www.bls.gov/cew/','https://www.bls.gov/lau/','https://www.bls.gov/nls/','https://www.bls.gov/developers/',
'https://www.courtlistener.com/','https://www.courtlistener.com/opinion/','https://www.courtlistener.com/docket/','https://www.courtlistener.com/person/','https://www.courtlistener.com/recap/','https://law.justia.com/','https://law.justia.com/cases/','https://law.justia.com/dockets/','https://www.law.cornell.edu/','https://www.law.cornell.edu/supct/',
'https://archive.org/','https://archive.org/advancedsearch.php','https://web.archive.org/','https://index.commoncrawl.org/','https://commoncrawl.org/','https://dp.la/','https://dp.la/search','https://www.wikidata.org/','https://query.wikidata.org/','https://commons.wikimedia.org/'
];
const urls=[...new Set(roots)];
if(urls.length!==100) throw new Error(`Pantheon batch 23 expected 100 distinct URLs, got ${urls.length}`);
const cats=(u:string):string[]=>/courtlistener|justia|cornell/i.test(u)?['courts','civil-litigation','criminal','corroboration']:/archives|loc\.gov|archive\.org|chronicling|dp\.la/i.test(u)?['historical','chronology','identity-resolution','corroboration']:/census|usa\.gov/i.test(u)?['identity-resolution','geography','residence','corroboration']:['corroboration','completeness','source-audit','final-dossier'];
export const PANTHEON_VERIFIED_SOURCES_BATCH_23:PantheonVerifiedSource[]=urls.map((url,i)=>({id:`b23-${String(i+1).padStart(3,'0')}`,name:`Corroboration/completeness source ${i+1}`,url,jurisdiction:'US/global',categories:cats(url),authority:/\.gov|archives\.gov|loc\.gov|census\.gov|bls\.gov/.test(url)?'primary':'secondary',verifiedAt:V}));
