import type { PantheonVerifiedSource } from './batch01';
const V='2026-09-20';
/** Batch 13: identity, address, postal, telecom, phone-numbering and geographic corroboration sources. */
const roots=[
'https://www.usps.com/','https://tools.usps.com/zip-code-lookup.htm','https://tools.usps.com/go/ZipLookupTool','https://postalpro.usps.com/','https://postalpro.usps.com/address-quality','https://postalpro.usps.com/address-quality-solutions','https://postalpro.usps.com/address-quality/cass','https://postalpro.usps.com/address-quality/ais-viewer','https://postalpro.usps.com/address-quality/zip-4','https://postalpro.usps.com/address-quality/dpv','https://postalpro.usps.com/address-quality/lacslink','https://postalpro.usps.com/address-quality/suitelink','https://postalpro.usps.com/address-quality/ncoalink','https://postalpro.usps.com/mailing-and-shipping-services','https://postalpro.usps.com/operations','https://postalpro.usps.com/data','https://postalpro.usps.com/competitive-product-prices','https://postalpro.usps.com/market-dominant-product-prices',
'https://geocoding.geo.census.gov/geocoder/','https://geocoding.geo.census.gov/geocoder/geographies/address','https://geocoding.geo.census.gov/geocoder/locations/address','https://geocoding.geo.census.gov/geocoder/geographies/onelineaddress','https://geocoding.geo.census.gov/geocoder/locations/onelineaddress','https://www.census.gov/geographies/reference-files/time-series/geo/gazetteer-files.html','https://www.census.gov/geographies/reference-files/time-series/geo/relationship-files.html','https://www.census.gov/geographies/reference-files/time-series/geo/centers-population.html','https://www.census.gov/geographies/reference-files/time-series/geo/geo-ipf.html','https://www.census.gov/geographies/reference-files/time-series/geo/ansi.html',
'https://www.census.gov/geographies/mapping-files/time-series/geo/tiger-line-file.html','https://www2.census.gov/geo/tiger/','https://tigerweb.geo.census.gov/tigerweb/','https://www.census.gov/geographies/mapping-files.html','https://www.census.gov/geographies/reference-maps.html','https://www.census.gov/programs-surveys/acs/geography-acs.html','https://www.census.gov/programs-surveys/decennial-census/about/rdo/summary-files.html','https://www.census.gov/data/developers/data-sets.html','https://api.census.gov/data.html','https://www.census.gov/data.html',
'https://www.fcc.gov/','https://www.fcc.gov/licensing-databases','https://www.fcc.gov/wireless','https://www.fcc.gov/general/universal-licensing-system','https://wireless2.fcc.gov/UlsSearch/searchLicense.jsp','https://wireless2.fcc.gov/UlsSearch/searchAdvanced.jsp','https://www.fcc.gov/ecfs/','https://www.fcc.gov/reports-research','https://www.fcc.gov/reports-research/maps','https://www.fcc.gov/BroadbandData',
'https://broadbandmap.fcc.gov/','https://broadbandmap.fcc.gov/location-summary/fixed','https://broadbandmap.fcc.gov/provider-detail/fixed','https://broadbandmap.fcc.gov/data-download','https://www.fcc.gov/BroadbandData/resources','https://www.fcc.gov/BroadbandData/resources/data-downloads','https://www.fcc.gov/BroadbandData/resources/data','https://www.fcc.gov/BroadbandData/filers','https://www.fcc.gov/BroadbandData/consumers','https://www.fcc.gov/BroadbandData/help-center',
'https://www.nanpa.com/','https://www.nanpa.com/numbering','https://www.nanpa.com/numbering/area-code-maps','https://www.nanpa.com/numbering/area-code-relief-planning','https://nanpa.com/index.php/reports/co-code-reports/cocodes_assign','https://www.nanpa.com/reports','https://www.nanpa.com/reports/npa-reports','https://www.nanpa.com/reports/reports_central_office_codes','https://www.nanpa.com/reports/npa-reportsnxx','https://www.nanpa.com/reports/reports_carrier',
'https://www.nationalnanpa.com/','https://www.nanpa.com/reports/co-code-reports','https://www.nationalnanpa.com/area_codes/','https://www.nationalnanpa.com/area_codes/area_code_maps.html','https://www.nationalnanpa.com/number_resource_info/','https://www.nationalnanpa.com/tools/','https://www.nationalnanpa.com/contact_us/',
'https://www.numberportability.com/','https://www.npac.com/','https://www.npac.com/number-portability','https://www.npac.com/number-portability/how-lnp-works','https://www.npac.com/number-portability/lnp-data','https://www.npac.com/industry-resources','https://www.npac.com/industry-resources/lnp-resources','https://www.npac.com/industry-resources/industry-links','https://www.npac.com/about-us','https://www.npac.com/contact-us',
'https://www.itu.int/en/ITU-T/inr/Pages/default.aspx','https://www.itu.int/en/ITU-T/inr/Pages/numbering.aspx','https://www.itu.int/en/ITU-T/inr/Pages/num.aspx','https://www.itu.int/en/ITU-T/inr/Pages/enum.aspx','https://www.itu.int/en/ITU-T/inr/Pages/iin.aspx','https://www.itu.int/en/ITU-T/inr/Pages/mnc.aspx','https://www.itu.int/en/ITU-T/inr/Pages/isdn.aspx','https://www.itu.int/en/ITU-T/inr/Pages/e164.aspx','https://www.itu.int/en/ITU-T/inr/Pages/roa.aspx',
'https://www.fcc.gov/general/telephone-numbers','https://www.fcc.gov/consumers/guides/telephone-numbers','https://www.fcc.gov/general/numbering-resources','https://www.fcc.gov/general/north-american-numbering-plan','https://www.fcc.gov/general/local-number-portability-lnp','https://www.fcc.gov/general/numbering-resource-utilization-forecast','https://www.fcc.gov/general/toll-free-numbers','https://www.fcc.gov/general/211','https://www.fcc.gov/general/311','https://www.fcc.gov/general/988-suicide-crisis-lifeline',
'https://www.fcc.gov/general/911-and-e911-services','https://www.fcc.gov/general/telecommunications-relay-services-trs','https://www.fcc.gov/general/interconnected-voip','https://www.fcc.gov/general/rural-call-completion','https://www.fcc.gov/general/caller-id-spoofing','https://www.fcc.gov/spoofing','https://www.fcc.gov/robocalls','https://www.fcc.gov/call-authentication','https://www.fcc.gov/stir-shaken','https://www.fcc.gov/rural-digital-opportunity-fund',
'https://www.usac.org/','https://www.usac.org/high-cost/','https://www.usac.org/lifeline/','https://www.usac.org/e-rate/','https://www.usac.org/rural-health-care/','https://www.usac.org/about/','https://www.usac.org/about/tools/','https://www.usac.org/about/open-data/','https://opendata.usac.org/','https://www.usac.org/about/reports-orders/',
'https://www.ntia.gov/','https://www.ntia.gov/data','https://www.ntia.gov/category/broadband','https://www.ntia.gov/program/broadbandusa','https://broadbandusa.ntia.gov/','https://broadbandusa.ntia.gov/resources/data-and-mapping','https://broadbandusa.ntia.gov/resources/federal-resources','https://broadbandusa.ntia.gov/funding-programs','https://www.ntia.gov/federal-register-notices','https://www.ntia.gov/press-release',
'https://www.usa.gov/state-governments','https://www.usa.gov/local-governments','https://www.usa.gov/state-consumer','https://www.usa.gov/state-health','https://www.usa.gov/state-social-services','https://www.usa.gov/state-motor-vehicle-services','https://www.usa.gov/state-election-office','https://www.usa.gov/state-attorney-general','https://www.usa.gov/state-emergency-management','https://www.usa.gov/state-tribal-governments',
'https://www.geonames.org/','https://www.geonames.org/export/','https://www.geonames.org/postal-codes/','https://www.geonames.org/countries/','https://www.geonames.org/statistics/','https://www.geonames.org/maps/google_41.878_-87.630.html','https://download.geonames.org/export/dump/','https://download.geonames.org/export/zip/','https://www.geonames.org/export/web-services.html','https://www.geonames.org/about.html',
'https://www.openstreetmap.org/','https://www.openstreetmap.org/search','https://nominatim.openstreetmap.org/','https://nominatim.org/','https://wiki.openstreetmap.org/wiki/Nominatim','https://wiki.openstreetmap.org/wiki/Addresses','https://wiki.openstreetmap.org/wiki/Key:addr','https://wiki.openstreetmap.org/wiki/United_States','https://download.geofabrik.de/north-america/us.html','https://planet.openstreetmap.org/',
'https://www.usgs.gov/programs/national-geospatial-program','https://apps.nationalmap.gov/viewer/','https://apps.nationalmap.gov/downloader/','https://www.usgs.gov/the-national-map-data-delivery','https://www.usgs.gov/tools/national-map-viewer','https://www.usgs.gov/programs/national-geospatial-program/us-topo-maps-america','https://www.usgs.gov/programs/national-geospatial-program/historical-topographic-maps-preserving-past','https://www.usgs.gov/programs/national-geospatial-program/national-map','https://www.usgs.gov/programs/national-geospatial-program/national-map-corps','https://www.usgs.gov/programs/national-geospatial-program/3d-elevation-program',
'https://www2.census.gov/geo/docs/maps-data/data/gazetteer/','https://www2.census.gov/geo/docs/maps-data/data/rel/','https://www2.census.gov/geo/tiger/TIGER2025/','https://www2.census.gov/geo/tiger/TIGER2024/','https://www2.census.gov/geo/tiger/TIGER2023/','https://www2.census.gov/geo/tiger/TIGER2022/','https://www2.census.gov/geo/tiger/TIGER2021/','https://www2.census.gov/geo/tiger/TIGER2020/','https://www2.census.gov/geo/tiger/TIGER2019/','https://www2.census.gov/geo/tiger/TIGER2018/',
'https://www.fcc.gov/data','https://www.fcc.gov/reports-research/guides','https://www.fcc.gov/general/numbering-resources-0','https://www.fcc.gov/general/numbering','https://www.fcc.gov/general/telephone-numbering','https://www.ntia.gov/page/spectrum-management','https://www.ntia.gov/page/spectrum-reports','https://www.ntia.gov/category/spectrum-management','https://www.ntia.gov/category/data','https://www.ntia.gov/issues/broadband','https://www.ntia.gov/issues/spectrum-management','https://www.spectrum.gov/','https://www.census.gov/geographies/mapping-files/time-series/geo/cartographic-boundary.html','https://www.census.gov/geographies/mapping-files/time-series/geo/kml-cartographic-boundary-files.html','https://www.usgs.gov/programs/national-geospatial-program/topographic-maps','https://www.usgs.gov/programs/national-geospatial-program/geospatial-products-and-services'
];
const urls=[...new Set(roots)].slice(0,200);
if(urls.length!==200) throw new Error(`Pantheon batch 13 expected 200 distinct URLs, got ${urls.length}`);
const cats=(u:string):string[]=>/usps|census|geonames|openstreetmap|usgs/i.test(u)?['residence','geography','identity-resolution']:/fcc|nanpa|npac|itu|usac|ntia/i.test(u)?['contacts','identity-resolution','corroboration']:['residence','geography','corroboration'];
export const PANTHEON_VERIFIED_SOURCES_BATCH_13:PantheonVerifiedSource[]=urls.map((url,i)=>({id:`b13-${String(i+1).padStart(3,'0')}`,name:`Address/telecom corroboration source ${i+1}`,url,jurisdiction:'US',categories:cats(url),authority:/geonames|openstreetmap/.test(url)?'secondary':'primary',verifiedAt:V}));
