import type { PantheonVerifiedSource } from './batch01';
const V='2026-09-20';
/**
 * Batch 04: state business/corporate/UCC/open-data authority endpoints.
 * Direct public authority roots are preferred; paid/login-required functions remain
 * source metadata only and are not bypassed by this registry.
 */
const business=[
'https://www.sos.alabama.gov/government-records/business-entity-records','https://www.commerce.alaska.gov/cbp/main/search/entities','https://ecorp.azcc.gov/EntitySearch/Index','https://www.sos.arkansas.gov/corps/search_all.php','https://bizfileonline.sos.ca.gov/search/business','https://www.sos.state.co.us/biz/BusinessEntityCriteriaExt.do','https://business.ct.gov/Home/Business-Search','https://icis.corp.delaware.gov/Ecorp/EntitySearch/NameSearch.aspx','https://search.sunbiz.org/Inquiry/CorporationSearch/ByName','https://ecorp.sos.ga.gov/BusinessSearch','https://hbe.ehawaii.gov/documents/search.html','https://sosbiz.idaho.gov/search/business','https://apps.ilsos.gov/corporatellc/','https://bsd.sos.in.gov/publicbusinesssearch','https://sos.iowa.gov/search/business/search.aspx','https://www.sos.ks.gov/eforms/BusinessEntity/Search.aspx','https://web.sos.ky.gov/ftsearch/','https://coraweb.sos.la.gov/CommercialSearch/CommercialSearch.aspx','https://apps3.web.maine.gov/nei-sos-icrs/ICRS?MainPage=x','https://egov.maryland.gov/BusinessExpress/EntitySearch','https://corp.sec.state.ma.us/corpweb/CorpSearch/CorpSearch.aspx','https://cofs.lara.state.mi.us/SearchApi/Search/Search','https://mblsportal.sos.state.mn.us/Business/Search','https://corp.sos.ms.gov/corp/portal/c/page/corpBusinessIdSearch/portal.aspx','https://bsd.sos.mo.gov/BusinessEntity/BESearch.aspx','https://biz.sosmt.gov/search/business','https://www.nebraska.gov/sos/corp/corpsearch.cgi','https://esos.nv.gov/EntitySearch/OnlineEntitySearch','https://quickstart.sos.nh.gov/online/BusinessInquire','https://www.njportal.com/DOR/BusinessNameSearch/Search/BusinessName','https://enterprise.sos.nm.gov/search/business','https://apps.dos.ny.gov/publicInquiry/','https://www.sosnc.gov/online_services/search/by_title/_Business_Registration','https://firststop.sos.nd.gov/search/business','https://businesssearch.ohiosos.gov/','https://www.sos.ok.gov/corp/corpInquiryFind.aspx','https://egov.sos.state.or.us/br/pkg_web_name_srch_inq.login','https://file.dos.pa.gov/search/business','https://business.sos.ri.gov/CorpWeb/CorpSearch/CorpSearch.aspx','https://businessfilings.sc.gov/BusinessFiling/Entity/Search','https://sosenterprise.sd.gov/BusinessServices/Business/FilingSearch.aspx','https://tnbear.tn.gov/Ecommerce/FilingSearch.aspx','https://mycpa.cpa.state.tx.us/coa/','https://secure.utah.gov/bes/','https://bizfilings.vermont.gov/online/BusinessInquire/','https://cis.scc.virginia.gov/EntitySearch/Index','https://ccfs.sos.wa.gov/','https://apps.wv.gov/SOS/BusinessEntitySearch/','https://www.wdfi.org/apps/CorpSearch/Search.aspx','https://wyobiz.wyo.gov/Business/FilingSearch.aspx'
];
const ucc=[
'https://www.sos.alabama.gov/business-entities/ucc','https://www.commerce.alaska.gov/web/cbpl/Corporations/UCC','https://azsos.gov/business/ucc','https://www.sos.arkansas.gov/business-commercial-services-bcs/uniform-commercial-code-ucc','https://bizfileonline.sos.ca.gov/','https://www.sos.state.co.us/pubs/ucc/uccHome.html','https://business.ct.gov/knowledge-base/articles/business-records-search/ucc-liens','https://corp.delaware.gov/ucc/','https://dos.fl.gov/sunbiz/other-services/ucc-information/','https://sos.ga.gov/page/uniform-commercial-code','https://cca.hawaii.gov/breg/ucc/','https://sos.idaho.gov/ucc/','https://www.ilsos.gov/departments/business_services/ucc/home.html','https://www.in.gov/sos/business/division-forms/uniform-commercial-code/','https://sos.iowa.gov/business/ucc/','https://sos.ks.gov/business/ucc.html','https://www.sos.ky.gov/bus/UCC/Pages/default.aspx','https://www.sos.la.gov/BusinessServices/UniformCommercialCode/Pages/default.aspx','https://www.maine.gov/sos/cec/corp/ucc/','https://egov.maryland.gov/SDAT/UCCFiling/','https://www.sec.state.ma.us/divisions/corporations/filing-by-subject/ucc.htm','https://www.michigan.gov/lara/bureau-list/cscl/ucc','https://www.sos.state.mn.us/business-liens/ucc-tax-cns-forms-fees/','https://www.sos.ms.gov/business-services-regulation/uniform-commercial-code','https://www.sos.mo.gov/ucc','https://sosmt.gov/ucc/','https://sos.nebraska.gov/business-services/uniform-commercial-code','https://www.nvsos.gov/sos/commercial-recordings/ucc','https://sos.nh.gov/corporation-ucc-securities/ucc/','https://www.nj.gov/treasury/revenue/ucc.shtml','https://www.sos.nm.gov/business-services/ucc/','https://dos.ny.gov/uniform-commercial-code','https://www.sosnc.gov/online_services/search/by_title/search_uniform_commercial_code','https://sos.nd.gov/business/business-services/uniform-commercial-code','https://www.ohiosos.gov/ucc/','https://www.sos.ok.gov/ucc/','https://sos.oregon.gov/business/Pages/ucc.aspx','https://www.pa.gov/agencies/dos/programs/business/types-of-filings-and-registrations/uniform-commercial-code.html','https://www.sos.ri.gov/divisions/business-services/ucc','https://sos.sc.gov/online-filings/uniform-commercial-code/ucc-file-and-search-online','https://sdsos.gov/business-services/uniform-commercial-code/','https://sos.tn.gov/businesses/guides/uniform-commercial-code','https://www.sos.state.tx.us/ucc/','https://corporations.utah.gov/ucc/','https://sos.vermont.gov/corporations/ucc-lien-services/','https://www.scc.virginia.gov/pages/UCC','https://dol.wa.gov/professional-licenses/uniform-commercial-code-ucc','https://sos.wv.gov/business/ucc/Pages/default.aspx','https://dfi.wi.gov/Pages/UCC.aspx','https://sos.wyo.gov/Business/UCC.aspx'
];
const stateOpen=[
'https://data.alabama.gov/','https://data-soa-alaska.opendata.arcgis.com/','https://data.az.gov/','https://data.arkansas.gov/','https://data.ca.gov/','https://data.colorado.gov/','https://data.ct.gov/','https://data.delaware.gov/','https://data.florida.gov/','https://data.georgia.gov/','https://data.hawaii.gov/','https://data.idaho.gov/','https://data.illinois.gov/','https://hub.mph.in.gov/','https://data.iowa.gov/','https://data.kansas.gov/','https://data.ky.gov/','https://data.louisiana.gov/','https://data.maine.gov/','https://opendata.maryland.gov/','https://data.mass.gov/','https://data.michigan.gov/','https://mn.gov/admin/data/','https://www.ms.gov/data','https://data.mo.gov/','https://data.mt.gov/','https://data.nebraska.gov/','https://data.nv.gov/','https://www.nh.gov/data/','https://data.nj.gov/','https://data.nm.gov/','https://data.ny.gov/','https://data.nc.gov/','https://www.nd.gov/data','https://data.ohio.gov/','https://data.ok.gov/','https://data.oregon.gov/','https://data.pa.gov/','https://data.ri.gov/','https://data.sc.gov/','https://opendata.sd.gov/','https://www.tn.gov/finance/rd-doa/open-data.html','https://data.texas.gov/','https://opendata.utah.gov/','https://data.vermont.gov/','https://data.virginia.gov/','https://data.wa.gov/','https://data.wv.gov/','https://data.wi.gov/','https://data.wyo.gov/'
];
const federal=[
'https://data.gov/','https://catalog.data.gov/dataset','https://www.census.gov/data.html','https://data.census.gov/','https://api.census.gov/data.html','https://www.bls.gov/data/','https://download.bls.gov/pub/time.series/','https://www.bea.gov/data','https://apps.bea.gov/iTable/','https://www.usa.gov/state-local-governments','https://www.usa.gov/state-consumer','https://www.usa.gov/state-election-office','https://www.usa.gov/state-attorney-general','https://www.usa.gov/state-corrections','https://www.usa.gov/state-health','https://www.usa.gov/state-motor-vehicle-services','https://www.usa.gov/state-social-services','https://www.usa.gov/state-emergency-management','https://www.usa.gov/state-governments','https://www.usa.gov/local-governments','https://www.archives.gov/research','https://catalog.archives.gov/','https://www.loc.gov/collections/','https://www.loc.gov/newspapers/','https://www.loc.gov/maps/','https://www.loc.gov/photos/','https://www.loc.gov/manuscripts/','https://www.loc.gov/books/','https://www.loc.gov/web-archives/','https://www.loc.gov/programs/national-recording-preservation-board/','https://www.govinfo.gov/app/collection/FR','https://www.govinfo.gov/app/collection/CFR','https://www.govinfo.gov/app/collection/BILLS','https://www.govinfo.gov/app/collection/PLAW','https://www.govinfo.gov/app/collection/STATUTE','https://www.govinfo.gov/app/collection/CREC','https://www.govinfo.gov/app/collection/USCODE','https://www.govinfo.gov/app/collection/USCOURTS','https://www.congress.gov/','https://www.congress.gov/members','https://www.congress.gov/committee-reports','https://www.congress.gov/congressional-record','https://www.congress.gov/committee-meetings','https://www.congress.gov/committees','https://www.congress.gov/nominations','https://www.congress.gov/treaties','https://www.congress.gov/legislation','https://www.congress.gov/help/field-values/member-bioguide-ids','https://bioguide.congress.gov/','https://www.gao.gov/reports-testimonies'
];
const urls=[...new Set([...business,...ucc,...stateOpen,...federal])];
if(urls.length!==200) throw new Error(`Pantheon batch 04 expected 200 distinct URLs, got ${urls.length}`);
const categories=(i:number)=>i<50?['business','corporate','organizations','professional-web']:i<100?['financial-public','business','corporate']:i<150?['identity','residence','employment','business','government-employment','property']:['identity','historical','government-employment','organizations','publications'];
export const PANTHEON_VERIFIED_SOURCES_BATCH_04:PantheonVerifiedSource[]=urls.map((url,i)=>({id:`b04-${String(i+1).padStart(3,'0')}`,name:`State/federal public records authority ${i+1}`,url,jurisdiction:'US',categories:categories(i),authority:'primary',verifiedAt:V}));
