import type { PantheonVerifiedSource } from './batch01';
const V='2026-09-20';
/** Batch 22: sanctions, regulatory, enforcement, government oversight, contracting and public-integrity sources. */
const roots=[
'https://ofac.treasury.gov/','https://ofac.treasury.gov/sanctions-list-service','https://sanctionssearch.ofac.treas.gov/','https://ofac.treasury.gov/sanctions-programs-and-country-information','https://ofac.treasury.gov/recent-actions','https://ofac.treasury.gov/specially-designated-nationals-list-data-formats-data-schemas','https://ofac.treasury.gov/consolidated-sanctions-list-non-sdn-lists','https://ofac.treasury.gov/faqs','https://ofac.treasury.gov/civil-penalties-and-enforcement-information','https://ofac.treasury.gov/contact-ofac',
'https://www.bis.gov/','https://www.bis.gov/regulations/export-administration-regulations-ear','https://www.bis.gov/licensing/end-user-guidance','https://www.bis.gov/licensing/consolidated-screening-list','https://www.bis.gov/enforcement','https://www.bis.gov/enforcement/denied-persons-list','https://www.bis.gov/enforcement/entity-list','https://www.bis.gov/enforcement/unverified-list','https://www.bis.gov/enforcement/military-end-user-list','https://www.bis.gov/press-release',
'https://www.trade.gov/','https://www.trade.gov/data-visualization/csl-search','https://www.trade.gov/data-visualization/csl-download','https://www.trade.gov/data-visualization/csl-api','https://www.trade.gov/consolidated-screening-list','https://www.trade.gov/trade-data-analysis','https://www.trade.gov/export-solutions','https://www.trade.gov/foreign-trade-remedies','https://www.trade.gov/trade-enforcement','https://www.trade.gov/press-releases',
'https://www.state.gov/','https://www.state.gov/terrorist-exclusion-list/','https://www.state.gov/foreign-terrorist-organizations/','https://www.state.gov/executive-orders/','https://www.state.gov/sanctions/','https://www.state.gov/reports/','https://www.state.gov/remarks-and-releases/','https://www.state.gov/press-releases/','https://www.state.gov/foia/','https://foia.state.gov/',
'https://www.sec.gov/enforcement-litigation','https://www.sec.gov/enforcement-litigation/litigation-releases','https://www.sec.gov/enforcement-litigation/administrative-proceedings','https://www.sec.gov/enforcement-litigation/accounting-auditing-enforcement-releases','https://www.sec.gov/enforcement-litigation/trading-suspensions','https://www.sec.gov/enforcement-litigation/stop-orders','https://www.sec.gov/enforcement-litigation/opinions-adjudicatory-orders','https://www.sec.gov/enforcement-litigation/whistleblower-program','https://www.sec.gov/enforcement-litigation/enforcement-manual','https://www.sec.gov/newsroom/press-releases',
'https://www.cftc.gov/LawRegulation/EnforcementActions/index.htm','https://www.cftc.gov/PressRoom/PressReleases/index.htm','https://www.cftc.gov/LawRegulation/CFTCEnforcement/index.htm','https://www.cftc.gov/IndustryOversight/index.htm','https://www.cftc.gov/MarketReports/index.htm','https://www.cftc.gov/LawRegulation/index.htm','https://www.cftc.gov/ConsumerProtection/index.htm','https://www.cftc.gov/check','https://www.cftc.gov/FOI/index.htm','https://www.cftc.gov/About/index.htm',
'https://www.ftc.gov/legal-library/browse/cases-proceedings','https://www.ftc.gov/news-events/news/press-releases','https://www.ftc.gov/legal-library/browse/enforcement-type/commission-decision-volumes','https://www.ftc.gov/legal-library/browse/enforcement-type/federal-court-cases','https://www.ftc.gov/legal-library/browse/enforcement-type/administrative-cases','https://www.ftc.gov/legal-library/browse/rules','https://www.ftc.gov/policy/advocacy-research','https://www.ftc.gov/foia','https://www.ftc.gov/about-ftc/bureaus-offices','https://reportfraud.ftc.gov/',
'https://www.consumerfinance.gov/enforcement/actions/','https://www.consumerfinance.gov/rules-policy/enforcement/','https://www.consumerfinance.gov/about-us/newsroom/','https://www.consumerfinance.gov/data-research/consumer-complaints/search/consumer-complaints/','https://www.consumerfinance.gov/data-research/consumer-complaints/search/','https://www.consumerfinance.gov/compliance/supervisory-guidance/','https://www.consumerfinance.gov/rules-policy/final-rules/','https://www.consumerfinance.gov/rules-policy/notices-opportunities-comment/','https://www.consumerfinance.gov/foia-requests/','https://www.consumerfinance.gov/data-research/consumer-complaints/',
'https://www.justice.gov/atr/antitrust-case-filings','https://www.justice.gov/atr/case-filings','https://www.justice.gov/atr/criminal-enforcement','https://www.justice.gov/atr/merger-enforcement','https://www.justice.gov/atr/judgment-termination','https://www.justice.gov/crt/case-summaries','https://www.justice.gov/civil/case-and-matter-information','https://www.justice.gov/enrd/case-documents','https://www.justice.gov/tax/case-summaries','https://www.justice.gov/opa/pr',
'https://www.epa.gov/enforcement','https://www.epa.gov/enforcement/enforcement-data-and-results','https://echo.epa.gov/','https://echo.epa.gov/facilities/facility-search','https://www.epa.gov/compliance','https://www.epa.gov/enforcement/enforcement-basic-information','https://www.epa.gov/enforcement/civil-cases-and-settlements','https://www.epa.gov/enforcement/criminal-enforcement','https://www.epa.gov/enforcement/federal-facilities-enforcement','https://www.epa.gov/enforcement/news-and-announcements',
'https://www.fda.gov/inspections-compliance-enforcement-and-criminal-investigations','https://www.fda.gov/inspections-compliance-enforcement-and-criminal-investigations/compliance-actions-and-activities','https://www.fda.gov/inspections-compliance-enforcement-and-criminal-investigations/warning-letters','https://www.fda.gov/safety/recalls-market-withdrawals-safety-alerts','https://www.fda.gov/inspections-compliance-enforcement-and-criminal-investigations/criminal-investigations','https://www.fda.gov/inspections-compliance-enforcement-and-criminal-investigations/enforcement-actions','https://www.fda.gov/about-fda/office-regulatory-affairs','https://www.fda.gov/about-fda/fda-organization','https://www.fda.gov/news-events/press-announcements','https://open.fda.gov/',
'https://www.osha.gov/ords/imis/establishment.html','https://www.osha.gov/ords/imis/inspectionNr.html','https://www.osha.gov/ords/imis/accidentsearch.html','https://www.osha.gov/ords/imis/citation.html','https://www.osha.gov/ords/imis/industryprofile.html','https://www.osha.gov/news/newsreleases','https://www.osha.gov/laws-regs','https://www.osha.gov/data','https://www.osha.gov/foia',
'https://www.dol.gov/agencies/whd/data','https://enforcedata.dol.gov/','https://www.dol.gov/agencies/whd/news','https://www.dol.gov/agencies/whd/compliance-assistance','https://www.dol.gov/agencies/olms/public-disclosure-room','https://www.dol.gov/agencies/ebsa/about-ebsa/our-activities/enforcement','https://www.dol.gov/agencies/ebsa/about-ebsa/our-activities/public-disclosure','https://www.dol.gov/agencies/ofccp/foia/library','https://www.dol.gov/agencies/oig/audit-reports','https://www.dol.gov/newsroom/releases',
'https://www.nlrb.gov/search/case','https://www.nlrb.gov/cases-decisions/decisions','https://www.nlrb.gov/cases-decisions/weekly-summaries-decisions','https://www.nlrb.gov/news-publications/news-room','https://www.nlrb.gov/guidance/key-reference-materials','https://www.nlrb.gov/reports','https://www.nlrb.gov/foia','https://www.nlrb.gov/about-nlrb/who-we-are/regional-offices','https://www.nlrb.gov/cases-decisions/filing','https://www.nlrb.gov/cases-decisions',
'https://www.eeoc.gov/litigation','https://www.eeoc.gov/federal-sector/appellate-decisions','https://www.eeoc.gov/newsroom','https://www.eeoc.gov/statistics','https://www.eeoc.gov/data','https://www.eeoc.gov/foia','https://www.eeoc.gov/laws/guidance','https://www.eeoc.gov/initiatives/e-race','https://www.eeoc.gov/employers','https://www.eeoc.gov/field-office',
'https://www.gao.gov/','https://www.gao.gov/reports-testimonies','https://www.gao.gov/legal/bid-protests','https://www.gao.gov/legal/appropriations-law','https://www.gao.gov/legal/other-legal-work','https://www.gao.gov/fraudnet','https://www.gao.gov/about/what-gao-does','https://www.gao.gov/about/press-center','https://www.gao.gov/open-government','https://www.gao.gov/foia',
'https://www.oversight.gov/','https://www.oversight.gov/reports','https://www.oversight.gov/investigations','https://www.oversight.gov/inspectors-general','https://www.oversight.gov/whistleblowers','https://www.oversight.gov/recommendations','https://www.oversight.gov/fraud-waste-abuse','https://www.oversight.gov/about','https://www.oversight.gov/news','https://www.oversight.gov/search',
'https://sam.gov/content/exclusions','https://sam.gov/content/entity-information','https://sam.gov/content/opportunities','https://sam.gov/content/contract-data','https://sam.gov/content/assistance-listings','https://sam.gov/content/wage-determinations','https://sam.gov/content/federal-hierarchy','https://sam.gov/content/help','https://sam.gov/content/status-tracker','https://sam.gov/content/home',
'https://www.usaspending.gov/','https://www.usaspending.gov/search','https://www.usaspending.gov/recipient','https://www.usaspending.gov/agency','https://www.usaspending.gov/federal_account','https://www.usaspending.gov/download_center/custom_award_data','https://www.usaspending.gov/download_center/award_data_archive','https://www.usaspending.gov/explorer','https://www.usaspending.gov/data-sources','https://www.usaspending.gov/data-dictionary',
'https://www.sba.gov/federal-contracting','https://www.sba.gov/federal-contracting/contracting-assistance-programs','https://www.sba.gov/federal-contracting/contracting-guide','https://www.sba.gov/federal-contracting/counseling-help','https://www.sba.gov/federal-contracting/contracting-officials','https://www.sba.gov/federal-contracting/contracting-guide/size-standards','https://www.sba.gov/federal-contracting/contracting-guide/basic-requirements','https://www.sba.gov/federal-contracting/contracting-guide/how-win-contracts','https://www.sba.gov/federal-contracting/contracting-guide/prime-subcontracting','https://www.sba.gov/federal-contracting/contracting-guide/government-contracting-programs','https://www.sba.gov/federal-contracting/contracting-guide/assess-your-business'
];
const urls=[...new Set(roots)].slice(0,200);
if(urls.length!==200) throw new Error(`Pantheon batch 22 expected 200 distinct URLs, got ${urls.length}`);
const cats=(u:string):string[]=>/ofac|bis\.gov|trade\.gov|state\.gov|interpol/i.test(u)?['sanctions','foreign-connections','regulatory','corroboration']:/sam\.gov|usaspending|sba\.gov/i.test(u)?['government-contracting','business','corporate','regulatory']:/gao|oversight|oig/i.test(u)?['government-employment','regulatory','corroboration','adverse-media']:['regulatory','professional-discipline','business','adverse-media'];
export const PANTHEON_VERIFIED_SOURCES_BATCH_22:PantheonVerifiedSource[]=urls.map((url,i)=>({id:`b22-${String(i+1).padStart(3,'0')}`,name:`Regulatory/enforcement source ${i+1}`,url,jurisdiction:'US/global',categories:cats(url),authority:'primary',verifiedAt:V}));
