import type { PantheonVerifiedSource } from './batch01';
const V='2026-09-20';
/** Batch 09: federal professional, licensing, contracting, corporate, labor and regulatory public-data endpoints. */
const roots=[
'https://sam.gov/search/','https://sam.gov/search/content/entity-registration','https://sam.gov/search/content/entity-information','https://sam.gov/search/content/exclusions','https://sam.gov/search/content/opportunities','https://sam.gov/search/content/assistance-listings','https://sam.gov/search/content/wage-determinations','https://sam.gov/search/content/contract-data','https://sam.gov/search/content/hierarchical-federal-data','https://sam.gov/search/content/status-tracker',
'https://www.usaspending.gov/','https://www.usaspending.gov/search','https://www.usaspending.gov/recipient','https://www.usaspending.gov/agency','https://www.usaspending.gov/federal_account','https://www.usaspending.gov/disaster/covid-19','https://www.usaspending.gov/download_center/custom_award_data','https://www.usaspending.gov/download_center/award_data_archive','https://www.usaspending.gov/data-sources','https://www.usaspending.gov/data-dictionary',
'https://www.fpds.gov/','https://www.fpds.gov/fpdsng_cms/index.php/en/','https://www.acquisition.gov/','https://www.acquisition.gov/far','https://www.acquisition.gov/browse/index/far','https://www.acquisition.gov/dfars','https://www.acquisition.gov/gsam','https://www.acquisition.gov/afars','https://www.acquisition.gov/affars','https://www.acquisition.gov/nmcars',
'https://www.sba.gov/','https://www.sba.gov/federal-contracting','https://www.sba.gov/federal-contracting/contracting-assistance-programs','https://www.sba.gov/federal-contracting/contracting-guide','https://www.sba.gov/document/support-directory-federal-government-prime-contractors-subcontracting-plans','https://certify.sba.gov/','https://dsbs.sba.gov/search/dsp_dsbs.cfm','https://www.sba.gov/partners/counselors','https://www.sba.gov/local-assistance','https://www.sba.gov/document/report-small-business-procurement-scorecard-overview',
'https://www.sec.gov/edgar/search/','https://www.sec.gov/edgar/searchedgar/companysearch','https://www.sec.gov/edgar/browse/','https://www.sec.gov/files/company_tickers.json','https://www.sec.gov/Archives/edgar/data/','https://data.sec.gov/','https://www.sec.gov/data-research','https://www.sec.gov/data-research/sec-markets-data','https://www.sec.gov/data-research/sec-markets-data/financial-statement-data-sets','https://www.sec.gov/data-research/sec-markets-data/company-information-about-active-broker-dealers',
'https://adviserinfo.sec.gov/','https://www.investor.gov/introduction-investing/investing-basics/glossary/investment-adviser-public-disclosure-iapd','https://brokercheck.finra.org/','https://www.finra.org/finra-data/browse-catalog','https://www.finra.org/finra-data/browse-catalog/brokercheck','https://www.finra.org/finra-data/browse-catalog/financial-professional-gateway','https://www.finra.org/rules-guidance/oversight-enforcement/disciplinary-actions','https://www.finra.org/rules-guidance/oversight-enforcement/individuals-barred-finra','https://www.finra.org/rules-guidance/oversight-enforcement/firms-expelled-finra','https://www.finra.org/rules-guidance/oversight-enforcement',
'https://www.nfa.futures.org/basicnet/','https://www.nfa.futures.org/registration-membership/index.html','https://www.nfa.futures.org/registration-membership/who-has-to-register/index.html','https://www.nfa.futures.org/registration-membership/member-directory.html','https://www.nfa.futures.org/rulebook/rules.aspx','https://www.cftc.gov/check','https://www.cftc.gov/MarketReports/index.htm','https://www.cftc.gov/MarketReports/CommitmentsofTraders/index.htm','https://www.cftc.gov/MarketReports/BankParticipationReports/index.htm','https://www.cftc.gov/MarketReports/SwapsReports/index.htm',
'https://www.nmlsconsumeraccess.org/','https://mortgage.nationwidelicensingsystem.org/','https://mortgage.nationwidelicensingsystem.org/about/Pages/default.aspx','https://mortgage.nationwidelicensingsystem.org/slr/Pages/default.aspx','https://mortgage.nationwidelicensingsystem.org/profreq/Pages/default.aspx','https://www.fdic.gov/bankfind-suite','https://banks.data.fdic.gov/bankfind-suite/bankfind','https://banks.data.fdic.gov/bankfind-suite/financialreporting','https://banks.data.fdic.gov/bankfind-suite/failed-bank-list','https://banks.data.fdic.gov/bankfind-suite/sod',
'https://occ.treas.gov/topics/charters-and-licensing/financial-institution-lists/index-financial-institution-lists.html','https://occ.treas.gov/topics/charters-and-licensing/financial-institution-lists/national-by-name.pdf','https://occ.treas.gov/topics/charters-and-licensing/financial-institution-lists/federal-savings-associations-by-name.pdf','https://www.ffiec.gov/npw','https://www.ffiec.gov/NPW','https://www.ffiec.gov/ubpr.htm','https://www.ffiec.gov/censusapp.htm','https://www.ffiec.gov/hmda/','https://ffiec.cfpb.gov/data-browser/','https://www.ncua.gov/analysis/credit-union-corporate-call-report-data',
'https://mapping.ncua.gov/','https://ncua.gov/analysis/credit-union-corporate-call-report-data/quarterly-data','https://ncua.gov/regulation-supervision/letters-credit-unions-other-guidance','https://ncua.gov/support-services/credit-union-resources-expansion/credit-union-locator','https://www.federalreserve.gov/data.htm','https://www.federalreserve.gov/releases/h8/current/','https://www.federalreserve.gov/supervisionreg/','https://www.federalreserve.gov/supervisionreg/isb-default.htm','https://www.federalreserve.gov/supervisionreg/large-bank-capital-requirements.htm','https://www.federalreserve.gov/apps/reportingforms/',
'https://npiregistry.cms.hhs.gov/','https://download.cms.gov/nppes/NPI_Files.html','https://data.cms.gov/provider-data/','https://data.cms.gov/provider-characteristics/medicare-provider-supplier-enrollment','https://data.cms.gov/provider-summary-by-type-of-service','https://openpaymentsdata.cms.gov/','https://openpaymentsdata.cms.gov/datasets','https://openpaymentsdata.cms.gov/search','https://data.cms.gov/','https://data.cms.gov/search',
'https://exclusions.oig.hhs.gov/','https://oig.hhs.gov/exclusions/','https://oig.hhs.gov/fraud/enforcement/','https://oig.hhs.gov/fraud/enforcement/criminal/','https://oig.hhs.gov/fraud/enforcement/civil-monetary-penalties/','https://oig.hhs.gov/fraud/enforcement/state-enforcement-actions/','https://oig.hhs.gov/reports-and-publications/','https://oig.hhs.gov/reports-and-publications/workplan/','https://oig.hhs.gov/reports-and-publications/oas/','https://oig.hhs.gov/compliance/',
'https://www.fda.gov/drugs/drug-approvals-and-databases','https://www.accessdata.fda.gov/scripts/cder/daf/','https://www.accessdata.fda.gov/scripts/cder/ob/','https://www.accessdata.fda.gov/scripts/cder/ndc/','https://www.accessdata.fda.gov/scripts/cdrh/cfdocs/cfRL/rl.cfm','https://www.accessdata.fda.gov/scripts/cdrh/cfdocs/cfpmn/pmn.cfm','https://www.accessdata.fda.gov/scripts/cdrh/cfdocs/cfpma/pma.cfm','https://www.accessdata.fda.gov/scripts/ires/','https://www.fda.gov/inspections-compliance-enforcement-and-criminal-investigations','https://www.fda.gov/safety/recalls-market-withdrawals-safety-alerts',
'https://www.dol.gov/agencies/whd/data','https://enforcedata.dol.gov/','https://www.dol.gov/agencies/whd/data/charts','https://www.dol.gov/agencies/whd/data/all-acts','https://www.dol.gov/agencies/olms/public-disclosure-room','https://olmsapps.dol.gov/query/getOrgQry.do','https://olmsapps.dol.gov/query/getFilerProfileQry.do','https://www.dol.gov/agencies/ebsa/about-ebsa/our-activities/public-disclosure','https://www.efast.dol.gov/5500Search/','https://www.dol.gov/agencies/eta/foreign-labor/performance',
'https://www.osha.gov/ords/imis/establishment.html','https://www.osha.gov/ords/imis/accidentsearch.html','https://www.osha.gov/ords/imis/citedstandard.html','https://www.osha.gov/ords/imis/industry.html','https://www.osha.gov/data','https://www.osha.gov/foia','https://www.osha.gov/enforcement','https://www.osha.gov/news/newsreleases',
'https://www.nlrb.gov/search/case','https://www.nlrb.gov/cases-decisions','https://www.nlrb.gov/cases-decisions/decisions','https://www.nlrb.gov/cases-decisions/board-decisions','https://www.nlrb.gov/cases-decisions/administrative-law-judge-decisions','https://www.nlrb.gov/reports/graphs-data','https://www.nlrb.gov/guidance/key-reference-materials','https://www.nlrb.gov/guidance/fillable-forms','https://www.nlrb.gov/about-nlrb/who-we-are/regional-offices','https://www.nlrb.gov/news-outreach',
'https://www.eeoc.gov/data','https://www.eeoc.gov/statistics','https://www.eeoc.gov/litigation','https://www.eeoc.gov/federal-sector/appellate-decisions','https://www.eeoc.gov/federal-sector/decisions','https://www.eeoc.gov/foia','https://www.eeoc.gov/newsroom','https://www.eeoc.gov/youth/filing-complaint','https://www.eeoc.gov/employers/recordkeeping-requirements','https://www.eeoc.gov/initiatives/e-race',
'https://www.epa.gov/enviro','https://enviro.epa.gov/','https://echo.epa.gov/','https://echo.epa.gov/facilities/facility-search','https://echo.epa.gov/trends/comparative-maps-dashboards/state-comparative-maps','https://echo.epa.gov/tools/data-downloads','https://www.epa.gov/ejscreen','https://www.epa.gov/frs','https://www.epa.gov/toxics-release-inventory-tri-program','https://www.epa.gov/ghgreporting',
'https://safer.fmcsa.dot.gov/','https://safer.fmcsa.dot.gov/CompanySnapshot.aspx','https://li-public.fmcsa.dot.gov/LIVIEW/pkg_carrquery.prc_carrlist','https://ai.fmcsa.dot.gov/SMS/','https://www.fmcsa.dot.gov/registration','https://www.fmcsa.dot.gov/safety/company-safety-records','https://data.transportation.gov/','https://www.transportation.gov/data','https://www.faa.gov/licenses_certificates/airmen_certification','https://amsrvs.registry.faa.gov/airmeninquiry/',
'https://registry.faa.gov/aircraftinquiry/','https://www.faa.gov/licenses_certificates/aircraft_certification/aircraft_registry','https://www.faa.gov/data_research','https://www.faa.gov/data_research/accident_incident','https://www.ntsb.gov/safety/data/Pages/Data_Stats.aspx','https://data.ntsb.gov/carol-main-public/','https://www.ntsb.gov/investigations/Pages/aviation.aspx','https://www.ntsb.gov/investigations/Pages/highway.aspx','https://www.ntsb.gov/investigations/Pages/marine.aspx','https://www.ntsb.gov/investigations/Pages/railroad.aspx',
'https://www.osha.gov/data/commonstats'
];
const urls=[...new Set(roots)].slice(0,200);
if(urls.length!==200) throw new Error(`Pantheon batch 09 expected 200 distinct URLs, got ${urls.length}`);
const cats=(u:string):string[]=>/sec|finra|nfa|cftc|fdic|occ|ffiec|ncua|federalreserve|nmls/i.test(u)?['securities','financial-public','professional-discipline','regulatory','business']:/cms|hhs|fda/i.test(u)?['credentials','professional-discipline','regulatory','employment']:/dol|osha|nlrb|eeoc/i.test(u)?['employment','professional-discipline','regulatory']:/sam|usaspending|fpds|acquisition|sba/i.test(u)?['government-contracting','business','corporate']:['regulatory','business','professional-web'];
export const PANTHEON_VERIFIED_SOURCES_BATCH_09:PantheonVerifiedSource[]=urls.map((url,i)=>({id:`b09-${String(i+1).padStart(3,'0')}`,name:`Federal professional/regulatory source ${i+1}`,url,jurisdiction:'US',categories:cats(url),authority:'primary',verifiedAt:V}));
