import type { PantheonVerifiedSource } from './batch01';
const V='2026-09-20';
/** Batch 20: public criminal, corrections, fugitive, warrant, offender and enforcement sources. */
const roots=[
'https://www.bop.gov/inmateloc/','https://www.bop.gov/inmateloc/inmateloc/','https://www.bop.gov/inmateloc/locations/','https://www.bop.gov/inmateloc/about/statistics/','https://www.bop.gov/inmateloc/foia/','https://www.bop.gov/inmateloc/resources/research_and_reports.jsp','https://www.bop.gov/inmateloc/inmates/','https://www.bop.gov/inmateloc/inmates/communications.jsp','https://www.bop.gov/inmateloc/inmates/custody_and_care/','https://www.bop.gov/inmateloc/inmates/fsa/',
'https://www.usmarshals.gov/what-we-do/fugitive-apprehension/profiled-fugitives','https://www.usmarshals.gov/what-we-do/fugitive-investigations','https://www.usmarshals.gov/what-we-do/fugitive-investigations/15-most-wanted-fugitive','https://www.usmarshals.gov/what-we-do/fugitive-investigations/profiled-fugitives','https://www.usmarshals.gov/what-we-do/prisoners','https://www.usmarshals.gov/what-we-do/witness-security','https://www.usmarshals.gov/news','https://www.usmarshals.gov/news/press-releases','https://www.usmarshals.gov/foia','https://www.usmarshals.gov/resources',
'https://www.fbi.gov/wanted','https://www.fbi.gov/wanted/topten','https://www.fbi.gov/wanted/fugitives','https://www.fbi.gov/wanted/counterintelligence','https://www.fbi.gov/wanted/cyber','https://www.fbi.gov/wanted/kidnap','https://www.fbi.gov/wanted/parental-kidnappings','https://www.fbi.gov/wanted/seeking-information','https://www.fbi.gov/wanted/vicap','https://www.fbi.gov/wanted/terrorism',
'https://www.fbi.gov/services/cjis','https://www.fbi.gov/services/cjis/ncic','https://www.fbi.gov/services/cjis/ucr','https://cde.ucr.cjis.gov/','https://cde.ucr.cjis.gov/LATEST/webapp/#/pages/home','https://www.fbi.gov/services/cjis/identity-history-summary-checks','https://www.fbi.gov/services/cjis/fingerprints-and-other-biometrics','https://www.fbi.gov/services/cjis/compact-council','https://www.fbi.gov/services/cjis/nics','https://www.fbi.gov/services/cjis/ndex',
'https://www.dea.gov/','https://www.dea.gov/fugitives','https://www.dea.gov/press-releases','https://www.dea.gov/operations','https://www.dea.gov/foia','https://www.dea.gov/data-and-statistics','https://www.dea.gov/domestic-divisions','https://www.dea.gov/foreign-offices','https://www.dea.gov/law-enforcement','https://www.dea.gov/drug-information',
'https://www.atf.gov/','https://www.atf.gov/most-wanted','https://www.atf.gov/news/press-releases','https://www.atf.gov/resource-center/data-statistics','https://www.atf.gov/resource-center/foia','https://www.atf.gov/firearms','https://www.atf.gov/explosives','https://www.atf.gov/arson','https://www.atf.gov/alcohol-tobacco','https://www.atf.gov/contact/local-atf-offices',
'https://locator.ice.gov/','https://locator.ice.gov/most-wanted','https://locator.ice.gov/statistics','https://locator.ice.gov/foia','https://locator.ice.gov/foia/library','https://locator.ice.gov/detain/detention-management','https://locator.ice.gov/odls/','https://locator.ice.gov/detain/detention-facilities','https://locator.ice.gov/news/releases','https://locator.ice.gov/features',
'https://www.justice.gov/criminal','https://www.justice.gov/criminal/criminal-fraud','https://www.justice.gov/criminal/criminal-fraud/case-information','https://www.justice.gov/criminal/criminal-fraud/related-enforcement-actions','https://www.justice.gov/criminal/criminal-fraud/health-care-fraud-unit','https://www.justice.gov/criminal/criminal-fraud/securities-and-financial-fraud-unit','https://www.justice.gov/criminal/criminal-fraud/foreign-corrupt-practices-act','https://www.justice.gov/criminal/criminal-fraud/market-integrity-and-major-frauds-unit','https://www.justice.gov/criminal/criminal-fraud/money-laundering-and-asset-recovery-section','https://www.justice.gov/criminal/criminal-fraud/public-integrity-section',
'https://www.justice.gov/usao','https://www.justice.gov/usao/find-your-united-states-attorney','https://www.justice.gov/usao/justice-101','https://www.justice.gov/usao/pressreleases','https://www.justice.gov/opa/pr','https://www.justice.gov/opa/media','https://www.justice.gov/opa/press-releases','https://www.justice.gov/archives/opa/pr','https://www.justice.gov/oip/foia-library','https://www.justice.gov/oig/reports',
'https://www.nsopw.gov/','https://www.nsopw.gov/search-public-sex-offender-registries','https://www.nsopw.gov/about-nsopw','https://www.nsopw.gov/safety-and-education','https://www.nsopw.gov/resources','https://smart.ojp.gov/','https://smart.ojp.gov/sorna','https://smart.ojp.gov/sorna/current-law','https://smart.ojp.gov/sorna/implementation-status','https://smart.ojp.gov/news',
'https://bjs.ojp.gov/','https://bjs.ojp.gov/topics/corrections','https://bjs.ojp.gov/topics/courts','https://bjs.ojp.gov/topics/crime','https://bjs.ojp.gov/topics/law-enforcement','https://bjs.ojp.gov/topics/recidivism','https://bjs.ojp.gov/data-analysis','https://bjs.ojp.gov/data-collection','https://bjs.ojp.gov/library','https://bjs.ojp.gov/press-releases',
'https://nij.ojp.gov/','https://nij.ojp.gov/topics/corrections','https://nij.ojp.gov/topics/crimes','https://nij.ojp.gov/topics/law-enforcement','https://nij.ojp.gov/topics/forensics','https://nij.ojp.gov/topics/courts','https://nij.ojp.gov/library','https://nij.ojp.gov/funding','https://nij.ojp.gov/events','https://nij.ojp.gov/media',
'https://www.ojp.gov/','https://www.ojp.gov/feature/crime-and-crime-prevention','https://www.ojp.gov/feature/corrections','https://www.ojp.gov/feature/law-enforcement','https://www.ojp.gov/feature/courts','https://www.ojp.gov/feature/forensic-sciences','https://www.ojp.gov/library','https://www.ojp.gov/funding','https://www.ojp.gov/news','https://www.ojp.gov/programs',
'https://ovc.ojp.gov/','https://ovc.ojp.gov/program/human-trafficking','https://ovc.ojp.gov/topics','https://ovc.ojp.gov/library','https://ovc.ojp.gov/funding','https://ovc.ojp.gov/news','https://ovc.ojp.gov/events','https://ovc.ojp.gov/help-for-victims','https://ovc.ojp.gov/about','https://ovc.ojp.gov/programs',
'https://cops.usdoj.gov/','https://cops.usdoj.gov/resources','https://cops.usdoj.gov/RIC/ric.php','https://cops.usdoj.gov/grants','https://cops.usdoj.gov/pressreleases','https://cops.usdoj.gov/collaborativereform','https://cops.usdoj.gov/lawenforcementmentalhealth','https://cops.usdoj.gov/hiringprogram','https://cops.usdoj.gov/tribalpolicing','https://cops.usdoj.gov/stoptheviolence',
'https://www.interpol.int/How-we-work/Notices/Red-Notices/View-Red-Notices','https://www.interpol.int/How-we-work/Notices','https://www.interpol.int/How-we-work/Notices/Yellow-Notices/View-Yellow-Notices','https://www.interpol.int/How-we-work/Notices/UN-Security-Council-Special-Notices','https://www.interpol.int/How-we-work/Notices/About-Notices','https://www.interpol.int/Crimes','https://www.interpol.int/Crimes/Fugitive-investigative-support','https://www.interpol.int/Crimes/Organized-crime','https://www.interpol.int/Crimes/Financial-crime','https://www.interpol.int/Crimes/Cybercrime',
'https://www.dhs.gov/','https://www.dhs.gov/foia','https://www.dhs.gov/publication/foia-library','https://www.dhs.gov/news','https://www.dhs.gov/news-releases','https://www.dhs.gov/hsi','https://www.dhs.gov/blue-campaign','https://www.dhs.gov/see-something-say-something','https://www.dhs.gov/countering-human-trafficking','https://www.dhs.gov/countering-transnational-organized-crime',
'https://www.secretservice.gov/','https://www.secretservice.gov/investigations','https://www.secretservice.gov/investigations/cyber','https://www.secretservice.gov/investigations/counterfeit','https://www.secretservice.gov/investigations/asset-forfeiture','https://www.secretservice.gov/newsroom/releases','https://www.secretservice.gov/newsroom/press-releases','https://www.secretservice.gov/foia','https://www.secretservice.gov/contact/field-offices','https://www.secretservice.gov/investigations/digitalassets',
'https://www.justice.gov/pardon','https://www.justice.gov/pardon/clemency-recipients','https://www.justice.gov/pardon/pardons-granted-president-joseph-biden-2021-present','https://www.justice.gov/pardon/commutations-granted-president-joseph-biden-2021-present','https://www.justice.gov/pardon/presidential-proclamation-4313','https://www.justice.gov/pardon/frequently-asked-questions','https://www.justice.gov/pardon/office-pardon-attorney','https://www.justice.gov/pardon/contact-office','https://www.justice.gov/pardon/standards-consideration-clemency-petitioners','https://www.justice.gov/pardon/apply-clemency',
'https://www.justice.gov/archives/jm/criminal-resource-manual','https://www.justice.gov/archives/jm/title-9-criminal','https://www.justice.gov/archives/jm/title-9-criminal-9-27000-principles-federal-prosecution','https://www.justice.gov/archives/jm/title-9-criminal-9-28000-principles-federal-prosecution-business-organizations','https://www.justice.gov/archives/jm/title-9-criminal-9-42000-fraud-against-government','https://www.justice.gov/archives/jm/title-9-criminal-9-60000-protection-individual','https://www.justice.gov/archives/jm/title-9-criminal-9-70000-harboring-fugitives','https://www.justice.gov/archives/jm/title-9-criminal-9-80000-judicial-and-other-official-corruption','https://www.justice.gov/archives/jm/title-9-criminal-9-100000-attorney-fee-forfeiture-guidelines','https://www.justice.gov/archives/jm/title-9-criminal-9-110000-organized-crime-and-racketeering'
];
const urls=[...new Set(roots)].slice(0,200);
if(urls.length!==200) throw new Error(`Pantheon batch 20 expected 200 distinct URLs, got ${urls.length}`);
const cats=(u:string):string[]=>/bop|ice\.gov.*detain|correction/i.test(u)?['corrections','criminal','historical']:/wanted|fugitive|marshals|interpol/i.test(u)?['warrants','criminal','arrests','corroboration']:/nsopw|smart\.ojp/i.test(u)?['sex-offender','criminal','corroboration']:['criminal','arrests','courts','adverse-media'];
export const PANTHEON_VERIFIED_SOURCES_BATCH_20:PantheonVerifiedSource[]=urls.map((url,i)=>({id:`b20-${String(i+1).padStart(3,'0')}`,name:`Criminal/corrections public source ${i+1}`,url,jurisdiction:'US/global',categories:cats(url),authority:/\.gov|interpol\.int/.test(url)?'primary':'secondary',verifiedAt:V}));
