import type { PantheonVerifiedSource } from './batch01';
const V='2026-09-20';
/** Batch 16: transportation, vehicle, aviation, maritime, carrier and safety public records. */
const roots=[
'https://www.nhtsa.gov/','https://www.nhtsa.gov/vehicle','https://www.nhtsa.gov/recalls','https://www.nhtsa.gov/ratings','https://www.nhtsa.gov/research-data','https://www.nhtsa.gov/data','https://www.nhtsa.gov/file-downloads','https://www.nhtsa.gov/nhtsa-datasets-and-apis','https://www.nhtsa.gov/vehicle-manufacturers','https://www.nhtsa.gov/importing-vehicle',
'https://vpic.nhtsa.dot.gov/','https://vpic.nhtsa.dot.gov/decoder/','https://vpic.nhtsa.dot.gov/api/','https://vpic.nhtsa.dot.gov/mid/','https://vpic.nhtsa.dot.gov/mid/home/displayfile/','https://vpic.nhtsa.dot.gov/ManufacturerHandbook/','https://vpic.nhtsa.dot.gov/decoder/Decoder','https://vpic.nhtsa.dot.gov/decoder/CheckDigit/','https://vpic.nhtsa.dot.gov/decoder/Manufacturer/','https://vpic.nhtsa.dot.gov/decoder/Plant/',
'https://www.nhtsa.gov/vehicle-safety/vehicle-identification-number-vin','https://www.nhtsa.gov/vehicle-safety/automated-vehicles-safety','https://www.nhtsa.gov/vehicle-safety/seat-belts','https://www.nhtsa.gov/vehicle-safety/takata-recall-spotlight','https://www.nhtsa.gov/vehicle-safety/child-safety','https://www.nhtsa.gov/vehicle-safety/tire-safety','https://www.nhtsa.gov/vehicle-safety/15-passenger-vans','https://www.nhtsa.gov/vehicle-safety/motorcycles','https://www.nhtsa.gov/vehicle-safety/bicycles','https://www.nhtsa.gov/vehicle-safety/pedestrian-safety',
'https://www.nhtsa.gov/research-data/fatality-analysis-reporting-system-fars','https://www.nhtsa.gov/research-data/crash-report-sampling-system','https://www.nhtsa.gov/research-data/crash-investigation-sampling-system','https://www.nhtsa.gov/research-data/state-data-programs','https://www.nhtsa.gov/research-data/special-crash-investigations-sci','https://www.nhtsa.gov/research-data/national-automotive-sampling-system-nass','https://www.nhtsa.gov/research-data/national-driver-register-ndr','https://www.nhtsa.gov/research-data/national-center-statistics-and-analysis-ncsa','https://www.nhtsa.gov/research-data/traffic-safety-facts','https://www.nhtsa.gov/research-data/traffic-records',
'https://www.fmcsa.dot.gov/','https://www.fmcsa.dot.gov/registration','https://www.fmcsa.dot.gov/registration/search-company','https://safer.fmcsa.dot.gov/','https://safer.fmcsa.dot.gov/CompanySnapshot.aspx','https://li-public.fmcsa.dot.gov/LIVIEW/pkg_carrquery.prc_carrlist','https://ai.fmcsa.dot.gov/SMS/','https://ai.fmcsa.dot.gov/SMS/Search/Index.aspx','https://www.fmcsa.dot.gov/safety/company-safety-records','https://www.fmcsa.dot.gov/safety/data-and-statistics',
'https://www.fmcsa.dot.gov/registration/licensing-and-insurance-public','https://li-public.fmcsa.dot.gov/','https://www.fmcsa.dot.gov/registration/get-mc-number-authority-operate','https://www.fmcsa.dot.gov/registration/insurance-filing-requirements','https://www.fmcsa.dot.gov/registration/process-agents','https://www.fmcsa.dot.gov/registration/registration-forms','https://www.fmcsa.dot.gov/registration/registration-alerts','https://www.fmcsa.dot.gov/registration/registration-resources','https://www.fmcsa.dot.gov/registration/registration-statistics','https://www.fmcsa.dot.gov/registration/registration-faqs',
'https://www.faa.gov/','https://www.faa.gov/licenses_certificates/aircraft_certification/aircraft_registry','https://registry.faa.gov/aircraftinquiry/','https://registry.faa.gov/aircraftinquiry/Search/NNumberInquiry','https://registry.faa.gov/aircraftinquiry/Search/SerialNumberInquiry','https://registry.faa.gov/aircraftinquiry/Search/NameInquiry','https://registry.faa.gov/aircraftinquiry/Search/EngineReferenceInquiry','https://registry.faa.gov/aircraftinquiry/Search/DeregisteredAircraftInquiry','https://registry.faa.gov/aircraftinquiry/Search/DealerInquiry','https://registry.faa.gov/aircraftinquiry/Search/DocumentIndexInquiry',
'https://www.faa.gov/licenses_certificates/airmen_certification','https://amsrvs.registry.faa.gov/airmeninquiry/','https://www.faa.gov/licenses_certificates/airmen_certification/airmen_inquiry','https://www.faa.gov/licenses_certificates/airmen_certification/airmen_services','https://www.faa.gov/licenses_certificates/airmen_certification/medical_certification','https://www.faa.gov/data_research','https://www.faa.gov/data_research/accident_incident','https://www.faa.gov/data_research/aviation_data_statistics','https://www.faa.gov/data_research/air_traffic_data','https://www.faa.gov/data_research/commercial_space_data',
'https://www.ntsb.gov/','https://www.ntsb.gov/safety/data/Pages/Data_Stats.aspx','https://data.ntsb.gov/carol-main-public/','https://www.ntsb.gov/investigations/Pages/aviation.aspx','https://www.ntsb.gov/investigations/Pages/highway.aspx','https://www.ntsb.gov/investigations/Pages/marine.aspx','https://www.ntsb.gov/investigations/Pages/railroad.aspx','https://www.ntsb.gov/investigations/Pages/pipeline.aspx','https://www.ntsb.gov/investigations/Pages/investigation-reports.aspx','https://www.ntsb.gov/news/Pages/default.aspx',
'https://www.uscg.mil/','https://www.dco.uscg.mil/nmc/','https://www.dco.uscg.mil/nmc/merchant_mariner_credential/','https://www.dco.uscg.mil/nmc/record_request/','https://www.dco.uscg.mil/nmc/credentialing_process/','https://www.dco.uscg.mil/nmc/examinations/','https://www.dco.uscg.mil/nmc/training_assessments/','https://www.dco.uscg.mil/nmc/checklist/','https://www.dco.uscg.mil/nmc/medical_certificate/','https://www.dco.uscg.mil/nmc/contact/',
'https://www.uscg.mil/Resources/Maritime-Safety/','https://www.dco.uscg.mil/Our-Organization/Assistant-Commandant-for-Prevention-Policy-CG-5P/Inspections-Compliance-CG-5PC-/Office-of-Investigations-Casualty-Analysis/','https://www.dco.uscg.mil/CG-INV/','https://www.dco.uscg.mil/CG-INV/Casualty-Reporting/','https://www.dco.uscg.mil/CG-INV/Statistics/','https://cgmix.uscg.mil/','https://cgmix.uscg.mil/PSIX/PSIXSearch.aspx','https://cgmix.uscg.mil/PSIX/PSIXAdvancedSearch.aspx','https://cgmix.uscg.mil/IIR/IIRSearch.aspx','https://cgmix.uscg.mil/EQ/EquipmentSearch.aspx',
'https://www.maritime.dot.gov/','https://www.maritime.dot.gov/data-reports','https://www.maritime.dot.gov/data-reports/data-statistics','https://www.maritime.dot.gov/ports/port-infrastructure-development-program','https://www.maritime.dot.gov/ships-and-shipping','https://www.maritime.dot.gov/ships-and-shipping/ship-disposal','https://www.maritime.dot.gov/ships-and-shipping/strategic-sealift','https://www.maritime.dot.gov/education/maritime-academies','https://www.maritime.dot.gov/about-us','https://www.maritime.dot.gov/newsroom',
'https://www.stb.gov/','https://www.stb.gov/proceedings-actions/','https://www.stb.gov/proceedings-actions/e-filing/','https://www.stb.gov/proceedings-actions/search-stb-records/','https://www.stb.gov/reports-data/','https://www.stb.gov/reports-data/economic-data/','https://www.stb.gov/reports-data/rail-service-data/','https://www.stb.gov/reports-data/waybill/','https://www.stb.gov/reports-data/railroad-revenue-deflator-factors/','https://www.stb.gov/news-communications/',
'https://railroads.dot.gov/','https://railroads.dot.gov/accident-and-incident-reporting/overview-reports','https://railroads.dot.gov/safety-data','https://railroads.dot.gov/safety-data-and-reporting','https://railroads.dot.gov/safety-data-and-reporting/accident-and-incident-reporting','https://railroads.dot.gov/safety-data-and-reporting/railroad-safety-data-frequently-asked-questions','https://railroads.dot.gov/rail-network-development/freight-rail-overview','https://railroads.dot.gov/rail-network-development/passenger-rail','https://railroads.dot.gov/rail-network-development/high-speed-rail','https://railroads.dot.gov/about-fra',
'https://www.phmsa.dot.gov/','https://www.phmsa.dot.gov/data-and-statistics','https://www.phmsa.dot.gov/data-and-statistics/pipeline/data-and-statistics-overview','https://www.phmsa.dot.gov/data-and-statistics/hazmat/incident-statistics','https://www.phmsa.dot.gov/data-and-statistics/pipeline/pipeline-incident-20-year-trends','https://www.phmsa.dot.gov/data-and-statistics/pipeline/pipeline-mileage-and-facilities','https://www.phmsa.dot.gov/data-and-statistics/pipeline/annual-report-mileage-summary-statistics','https://www.phmsa.dot.gov/data-and-statistics/pipeline/operator-information','https://www.phmsa.dot.gov/data-and-statistics/pipeline/state-pipeline-safety-programs','https://www.phmsa.dot.gov/foia',
'https://www.transit.dot.gov/','https://www.transit.dot.gov/ntd','https://www.transit.dot.gov/ntd/data-product/monthly-module-adjusted-data-release','https://www.transit.dot.gov/ntd/data-product/annual-database-service','https://www.transit.dot.gov/ntd/data-product/annual-database-facility','https://www.transit.dot.gov/ntd/data-product/annual-database-agency-information','https://www.transit.dot.gov/ntd/data-product/annual-database-fuel-and-energy','https://www.transit.dot.gov/ntd/data-product/annual-database-funding-sources','https://www.transit.dot.gov/ntd/data-product/annual-database-safety','https://www.transit.dot.gov/ntd/data-product/annual-database-transit-way-mileage',
'https://www.bts.gov/','https://www.bts.gov/browse-statistical-products-and-data','https://www.bts.gov/topics/airlines-airports-and-aviation','https://www.bts.gov/topics/automobiles','https://www.bts.gov/topics/freight-transportation','https://www.bts.gov/topics/maritime-and-inland-waterways','https://www.bts.gov/topics/passenger-travel','https://www.bts.gov/topics/rail','https://www.bts.gov/topics/safety','https://www.bts.gov/topics/transportation-infrastructure',
'https://data.transportation.gov/','https://www.transportation.gov/data','https://www.transportation.gov/data/transportation-public-data-portal','https://www.transportation.gov/briefing-room','https://www.transportation.gov/individuals/foia','https://www.transportation.gov/mission/open-government','https://www.transportation.gov/mission/budget','https://www.transportation.gov/mission/performance','https://www.transportation.gov/mission/office-secretary','https://www.transportation.gov/mission/administrations',
'https://www.nicb.org/','https://www.nicb.org/vincheck','https://www.nicb.org/news','https://www.nicb.org/prevent-fraud-theft','https://www.nicb.org/how-we-help','https://www.nicb.org/industry-partners','https://www.nicb.org/law-enforcement','https://www.nicb.org/resources','https://www.nicb.org/about-nicb','https://www.nicb.org/contact-us',
'https://www.nhtsa.gov/vehicle/complaints','https://www.nhtsa.gov/vehicle-safety','https://www.nhtsa.gov/vehicle-safety/driver-assistance-technologies','https://www.fmcsa.dot.gov/safety/analysis-research-technology','https://www.fmcsa.dot.gov/safety/data-and-statistics/large-truck-and-bus-crash-facts','https://www.faa.gov/data_research/accident_incident/aviation_data_statistics','https://www.bts.gov/ntad','https://www.bts.gov/geospatial','https://www.transportation.gov/data/enterprise-data-inventory','https://www.transportation.gov/data/transportation-data-strategy'
];
const urls=[...new Set(roots)].slice(0,200);
if(urls.length!==200) throw new Error(`Pantheon batch 16 expected 200 distinct URLs, got ${urls.length}`);
const cats=(u:string):string[]=>/faa|aircraft|airmen|ntsb/i.test(u)?['transportation','credentials','professional-discipline','regulatory']:/fmcsa|safer|nhtsa|vpic|nicb/i.test(u)?['transportation','business','regulatory','corroboration']:/uscg|maritime|cgmix/i.test(u)?['transportation','credentials','professional-discipline']:['transportation','regulatory','business'];
export const PANTHEON_VERIFIED_SOURCES_BATCH_16:PantheonVerifiedSource[]=urls.map((url,i)=>({id:`b16-${String(i+1).padStart(3,'0')}`,name:`Transportation public source ${i+1}`,url,jurisdiction:'US',categories:cats(url),authority:/nicb\.org/.test(url)?'secondary':'primary',verifiedAt:V}));
