import type { PantheonVerifiedSource } from './batch01';
const V='2026-09-20';
/** Batch 06: public web/social/professional/news/archive discovery sources. */
const roots=[
'https://www.linkedin.com/','https://www.facebook.com/','https://www.instagram.com/','https://www.threads.net/','https://x.com/','https://bsky.app/','https://mastodon.social/','https://www.tiktok.com/','https://www.youtube.com/','https://www.reddit.com/','https://www.pinterest.com/','https://www.tumblr.com/','https://www.flickr.com/','https://www.quora.com/','https://medium.com/','https://github.com/','https://gitlab.com/','https://bitbucket.org/','https://stackoverflow.com/users','https://stackexchange.com/users','https://dev.to/','https://hashnode.com/','https://codepen.io/','https://replit.com/','https://www.kaggle.com/','https://orcid.org/orcid-search/search','https://scholar.google.com/','https://www.researchgate.net/','https://www.academia.edu/','https://pubmed.ncbi.nlm.nih.gov/','https://www.ncbi.nlm.nih.gov/pmc/','https://arxiv.org/','https://ssrn.com/','https://zenodo.org/','https://figshare.com/','https://osf.io/','https://search.crossref.org/','https://explore.openalex.org/authors/','https://www.semanticscholar.org/','https://dblp.org/','https://search.worldcat.org/','https://id.loc.gov/','https://viaf.org/','https://isni.org/','https://www.wikidata.org/','https://en.wikipedia.org/','https://commons.wikimedia.org/','https://archive.org/','https://web.archive.org/',
'https://www.google.com/search','https://www.bing.com/search','https://search.brave.com/search','https://duckduckgo.com/','https://www.google.com/images','https://www.google.com/maps','https://www.google.com/news','https://news.google.com/','https://www.bing.com/news','https://www.bing.com/images','https://www.bing.com/maps','https://www.yahoo.com/','https://news.yahoo.com/','https://search.yahoo.com/','https://www.startpage.com/','https://www.mojeek.com/','https://www.ecosia.org/','https://www.qwant.com/','https://www.ask.com/','https://www.dogpile.com/','https://www.wolframalpha.com/','https://www.google.com/books','https://books.google.com/','https://books.google.com/advanced_book_search','https://www.google.com/scholar','https://patents.google.com/','https://datasetsearch.research.google.com/','https://trends.google.com/','https://groups.google.com/','https://sites.google.com/','https://blogger.com/',
'https://www.reuters.com/','https://apnews.com/','https://www.npr.org/','https://www.pbs.org/newshour/','https://www.c-span.org/','https://www.bbc.com/news','https://www.theguardian.com/us','https://www.nytimes.com/','https://www.washingtonpost.com/','https://www.wsj.com/','https://www.usatoday.com/','https://www.latimes.com/','https://www.chicagotribune.com/','https://www.bostonglobe.com/','https://www.inquirer.com/','https://www.dallasnews.com/','https://www.denverpost.com/','https://www.seattletimes.com/','https://www.startribune.com/','https://www.desmoinesregister.com/','https://omaha.com/','https://www.argusleader.com/','https://www.keloland.com/','https://www.kcci.com/','https://www.ketv.com/','https://www.newspapers.com/','https://www.genealogybank.com/','https://chroniclingamerica.loc.gov/','https://www.loc.gov/newspapers/','https://www.loc.gov/collections/chronicling-america/','https://guides.loc.gov/chronicling-america','https://www.loc.gov/rr/news/','https://www.loc.gov/web-archives/','https://archive.org/details/newspapers','https://web.archive.org/web/','https://arquivo.pt/','https://timetravel.mementoweb.org/','https://commoncrawl.org/','https://index.commoncrawl.org/','https://data.commoncrawl.org/','https://www.gdeltproject.org/','https://api.gdeltproject.org/','https://www.mediacloud.org/','https://mediacloud.org/','https://newsapi.org/','https://www.propublica.org/','https://projects.propublica.org/','https://www.icij.org/','https://offshoreleaks.icij.org/','https://www.documentcloud.org/','https://www.muckrock.com/','https://www.govinfo.gov/app/collection/USCOURTS',
'https://www.zoominfo.com/','https://www.crunchbase.com/','https://www.bloomberg.com/','https://www.dnb.com/','https://www.bbb.org/','https://www.glassdoor.com/','https://www.indeed.com/','https://www.ziprecruiter.com/','https://www.monster.com/','https://www.careerbuilder.com/','https://www.simplyhired.com/','https://www.usajobs.gov/','https://www.opm.gov/','https://www.federalpay.org/','https://www.fedsdatacenter.com/','https://www.guidestar.org/','https://www.candid.org/','https://projects.propublica.org/nonprofits/','https://apps.irs.gov/app/eos/','https://projects.propublica.org/represent/','https://www.opensecrets.org/','https://www.followthemoney.org/','https://ballotpedia.org/','https://www.votesmart.org/','https://www.fec.gov/data/','https://lda.senate.gov/system/public/','https://disclosures-clerk.house.gov/','https://efdsearch.senate.gov/','https://bioguide.congress.gov/','https://www.congress.gov/members',
'https://www.avvo.com/','https://www.martindale.com/','https://www.justia.com/lawyers','https://lawyers.findlaw.com/','https://www.lawyers.com/','https://www.nolo.com/lawyers/','https://www.healthgrades.com/','https://www.vitals.com/','https://www.psychologytoday.com/us/therapists','https://www.zocdoc.com/','https://www.doximity.com/','https://npiregistry.cms.hhs.gov/','https://openpaymentsdata.cms.gov/','https://brokercheck.finra.org/','https://adviserinfo.sec.gov/','https://www.nmlsconsumeraccess.org/','https://sam.gov/search/','https://www.usaspending.gov/','https://www.sec.gov/edgar/search/','https://www.uspto.gov/patents/search',
'https://soundcloud.com/','https://bandcamp.com/','https://open.spotify.com/','https://music.apple.com/','https://www.imdb.com/','https://vimeo.com/','https://www.twitch.tv/','https://www.goodreads.com/','https://www.strava.com/','https://www.meetup.com/','https://www.etsy.com/','https://www.ebay.com/','https://www.patreon.com/','https://substack.com/','https://linktr.ee/','https://about.me/','https://gravatar.com/','https://keybase.io/','https://news.ycombinator.com/','https://lobste.rs/'
];
const urls=[...new Set(roots)].slice(0,200);
if(urls.length!==200) throw new Error(`Pantheon batch 06 expected 200 distinct URLs, got ${urls.length}`);
const cats=(u:string):string[]=>{
 if(/linkedin|facebook|instagram|threads|x\.com|bsky|mastodon|tiktok|youtube|reddit|pinterest|tumblr|flickr|quora|soundcloud|bandcamp|spotify|twitch|meetup|strava/i.test(u)) return ['social','usernames','associates','internet'];
 if(/orcid|researchgate|academia|pubmed|arxiv|ssrn|crossref|openalex|scholar/i.test(u)) return ['professional-web','publications','education','credentials','usernames'];
 if(/github|gitlab|bitbucket|stackoverflow|dev\.to|hashnode|codepen|kaggle/i.test(u)) return ['professional-web','publications','employment','usernames','internet'];
 if(/reuters|apnews|npr|pbs|bbc|guardian|nytimes|washingtonpost|wsj|usatoday|tribune|globe|inquirer|news|newspapers|gdelt|mediacloud|propublica|icij|documentcloud/i.test(u)) return ['news','adverse-media','internet','historical'];
 if(/archive|commoncrawl|arquivo|loc\.gov/i.test(u)) return ['internet','historical','publications'];
 if(/zoominfo|crunchbase|bloomberg|dnb|bbb|glassdoor|indeed|usajobs|opm|guidestar|candid|fec|senate|congress|opensecrets/i.test(u)) return ['employment','business','organizations','professional-web'];
 return ['internet','usernames','identity-resolution'];
};
export const PANTHEON_VERIFIED_SOURCES_BATCH_06:PantheonVerifiedSource[]=urls.map((url,i)=>({id:`b06-${String(i+1).padStart(3,'0')}`,name:`Public web/professional/media source ${i+1}`,url,jurisdiction:'global',categories:cats(url),authority:/\.gov\//.test(url)||/loc\.gov|sec\.gov|fec\.gov|congress\.gov|uspto\.gov|cms\.hhs\.gov/.test(url)?'primary':'secondary',verifiedAt:V}));
