import type { PantheonVerifiedSource } from './batch01';
const V='2026-09-20';
/** Batch 15: public image, media, archive, publication and historical-identity sources. */
const roots=[
'https://www.loc.gov/pictures/','https://www.loc.gov/photos/','https://www.loc.gov/collections/','https://www.loc.gov/collections/?fa=original-format:photo,+print,+drawing','https://www.loc.gov/pictures/collection/','https://www.loc.gov/pictures/search/','https://www.loc.gov/pictures/collection/cph/','https://www.loc.gov/pictures/collection/fsa/','https://www.loc.gov/pictures/collection/ggbain/','https://www.loc.gov/pictures/collection/hec/',
'https://catalog.archives.gov/','https://www.archives.gov/research/still-pictures','https://www.archives.gov/research/still-pictures/photographs','https://www.archives.gov/research/catalog','https://www.archives.gov/research/start/online-tools','https://www.archives.gov/research/military/photos','https://www.archives.gov/research/alic/reference/photography.html','https://www.archives.gov/research/alic/reference/photography-digital.html','https://www.archives.gov/research/alic/reference/photography-preservation.html','https://www.archives.gov/research/alic/reference/photography-collections.html',
'https://www.si.edu/openaccess','https://www.si.edu/search/collection-images','https://www.si.edu/collections','https://www.si.edu/object','https://www.si.edu/exhibitions','https://www.si.edu/explore','https://www.si.edu/spotlight','https://www.si.edu/photography','https://www.si.edu/museums','https://www.si.edu/researchcenters',
'https://www.si.edu/openaccess/faq','https://www.si.edu/openaccess/remix','https://www.si.edu/openaccess/updates','https://www.si.edu/openaccess/api','https://api.si.edu/openaccess/api/v1.0/search','https://collections.si.edu/search/','https://collections.si.edu/search/results.htm','https://collections.si.edu/search/detail/','https://collections.si.edu/search/record/','https://collections.si.edu/search/slideshow.htm',
'https://images.nasa.gov/','https://www.nasa.gov/images/','https://www.nasa.gov/gallery/','https://www.nasa.gov/multimedia/','https://www.nasa.gov/nasa-brand-center/images-and-media/','https://science.nasa.gov/resource/','https://earthobservatory.nasa.gov/images','https://visibleearth.nasa.gov/','https://photojournal.jpl.nasa.gov/','https://svs.gsfc.nasa.gov/',
'https://www.dvidshub.net/','https://www.dvidshub.net/search','https://www.dvidshub.net/image','https://www.dvidshub.net/video','https://www.dvidshub.net/news','https://www.dvidshub.net/unit','https://www.dvidshub.net/portfolio','https://www.dvidshub.net/feature','https://www.dvidshub.net/about','https://www.dvidshub.net/help',
'https://commons.wikimedia.org/','https://commons.wikimedia.org/wiki/Main_Page','https://commons.wikimedia.org/wiki/Special:MediaSearch','https://commons.wikimedia.org/wiki/Special:Search','https://commons.wikimedia.org/wiki/Category:People','https://commons.wikimedia.org/wiki/Category:Portraits','https://commons.wikimedia.org/wiki/Category:Photographs','https://commons.wikimedia.org/wiki/Category:Historical_images','https://commons.wikimedia.org/wiki/Commons:Categories','https://commons.wikimedia.org/wiki/Commons:Reusing_content_outside_Wikimedia',
'https://www.flickr.com/commons','https://www.flickr.com/search/','https://www.flickr.com/photos/library_of_congress/','https://www.flickr.com/photos/smithsonian/','https://www.flickr.com/photos/usnationalarchives/','https://www.flickr.com/photos/nasacommons/','https://www.flickr.com/photos/britishlibrary/','https://www.flickr.com/photos/internetarchivebookimages/','https://www.flickr.com/photos/nypl/','https://www.flickr.com/photos/statelibraryofnsw/',
'https://dp.la/','https://dp.la/search','https://dp.la/browse-by-topic','https://dp.la/browse-by-partner','https://dp.la/browse-by-date','https://dp.la/browse-by-location','https://dp.la/browse-by-language','https://dp.la/browse-by-type','https://dp.la/primary-source-sets','https://pro.dp.la/developers',
'https://www.europeana.eu/','https://www.europeana.eu/en/search','https://www.europeana.eu/en/collections','https://www.europeana.eu/en/galleries','https://www.europeana.eu/en/stories','https://www.europeana.eu/en/exhibitions','https://www.europeana.eu/en/share-your-collections','https://pro.europeana.eu/page/search','https://pro.europeana.eu/page/apis','https://api.europeana.eu/',
'https://digitalcollections.nypl.org/','https://digitalcollections.nypl.org/search/index','https://digitalcollections.nypl.org/collections','https://digitalcollections.nypl.org/divisions','https://digitalcollections.nypl.org/items','https://digitalcollections.nypl.org/about','https://digitalcollections.nypl.org/terms','https://www.nypl.org/research/collections/digital-collections','https://www.nypl.org/research/research-catalog','https://www.nypl.org/research/collections',
'https://www.metmuseum.org/art/collection','https://www.metmuseum.org/art/collection/search','https://www.metmuseum.org/art/collection/open-access','https://www.metmuseum.org/about-the-met/policies-and-documents/open-access','https://www.metmuseum.org/art/libraries-and-research-centers','https://www.metmuseum.org/art/libraries-and-research-centers/watson-digital-collections','https://www.metmuseum.org/art/libraries-and-research-centers/watson-digital-collections/metropolitan-museum-of-art-publications','https://www.metmuseum.org/perspectives','https://www.metmuseum.org/art/online-features','https://www.metmuseum.org/art/collection/search#!?showOnly=openAccess',
'https://www.getty.edu/art/collection/','https://www.getty.edu/art/collection/search/','https://www.getty.edu/projects/open-content-program/','https://www.getty.edu/research/tools/','https://www.getty.edu/research/tools/digital_collections/','https://www.getty.edu/research/special_collections/','https://www.getty.edu/research/library/','https://www.getty.edu/research/library/search/','https://www.getty.edu/publications/','https://www.getty.edu/art/exhibitions/',
'https://www.nga.gov/artworks/free-images-and-open-access','https://www.nga.gov/collection','https://www.nga.gov/collection-search-result.html','https://www.nga.gov/research','https://www.nga.gov/research/library','https://www.nga.gov/research/gallery-archives','https://www.nga.gov/research/casva','https://www.nga.gov/learn/teachers/lessons-activities.html','https://www.nga.gov/features/slideshows.html','https://www.nga.gov/press',
'https://www.artic.edu/collection','https://www.artic.edu/open-access/open-access-images','https://www.artic.edu/aic/libraries','https://www.artic.edu/aic/libraries/digital-collections','https://www.artic.edu/aic/libraries/digital-collections/collections','https://www.artic.edu/aic/libraries/digital-collections/search','https://www.artic.edu/artworks','https://www.artic.edu/exhibitions','https://www.artic.edu/highlights','https://www.artic.edu/api/v1/artworks',
'https://archive.org/details/image','https://archive.org/details/photos','https://archive.org/details/flickrcommons','https://archive.org/details/metropolitanmuseumofart-gallery','https://archive.org/details/smithsonian','https://archive.org/details/library_of_congress','https://archive.org/details/national_archives','https://archive.org/details/americana','https://archive.org/details/texts','https://archive.org/advancedsearch.php',
'https://chroniclingamerica.loc.gov/','https://chroniclingamerica.loc.gov/search/pages/results/','https://chroniclingamerica.loc.gov/newspapers/','https://chroniclingamerica.loc.gov/about/','https://chroniclingamerica.loc.gov/help/','https://chroniclingamerica.loc.gov/data/','https://chroniclingamerica.loc.gov/awardees/','https://chroniclingamerica.loc.gov/essays/','https://chroniclingamerica.loc.gov/lccn/','https://chroniclingamerica.loc.gov/search/titles/results/',
'https://www.reuters.com/pictures/','https://apnews.com/hub/photos','https://www.npr.org/sections/pictureshow/','https://www.pbs.org/newshour/photos','https://www.c-span.org/search/','https://www.c-span.org/person/','https://www.c-span.org/video/','https://www.c-span.org/series/','https://www.c-span.org/classroom/','https://www.c-span.org/about/',
'https://www.gpo.gov/who-we-are/our-agency/history','https://www.govinfo.gov/app/collection/crec','https://www.govinfo.gov/app/collection/cdir','https://www.govinfo.gov/app/collection/cdoc','https://www.govinfo.gov/app/collection/cprt','https://www.govinfo.gov/app/collection/chrg','https://www.govinfo.gov/app/collection/fr','https://www.govinfo.gov/app/collection/serialset','https://www.govinfo.gov/app/collection/statute','https://www.govinfo.gov/app/collection/uscode',
'https://www.defense.gov/Multimedia/Photos/','https://www.defense.gov/Multimedia/Videos/','https://www.defense.gov/News/','https://www.defense.gov/News/Photos/','https://www.defense.gov/News/Releases/','https://www.defense.gov/News/Transcripts/','https://www.defense.gov/News/Speeches/','https://www.defense.gov/Spotlights/','https://www.defense.gov/Multimedia/Experience/','https://www.defense.gov/Multimedia/',
'https://www.army.mil/photos','https://www.navy.mil/Resources/Photo-Gallery/','https://www.af.mil/News/Photos/','https://www.marines.mil/Photos/','https://www.spaceforce.mil/Multimedia/Photos/','https://www.uscg.mil/Resources/Photo-Gallery/','https://www.nationalguard.mil/Resources/Image-Gallery/','https://www.dia.mil/News-Features/Images/','https://www.nsa.gov/Press-Room/Multimedia/','https://www.cia.gov/legacy/museum/artifact/'
];
const urls=[...new Set(roots)].slice(0,200);
if(urls.length!==200) throw new Error(`Pantheon batch 15 expected 200 distinct URLs, got ${urls.length}`);
const cats=(u:string):string[]=>/reuters|apnews|npr|pbs|c-span|chronicling/i.test(u)?['news','adverse-media','chronology','historical']:/archives|loc\.gov|archive\.org|dp\.la|europeana|nypl/i.test(u)?['historical','identity-resolution','chronology','publications']:['internet','historical','identity-resolution','publications'];
export const PANTHEON_VERIFIED_SOURCES_BATCH_15:PantheonVerifiedSource[]=urls.map((url,i)=>({id:`b15-${String(i+1).padStart(3,'0')}`,name:`Public image/media source ${i+1}`,url,jurisdiction:'US/global',categories:cats(url),authority:/\.gov|si\.edu|loc\.gov|archives\.gov/.test(url)?'primary':'secondary',verifiedAt:V}));
