import type { PantheonVerifiedSource } from './batch01';
const V='2026-09-20';
/** Batch 21: public property, housing, land, tax, mortgage, parcel and geographic sources. */
const roots=[
'https://www.hud.gov/','https://www.huduser.gov/portal/datasets/','https://www.huduser.gov/portal/datasets/fmr.html','https://www.huduser.gov/portal/datasets/il.html','https://www.huduser.gov/portal/datasets/cp.html','https://www.huduser.gov/portal/datasets/ahs.html','https://www.huduser.gov/portal/datasets/pdrdatas.html','https://www.huduser.gov/portal/datasets/picture/yearlydata.html','https://www.huduser.gov/portal/datasets/assthsg.html','https://www.huduser.gov/portal/datasets/lihtc.html',
'https://www.hud.gov/program_offices/housing','https://www.hud.gov/program_offices/public_indian_housing','https://www.hud.gov/program_offices/comm_planning','https://www.hud.gov/program_offices/fair_housing_equal_opp','https://www.hud.gov/states','https://www.hud.gov/housingcounseling','https://www.hud.gov/fha','https://www.hud.gov/press','https://www.hud.gov/foia','https://www.hud.gov/data',
'https://www.fhfa.gov/','https://www.fhfa.gov/data','https://www.fhfa.gov/data/hpi','https://www.fhfa.gov/data/dashboards','https://www.fhfa.gov/data/datasets','https://www.fhfa.gov/data/freddie-mac-and-fannie-mae-loan-level-data','https://www.fhfa.gov/supervision','https://www.fhfa.gov/regulation','https://www.fhfa.gov/public-input','https://www.fhfa.gov/news',
'https://www.consumerfinance.gov/data-research/hmda/','https://ffiec.cfpb.gov/','https://ffiec.cfpb.gov/data-browser/','https://ffiec.cfpb.gov/data-publication/','https://ffiec.cfpb.gov/documentation/','https://www.consumerfinance.gov/data-research/mortgage-performance-trends/','https://www.consumerfinance.gov/data-research/consumer-credit-trends/mortgages/','https://www.consumerfinance.gov/consumer-tools/mortgages/','https://www.consumerfinance.gov/rules-policy/mortgage-resources/','https://www.consumerfinance.gov/enforcement/actions/',
'https://www.census.gov/programs-surveys/ahs.html','https://www.census.gov/programs-surveys/ahs/data.html','https://www.census.gov/programs-surveys/acs/','https://data.census.gov/','https://api.census.gov/data.html','https://www.census.gov/construction/nrs/','https://www.census.gov/construction/bps/','https://www.census.gov/construction/nrc/','https://www.census.gov/housing/hvs/','https://www.census.gov/topics/housing.html',
'https://www.usgs.gov/programs/national-geospatial-program','https://apps.nationalmap.gov/viewer/','https://apps.nationalmap.gov/downloader/','https://www.usgs.gov/the-national-map-data-delivery','https://www.usgs.gov/programs/national-geospatial-program/national-map','https://www.usgs.gov/programs/national-geospatial-program/us-topo-maps-america','https://www.usgs.gov/programs/national-geospatial-program/historical-topographic-maps-preserving-past','https://www.usgs.gov/programs/national-geospatial-program/3d-elevation-program','https://www.usgs.gov/programs/national-geospatial-program/national-hydrography','https://www.usgs.gov/programs/national-geospatial-program/geographic-names-information-system',
'https://geonames.usgs.gov/','https://edits.nationalmap.gov/apps/gaz-domestic/public/search/names','https://www.usgs.gov/us-board-on-geographic-names','https://www.usgs.gov/tools/geographic-names-information-system-gnis','https://www.usgs.gov/programs/national-geospatial-program/national-map-gazetteer','https://www.usgs.gov/core-science-systems/ngp/tnm-delivery/','https://prd-tnm.s3.amazonaws.com/index.html','https://basemap.nationalmap.gov/','https://hydro.nationalmap.gov/arcgis/rest/services/nhd/MapServer','https://carto.nationalmap.gov/arcgis/rest/services/',
'https://www.blm.gov/','https://www.blm.gov/services/land-records','https://glorecords.blm.gov/','https://glorecords.blm.gov/search/default.aspx','https://glorecords.blm.gov/search/patent/default.aspx','https://glorecords.blm.gov/search/survey/default.aspx','https://glorecords.blm.gov/search/tractbook/default.aspx','https://www.blm.gov/services/geospatial','https://gbp-blm-egis.hub.arcgis.com/','https://www.blm.gov/programs/lands-and-realty',
'https://www.usda.gov/','https://www.nrcs.usda.gov/resources/data-and-reports','https://websoilsurvey.nrcs.usda.gov/','https://www.nrcs.usda.gov/resources/data-and-reports/soil-survey','https://www.nrcs.usda.gov/resources/data-and-reports/geospatial-data-gateway','https://www.fsa.usda.gov/resources/programs','https://www.fsa.usda.gov/resources/programs/farm-records','https://www.ers.usda.gov/data-products','https://www.nass.usda.gov/Quick_Stats/','https://www.nass.usda.gov/Data_and_Statistics/',
'https://www.fema.gov/','https://msc.fema.gov/portal/home','https://msc.fema.gov/portal/search','https://hazards.fema.gov/nri/','https://www.fema.gov/flood-maps','https://www.fema.gov/openfema-data-page','https://www.fema.gov/about/openfema/data-sets','https://www.fema.gov/disaster/declarations','https://www.fema.gov/assistance/individual','https://www.fema.gov/assistance/public',
'https://www.epa.gov/enviro','https://enviro.epa.gov/','https://echo.epa.gov/','https://echo.epa.gov/facilities/facility-search','https://www.epa.gov/frs','https://www.epa.gov/superfund/search-superfund-sites-where-you-live','https://www.epa.gov/brownfields','https://www.epa.gov/lead','https://www.epa.gov/radon','https://www.epa.gov/ust',
'https://www.nps.gov/subjects/nationalregister/index.htm','https://www.nps.gov/subjects/nationalregister/database-research.htm','https://www.nps.gov/subjects/nationalregister/national-register-database-research.htm','https://www.nps.gov/subjects/nationalhistoriclandmarks/index.htm','https://www.nps.gov/subjects/nationalregister/publications.htm','https://www.nps.gov/subjects/nationalregister/weekly-list.htm','https://www.nps.gov/subjects/nationalregister/listing-a-property.htm','https://www.nps.gov/subjects/nationalregister/state-historic-preservation-offices.htm','https://www.nps.gov/subjects/nationalregister/data-downloads.htm','https://www.nps.gov/subjects/nationalregister/gis-data-download.htm',
'https://www.regrid.com/','https://app.regrid.com/','https://regrid.com/property-app','https://regrid.com/api','https://regrid.com/reports','https://www.landgrid.com/','https://qpublic.schneidercorp.com/','https://beacon.schneidercorp.com/','https://www.actdatascout.com/','https://www.vgsi.com/',
'https://www.zillow.com/','https://www.zillow.com/homes/','https://www.zillow.com/research/data/','https://www.redfin.com/','https://www.redfin.com/news/data-center/','https://www.realtor.com/','https://www.realtor.com/realestateandhomes-search/','https://www.trulia.com/','https://www.homes.com/','https://www.loopnet.com/',
'https://www.crexi.com/','https://www.landwatch.com/','https://www.land.com/','https://www.landandfarm.com/','https://www.propertyshark.com/','https://www.propertyiq.com/','https://www.corelogic.com/','https://www.attomdata.com/','https://www.blackknightinc.com/data-solutions/','https://www.ice.com/mortgage-technology',
'https://www.irs.gov/businesses/small-businesses-self-employed/real-estate-tax-center','https://www.irs.gov/taxtopics/tc701','https://www.irs.gov/taxtopics/tc703','https://www.irs.gov/publications/p523','https://www.irs.gov/publications/p527','https://www.irs.gov/publications/p936','https://www.irs.gov/publications/p551','https://www.irs.gov/publications/p587','https://www.irs.gov/publications/p925','https://www.irs.gov/forms-pubs/about-form-1098',
'https://www.treasury.gov/','https://home.treasury.gov/policy-issues/financing-the-government','https://home.treasury.gov/data','https://fiscaldata.treasury.gov/','https://fiscaldata.treasury.gov/datasets/','https://home.treasury.gov/policy-issues/tax-policy','https://home.treasury.gov/services/treasury-payments','https://home.treasury.gov/services/report-fraud-waste-and-abuse','https://home.treasury.gov/foia','https://home.treasury.gov/news',
'https://www.usa.gov/property','https://www.usa.gov/unclaimed-money','https://www.usa.gov/state-treasury','https://www.usa.gov/state-governments','https://www.usa.gov/local-governments','https://www.usa.gov/housing-help','https://www.usa.gov/mortgages','https://www.usa.gov/buying-home','https://www.usa.gov/foreclosure','https://www.usa.gov/rental-housing',
'https://www.gsa.gov/real-estate','https://www.gsa.gov/real-estate/real-estate-services','https://www.gsa.gov/real-estate/real-estate-services/leasing','https://www.gsa.gov/real-estate/real-estate-services/disposal','https://www.gsa.gov/real-estate/historic-preservation','https://www.gsa.gov/real-estate/environmental-programs','https://www.gsa.gov/real-estate/design-and-construction','https://www.gsa.gov/real-estate/gsa-properties','https://www.gsa.gov/real-estate/real-property-utilization-and-disposal','https://www.gsa.gov/real-estate/real-property-disposal',
'https://catalog.data.gov/dataset?tags=property','https://catalog.data.gov/dataset?tags=parcel','https://catalog.data.gov/dataset?tags=housing','https://catalog.data.gov/dataset?tags=real-estate','https://catalog.data.gov/dataset?tags=land','https://catalog.data.gov/dataset?tags=mortgage','https://catalog.data.gov/dataset?tags=tax','https://catalog.data.gov/dataset?tags=address','https://catalog.data.gov/dataset?tags=geospatial','https://catalog.data.gov/dataset?tags=cadastral'
];
const urls=[...new Set(roots)].slice(0,200);
if(urls.length!==200) throw new Error(`Pantheon batch 21 expected 200 distinct URLs, got ${urls.length}`);
const cats=(u:string):string[]=>/hud|fhfa|mortgage|zillow|redfin|realtor|trulia|homes\.com/i.test(u)?['property','residence','financial-public','geography']:/blm|usgs|land|parcel|regrid|qpublic|beacon/i.test(u)?['property','geography','historical','residence']:/irs|treasury|tax/i.test(u)?['tax-public','property','financial-public']:['property','residence','geography','corroboration'];
export const PANTHEON_VERIFIED_SOURCES_BATCH_21:PantheonVerifiedSource[]=urls.map((url,i)=>({id:`b21-${String(i+1).padStart(3,'0')}`,name:`Property/land public source ${i+1}`,url,jurisdiction:'US',categories:cats(url),authority:/\.gov|census\.gov|usgs\.gov/.test(url)?'primary':'secondary',verifiedAt:V}));
