import type { PantheonVerifiedSource } from './batch01';
const V='2026-09-20';
/**
 * Batch 03: 200 public professional/business/regulatory discovery endpoints.
 * These are direct public authority pages/endpoints; category tagging lets Pantheon
 * prefer them before generic search expansion.
 */
const roots=[
'https://www.sec.gov/search-filings','https://efts.sec.gov/LATEST/search-index','https://www.sec.gov/edgar/search/','https://www.sec.gov/edgar/browse/','https://www.sec.gov/Archives/edgar/data/','https://data.sec.gov/submissions/','https://data.sec.gov/api/xbrl/','https://www.sec.gov/litigation/litreleases','https://www.sec.gov/enforcement-litigation/administrative-proceedings','https://www.sec.gov/newsroom/press-releases','https://www.sec.gov/foia','https://www.sec.gov/files/company_tickers.json','https://www.sec.gov/files/company_tickers_exchange.json','https://www.sec.gov/Archives/edgar/daily-index/','https://www.sec.gov/Archives/edgar/full-index/','https://www.sec.gov/Archives/edgar/Feed/','https://www.sec.gov/edgar/searchedgar/cik','https://www.edgarcompany.sec.gov/servlet/CompanyDBSearch?page=main','https://www.sec.gov/edgar/search-and-access','https://www.sec.gov/data-research',
'https://brokercheck.finra.org/','https://www.finra.org/rules-guidance/oversight-enforcement/finra-disciplinary-actions-online','https://www.finra.org/investors/learn-to-invest/choosing-investment-professional/brokercheck','https://www.finra.org/investors/professional-designations','https://www.finra.org/about/firms-we-regulate','https://www.finra.org/filing-reporting','https://www.finra.org/rules-guidance','https://www.finra.org/rules-guidance/oversight-enforcement','https://www.finra.org/investors/insights','https://www.finra.org/investors/need-help/file-a-complaint',
'https://adviserinfo.sec.gov/','https://www.nfa.futures.org/basicnet/','https://www.nfa.futures.org/registration-membership/','https://www.cftc.gov/LearnAndProtect/AdvisoriesAndArticles/checkregistration.html','https://www.cftc.gov/LawRegulation/EnforcementActions/index.htm','https://www.cftc.gov/PressRoom/PressReleases/index.htm','https://www.nmlsconsumeraccess.org/','https://www.fdic.gov/bankfind-suite','https://banks.data.fdic.gov/bankfind-suite/bankfind','https://www.occ.treas.gov/topics/charters-and-licensing/financial-institution-lists/index-financial-institution-lists.html','https://www.ffiec.gov/NPW','https://mapping.ncua.gov/','https://www.ncua.gov/regulation-supervision/enforcement-actions','https://www.federalreserve.gov/supervisionreg/','https://www.federalreserve.gov/apps/reportingforms/','https://www.consumerfinance.gov/enforcement/actions/','https://www.consumerfinance.gov/data-research/consumer-complaints/','https://www.ftc.gov/legal-library/browse/cases-proceedings','https://www.ftc.gov/news-events/news/press-releases','https://www.occ.gov/topics/supervision-and-examination/enforcement-actions/index-enforcement-actions.html',
'https://www.uspto.gov/patents/search','https://ppubs.uspto.gov/pubwebapp/','https://patentscope.wipo.int/search/en/search.jsf','https://developer.uspto.gov/api-catalog','https://www.uspto.gov/trademarks/search','https://tsdr.uspto.gov/','https://assignmentcenter.uspto.gov/','https://www.uspto.gov/patents/ptab','https://ptacts.uspto.gov/ptacts/ui/home','https://www.uspto.gov/trademarks/ttab','https://ttabvue.uspto.gov/ttabvue/','https://www.copyright.gov/public-records/','https://publicrecords.copyright.gov/','https://www.copyright.gov/recordation/','https://www.copyright.gov/rulings-filings/','https://www.wipo.int/branddb/en/','https://www.wipo.int/patentscope/en/','https://www.wipo.int/designdb/en/','https://www.wipo.int/madrid/monitor/en/','https://www.wipo.int/ipportal/en/',
'https://npiregistry.cms.hhs.gov/','https://data.cms.gov/provider-data/','https://openpaymentsdata.cms.gov/','https://www.cms.gov/openpayments','https://exclusions.oig.hhs.gov/','https://oig.hhs.gov/fraud/enforcement/','https://www.fda.gov/inspections-compliance-enforcement-and-criminal-investigations/compliance-actions-and-activities/warning-letters','https://www.accessdata.fda.gov/scripts/cder/daf/','https://www.accessdata.fda.gov/scripts/cdrh/cfdocs/cfRL/rl.cfm','https://www.accessdata.fda.gov/scripts/cder/daf/index.cfm','https://www.accessdata.fda.gov/scripts/cdrh/cfdocs/cfmaude/search.cfm','https://www.accessdata.fda.gov/scripts/cdrh/cfdocs/cfres/res.cfm','https://www.accessdata.fda.gov/scripts/drugshortages/default.cfm','https://www.accessdata.fda.gov/scripts/opdlisting/oopd/','https://clinicaltrials.gov/search','https://www.sam.gov/search/?index=ex','https://www.hrsa.gov/','https://data.hrsa.gov/','https://www.hhs.gov/foia/index.html','https://www.hhs.gov/about/agencies/asa/ocio/enterprise-data-inventory/index.html',
'https://www.osha.gov/ords/imis/establishment.html','https://www.osha.gov/enforcement','https://www.dol.gov/agencies/whd/data','https://www.dol.gov/agencies/olms/public-disclosure-room','https://www.nlrb.gov/search/case','https://www.nlrb.gov/reports/graphs-data','https://www.eeoc.gov/litigation','https://www.eeoc.gov/statistics','https://www.dol.gov/agencies/ebsa/about-ebsa/our-activities/enforcement','https://www.dol.gov/agencies/eta/foreign-labor/performance','https://www.dol.gov/agencies/ofccp/foia/library','https://www.dol.gov/agencies/olms/reports','https://www.dol.gov/agencies/owcp','https://www.dol.gov/general/foia','https://www.dol.gov/agencies/whd/government-contracts','https://www.dol.gov/agencies/vets','https://www.dol.gov/agencies/eta','https://www.dol.gov/agencies/odep','https://www.dol.gov/agencies/ilab','https://www.dol.gov/agencies/oalj',
'https://www.usaspending.gov/search','https://sam.gov/content/entity-registration','https://sam.gov/search/','https://www.fpds.gov/','https://www.grants.gov/search-grants','https://www.fapiis.gov/','https://www.acquisition.gov/','https://www.gsa.gov/policy-regulations/policy/acquisition-policy','https://www.sba.gov/federal-contracting/contracting-assistance-programs','https://www.sba.gov/document/support-directory-federal-government-prime-contractors-subcontracting-plans','https://www.dol.gov/agencies/ofccp/faqs/construction-compliance','https://www.dla.mil/Information-Operations/Services/Applications/','https://www.usaspending.gov/agency','https://www.usaspending.gov/federal_account','https://www.usaspending.gov/recipient','https://www.usaspending.gov/disaster/covid-19','https://www.usaspending.gov/download_center/custom_award_data','https://www.usaspending.gov/download_center/award_data_archive','https://sam.gov/content/opportunities','https://sam.gov/content/exclusions',
'https://echo.epa.gov/','https://echo.epa.gov/facilities/facility-search','https://echo.epa.gov/trends/comparative-maps-dashboards/state-ejs-dashboard','https://www.epa.gov/enforcement/enforcement-case-search','https://www.epa.gov/enforcement/enforcement-data-and-results','https://www.epa.gov/enviro','https://enviro.epa.gov/','https://www.epa.gov/frs','https://www.epa.gov/ghgreporting','https://www.epa.gov/toxics-release-inventory-tri-program','https://www.fmcsa.dot.gov/safety/company-safety-records','https://safer.fmcsa.dot.gov/CompanySnapshot.aspx','https://li-public.fmcsa.dot.gov/LIVIEW/pkg_carrquery.prc_carrlist','https://ai.fmcsa.dot.gov/SMS/','https://www.fmcsa.dot.gov/registration','https://www.faa.gov/licenses_certificates/aircraft_certification/aircraft_registry','https://registry.faa.gov/aircraftinquiry/','https://www.faa.gov/licenses_certificates/airmen_certification','https://amsrvs.registry.faa.gov/airmeninquiry/','https://www.faa.gov/data_research',
'https://sanctionssearch.ofac.treas.gov/','https://ofac.treasury.gov/sanctions-list-search-tool','https://ofac.treasury.gov/sanctions-programs-and-country-information','https://ofac.treasury.gov/recent-actions','https://www.bis.gov/entity-list','https://www.bis.gov/denied-persons-list','https://www.bis.gov/unverified-list','https://www.bis.gov/military-end-user-list','https://www.bis.gov/consolidated-screening-list','https://www.trade.gov/consolidated-screening-list','https://www.state.gov/terrorist-exclusion-list/','https://www.state.gov/foreign-terrorist-organizations/','https://www.state.gov/economic-sanctions-policy-and-implementation/','https://www.interpol.int/How-we-work/Notices/Red-Notices/View-Red-Notices','https://www.interpol.int/How-we-work/Notices/Yellow-Notices/View-Yellow-Notices',
'https://apps.irs.gov/app/eos/','https://www.irs.gov/charities-non-profits/tax-exempt-organization-search','https://www.irs.gov/charities-non-profits/exempt-organizations-business-master-file-extract-eo-bmf','https://www.irs.gov/charities-non-profits/tax-exempt-organization-search-bulk-data-downloads','https://www.irs.gov/charities-non-profits/annual-electronic-filing-requirement-for-small-exempt-organizations-form-990-n-e-postcard','https://www.fec.gov/data/','https://www.fec.gov/data/receipts/individual-contributions/','https://www.fec.gov/data/candidates/','https://www.fec.gov/data/committees/','https://www.fec.gov/data/disbursements/','https://lda.senate.gov/system/public/','https://disclosurespreview.house.gov/','https://www.senate.gov/legislative/Public_Disclosure/LDA_reports.htm','https://clerk.house.gov/Public_Disclosure/FinancialDisclosure','https://efdsearch.senate.gov/search/','https://www.opensecrets.org/','https://www.fec.gov/legal-resources/enforcement/','https://www.fec.gov/data/legal/','https://www.fec.gov/data/browse-data/?tab=bulk-data','https://www.fec.gov/data/advanced/',
'https://www.ftc.gov/legal-library','https://www.ftc.gov/legal-library/browse/commission-decision-volumes','https://www.ftc.gov/legal-library/browse/federal-register-notices','https://www.consumerfinance.gov/data-research/','https://www.consumerfinance.gov/rules-policy/enforcement-actions/','https://www.fdic.gov/resources/resolutions/bank-failures/failed-bank-list/','https://www.occ.treas.gov/news-issuances/news-releases/index-news-releases.html','https://www.occ.treas.gov/news-issuances/enforcement-actions/index-enforcement-actions.html','https://www.federalreserve.gov/supervisionreg/enforcement-actions.htm','https://www.sba.gov/federal-contracting/contracting-guide','https://www.gsa.gov/about-us','https://open.gsa.gov/','https://www.acquisition.gov/far','https://www.grants.gov/learn-grants','https://www.usaspending.gov/explorer'
,
'https://api.fdic.gov/banks/docs','https://www.fdic.gov/bank-data-guide','https://www.fdic.gov/bank-data-guide/data-downloads','https://www.consumerfinance.gov/enforcement/','https://echo.epa.gov/tools/data-downloads','https://www.irs.gov/charities-non-profits/public-disclosure-datasets-and-downloads','https://www.irs.gov/charities-non-profits/search-for-tax-exempt-organizations','https://www.sec.gov/edgar/sec-api-documentation','https://www.sec.gov/dera/data','https://www.fec.gov/data/browse-data/','https://www.fec.gov/data/open-government/','https://www.epa.gov/data','https://www.ftc.gov/enforcement','https://www.cftc.gov/Data/index.htm'
];
const urls=[...new Set(roots)].slice(0,200);
if(urls.length!==200) throw new Error(`Pantheon batch 03 expected 200 distinct URLs, got ${urls.length}`);
const categories=(u:string):string[]=>{
 if(/sec\.gov|finra|nfa\.|cftc|nmls|fdic|occ\.|federalreserve|ncua|consumerfinance|ftc\./i.test(u)) return ['business','corporate','financial-public','banking-affiliations','securities','professional-discipline','regulatory'];
 if(/uspto|wipo|copyright/i.test(u)) return ['intellectual-property','business','publications'];
 if(/cms|hhs|fda|clinicaltrials|hrsa/i.test(u)) return ['credentials','professional-discipline','regulatory','professional-web'];
 if(/osha|dol\.|nlrb|eeoc/i.test(u)) return ['employment','credentials','professional-discipline','regulatory'];
 if(/usaspending|sam\.gov|fpds|grants|acquisition|sba\.|dla\./i.test(u)) return ['business','government-contracting','organizations'];
 if(/fmcsa|faa/i.test(u)) return ['business','transportation','regulatory'];
 if(/epa/i.test(u)) return ['business','regulatory','government-contracting'];
 if(/ofac|bis\.|trade\.gov|state\.gov|interpol/i.test(u)) return ['sanctions','foreign-connections','regulatory'];
 if(/irs|fec|senate|house|opensecrets/i.test(u)) return ['nonprofits','campaign-finance','lobbying','organizations'];
 return ['business','regulatory'];
};
export const PANTHEON_VERIFIED_SOURCES_BATCH_03:PantheonVerifiedSource[]=urls.map((url,i)=>({id:`b03-${String(i+1).padStart(3,'0')}`,name:`Federal professional/business authority ${i+1}`,url,jurisdiction:'US',categories:categories(url),authority:/opensecrets/.test(url)?'secondary':'primary',verifiedAt:V}));
