import type { PantheonVerifiedSource } from './batch01';
const V='2026-09-20';
/** Batch 10: federal sanctions, trade, immigration, elections, lobbying, ethics and public-service records. */
const roots=[
'https://sanctionssearch.ofac.treas.gov/','https://ofac.treasury.gov/sanctions-list-service','https://ofac.treasury.gov/sanctions-programs-and-country-information','https://ofac.treasury.gov/recent-actions','https://ofac.treasury.gov/specially-designated-nationals-list-data-formats-data-schemas','https://ofac.treasury.gov/consolidated-sanctions-list-non-sdn-lists','https://ofac.treasury.gov/faqs','https://home.treasury.gov/policy-issues/financial-sanctions','https://home.treasury.gov/news/press-releases','https://home.treasury.gov/data',
'https://www.trade.gov/consolidated-screening-list','https://www.trade.gov/data-visualization/csl-search','https://www.bis.gov/licensing/end-user-guidance','https://www.bis.gov/licensing/end-user-guidance/denied-persons-list-dpl','https://www.bis.gov/licensing/end-user-guidance/entity-list','https://www.bis.gov/licensing/end-user-guidance/unverified-list','https://www.bis.gov/licensing/end-user-guidance/military-end-user-list','https://www.bis.gov/enforcement','https://www.bis.gov/enforcement/oee','https://www.bis.gov/enforcement/violations',
'https://www.state.gov/','https://www.state.gov/reports/','https://www.state.gov/reports-bureau-of-democracy-human-rights-and-labor/','https://www.state.gov/reports/2025-country-reports-on-human-rights-practices/','https://www.state.gov/reports/2025-trafficking-in-persons-report/','https://www.state.gov/terrorist-exclusion-list/','https://www.state.gov/foreign-terrorist-organizations/','https://www.state.gov/executive-orders/','https://www.state.gov/press-releases/','https://www.state.gov/briefings-foreign-press-centers/',
'https://www.uscis.gov/','https://www.uscis.gov/tools','https://www.uscis.gov/tools/reports-and-studies','https://www.uscis.gov/tools/reports-and-studies/immigration-and-citizenship-data','https://www.uscis.gov/records','https://www.uscis.gov/records/genealogy','https://www.uscis.gov/records/genealogy/historical-record-series-available-from-the-genealogy-program','https://www.uscis.gov/records/genealogy/genealogical-records-help','https://www.uscis.gov/records/foia','https://www.uscis.gov/records/electronic-reading-room',
'https://www.ice.gov/','https://www.ice.gov/statistics','https://www.ice.gov/foia','https://www.ice.gov/foia/library','https://www.ice.gov/most-wanted','https://www.ice.gov/detain/detention-management','https://locator.ice.gov/odls/','https://www.ice.gov/detain/detention-facilities','https://www.ice.gov/news/releases','https://www.ice.gov/features',
'https://www.cbp.gov/','https://www.cbp.gov/newsroom/stats','https://www.cbp.gov/newsroom/media-releases','https://www.cbp.gov/document/foia-record','https://www.cbp.gov/site-policy-notices/foia','https://www.cbp.gov/trade/automated','https://www.cbp.gov/trade/rulings','https://rulings.cbp.gov/','https://www.cbp.gov/travel/international-visitors/i-94','https://i94.cbp.dhs.gov/',
'https://www.eoir.justice.gov/','https://www.justice.gov/eoir','https://www.justice.gov/eoir/precedent-decisions','https://www.justice.gov/eoir/virtual-law-library','https://www.justice.gov/eoir/foia-library','https://www.justice.gov/eoir/statistical-year-book','https://www.justice.gov/eoir/eoir-case-data','https://www.justice.gov/eoir/immigration-court-practice-manual','https://www.justice.gov/eoir/board-of-immigration-appeals','https://www.justice.gov/eoir/list-pro-bono-legal-service-providers',
'https://www.fec.gov/','https://www.fec.gov/data/','https://www.fec.gov/data/receipts/','https://www.fec.gov/data/disbursements/','https://www.fec.gov/data/candidates/','https://www.fec.gov/data/committees/','https://www.fec.gov/data/individual-contributions/','https://www.fec.gov/data/independent-expenditures/','https://www.fec.gov/data/elections/','https://www.fec.gov/data/browse-data/',
'https://www.fec.gov/data/legal/','https://www.fec.gov/legal-resources/enforcement/','https://www.fec.gov/legal-resources/court-cases/','https://www.fec.gov/legal-resources/advisory-opinions-process/','https://www.fec.gov/legal-resources/regulations/','https://www.fec.gov/legal-resources/policy-other-guidance/','https://www.fec.gov/updates/','https://www.fec.gov/press/','https://www.fec.gov/about/reports-about-fec/','https://www.fec.gov/foia/',
'https://lda.senate.gov/system/public/','https://www.senate.gov/legislative/Public_Disclosure/LDA_reports.htm','https://www.senate.gov/legislative/lobbyingdisc.htm','https://www.senate.gov/legislative/FinancialDisclosure.htm','https://efdsearch.senate.gov/search/','https://www.senate.gov/legislative/common/generic/ethics.htm','https://www.ethics.senate.gov/public/index.cfm/financialdisclosure','https://www.ethics.senate.gov/public/index.cfm/laws','https://www.ethics.senate.gov/public/index.cfm/advisories','https://www.ethics.senate.gov/public/index.cfm/pressreleases',
'https://disclosures-clerk.house.gov/','https://disclosures-clerk.house.gov/PublicDisclosure/FinancialDisclosure','https://disclosures-clerk.house.gov/PublicDisclosure/FinancialDisclosureViewMember','https://disclosures-clerk.house.gov/PublicDisclosure/FinancialDisclosureViewCandidates','https://disclosures-clerk.house.gov/ForeignTravel/','https://disclosures-clerk.house.gov/PublicDisclosure/GiftTravelFilings','https://lobbyingdisclosure.house.gov/','https://ethics.house.gov/financial-disclosure','https://ethics.house.gov/publications','https://ethics.house.gov/press-releases',
'https://www.opm.gov/','https://www.opm.gov/data/','https://www.opm.gov/data/datasets/','https://www.opm.gov/policy-data-oversight/data-analysis-documentation/federal-employment-reports/','https://www.opm.gov/policy-data-oversight/pay-leave/salaries-wages/','https://www.opm.gov/policy-data-oversight/senior-executive-service/','https://www.opm.gov/policy-data-oversight/employee-relations/','https://www.opm.gov/policy-data-oversight/employee-relations/employee-rights-appeals/','https://www.opm.gov/information-management/freedom-of-information-act/','https://www.opm.gov/about-us/open-government/',
'https://www.oge.gov/','https://www.oge.gov/web/oge.nsf/Resources/Public+Financial+Disclosure+Guide','https://www.oge.gov/web/oge.nsf/Resources/Officials%27+Individual+Disclosures+Search+Collection','https://www.oge.gov/web/oge.nsf/Resources/Agency+Ethics+Program+Data','https://www.oge.gov/web/oge.nsf/Resources/FOIA','https://www.oge.gov/web/oge.nsf/Resources/Legal+Advisories','https://www.oge.gov/web/oge.nsf/Resources/Education+Resources','https://www.oge.gov/web/oge.nsf/Resources/Program+Review+Reports','https://www.oge.gov/web/oge.nsf/Resources/Enforcement+Actions','https://www.oge.gov/web/oge.nsf/Resources/Presidential+Nominee+and+Appointee+Records',
'https://osc.gov/','https://osc.gov/Services/Pages/FOIA-Resources.aspx','https://osc.gov/Services/Pages/HatchAct.aspx','https://osc.gov/Services/Pages/PPP.aspx','https://osc.gov/Services/Pages/Disclosure.aspx','https://osc.gov/News/Pages/default.aspx','https://osc.gov/Documents/Pages/default.aspx','https://osc.gov/Resources/Pages/default.aspx','https://osc.gov/Agency/Pages/Annual-Reports.aspx','https://osc.gov/Agency/Pages/Performance-and-Accountability.aspx',
'https://www.gao.gov/','https://www.gao.gov/reports-testimonies','https://www.gao.gov/legal','https://www.gao.gov/legal/bid-protests','https://www.gao.gov/legal/appropriations-law','https://www.gao.gov/legal/other-legal-work','https://www.gao.gov/fraudnet','https://www.gao.gov/about/what-gao-does','https://www.gao.gov/about/careers','https://www.gao.gov/about/press-center',
'https://www.oversight.gov/','https://www.oversight.gov/reports','https://www.oversight.gov/investigations','https://www.oversight.gov/recommendations','https://www.oversight.gov/inspectors-general','https://www.oversight.gov/whistleblowers','https://www.oversight.gov/fraud-waste-abuse','https://www.oversight.gov/press-releases','https://www.oversight.gov/data','https://www.oversight.gov/about',
'https://www.federalregister.gov/','https://www.federalregister.gov/documents/search','https://www.federalregister.gov/agencies','https://www.federalregister.gov/presidential-documents','https://www.federalregister.gov/public-inspection/current','https://www.federalregister.gov/documents/current','https://www.federalregister.gov/documents/search?conditions%5Btype%5D%5B%5D=NOTICE','https://www.federalregister.gov/documents/search?conditions%5Btype%5D%5B%5D=RULE','https://www.federalregister.gov/documents/search?conditions%5Btype%5D%5B%5D=PRORULE','https://www.federalregister.gov/developers/documentation/api/v1',
'https://www.regulations.gov/','https://www.regulations.gov/search','https://www.regulations.gov/dockets','https://www.regulations.gov/documents','https://www.regulations.gov/comments','https://www.regulations.gov/faq','https://open.gsa.gov/api/regulationsgov/','https://api.regulations.gov/','https://www.reginfo.gov/public/','https://www.reginfo.gov/public/do/eAgendaMain',
'https://www.whitehouse.gov/','https://www.whitehouse.gov/presidential-actions/','https://www.whitehouse.gov/presidential-actions/executive-orders/','https://www.whitehouse.gov/presidential-actions/presidential-memoranda/','https://www.whitehouse.gov/presidential-actions/proclamations/','https://www.whitehouse.gov/briefing-room/','https://www.whitehouse.gov/briefing-room/statements-releases/','https://www.whitehouse.gov/briefing-room/presidential-actions/','https://www.whitehouse.gov/omb/','https://www.whitehouse.gov/ostp/',
'https://www.congress.gov/','https://www.congress.gov/members','https://www.congress.gov/committees','https://www.congress.gov/committee-reports','https://www.congress.gov/congressional-record','https://www.congress.gov/legislation','https://www.congress.gov/nominations','https://www.congress.gov/treaties','https://www.congress.gov/committee-meetings','https://www.congress.gov/help/field-values/member-bioguide-ids'
];
const urls=[...new Set(roots)].slice(0,200);
if(urls.length!==200) throw new Error(`Pantheon batch 10 expected 200 distinct URLs, got ${urls.length}`);
const cats=(u:string):string[]=>/ofac|treasury|trade\.gov|bis\.gov/i.test(u)?['sanctions','foreign-connections','regulatory','business']:/uscis|ice\.gov|cbp|eoir/i.test(u)?['immigration','foreign-residence','government-employment']:/fec|senate|house\.gov|oge|osc|congress|whitehouse/i.test(u)?['campaign-finance','lobbying','government-employment','government-contracting']:/gao|oversight|federalregister|regulations/i.test(u)?['regulatory','government-contracting','government-employment']:['government-employment','regulatory'];
export const PANTHEON_VERIFIED_SOURCES_BATCH_10:PantheonVerifiedSource[]=urls.map((url,i)=>({id:`b10-${String(i+1).padStart(3,'0')}`,name:`Federal public-service/sanctions source ${i+1}`,url,jurisdiction:'US',categories:cats(url),authority:'primary',verifiedAt:V}));
