import type { PantheonVerifiedSource } from './batch01';
const V='2026-09-20';
/** Batch 12: authoritative education, credentials, professional licensing and disciplinary sources. */
const roots=[
'https://ope.ed.gov/dapip/','https://nces.ed.gov/collegenavigator/','https://nces.ed.gov/ipeds/','https://nces.ed.gov/ipeds/datacenter/','https://nces.ed.gov/globallocator/','https://nces.ed.gov/ccd/schoolsearch/','https://nces.ed.gov/ccd/districtsearch/','https://nces.ed.gov/programs/digest/','https://nces.ed.gov/surveys/ntps/','https://nces.ed.gov/fastfacts/','https://studentaid.gov/','https://studentaid.gov/understand-aid/eligibility/requirements','https://studentaid.gov/data-center/','https://studentaid.gov/data-center/student/title-iv','https://studentaid.gov/data-center/school','https://studentaid.gov/data-center/school/geographic','https://studentaid.gov/data-center/school/programs','https://studentaid.gov/data-center/school/default','https://studentaid.gov/data-center/student/application-volume/fafsa-school-state','https://studentaid.gov/data-center/student/application-volume/fafsa-completion-high-school',
'https://www.ed.gov/laws-and-policy/civil-rights-laws/file-complaint','https://ocrcas.ed.gov/','https://www.ed.gov/laws-and-policy/civil-rights-laws/civil-rights-data','https://civilrightsdata.ed.gov/','https://www.ed.gov/data','https://www.ed.gov/research-data','https://ies.ed.gov/','https://ies.ed.gov/data.asp','https://ies.ed.gov/ncee/wwc/','https://eric.ed.gov/',
'https://www.ed.gov/grants-and-programs','https://www.ed.gov/grants-and-programs/formula-grants','https://www.ed.gov/grants-and-programs/grants-higher-education','https://www.ed.gov/grants-and-programs/grants-special-populations','https://www.ed.gov/grants-and-programs/grants-birth-grade-12','https://www.ed.gov/grants-and-programs/grants-postsecondary','https://www.ed.gov/grants-and-programs/grants-state-and-local','https://www.ed.gov/grants-and-programs/grants-research-and-statistics','https://www.ed.gov/grants-and-programs/grants-innovation','https://www.ed.gov/grants-and-programs/grants-teacher-preparation',
'https://www.acenursing.org/search-programs','https://www.aacnnursing.org/ccne-accreditation/find-accredited-programs','https://www.abet.org/accreditation/find-programs/','https://www.ada.org/resources/research/commission-on-dental-accreditation/find-a-program','https://www.apa.org/ed/accreditation/programs','https://www.cswe.org/accreditation/directory-of-accredited-programs/','https://www.asha.org/academic/accreditation/edfind/','https://www.arc-pa.org/accreditation/accredited-programs/','https://www.capteonline.org/about-capte/accredited-programs','https://www.acgme.org/about-us/accredited-programs-and-institutions/',
'https://npiregistry.cms.hhs.gov/','https://download.cms.gov/nppes/NPI_Files.html','https://data.cms.gov/provider-data/','https://data.cms.gov/provider-characteristics/medicare-provider-supplier-enrollment','https://openpaymentsdata.cms.gov/','https://exclusions.oig.hhs.gov/','https://oig.hhs.gov/exclusions/','https://www.fsmb.org/contact-a-state-medical-board/','https://www.fsmb.org/physician-information/','https://www.docinfo.org/',
'https://www.nursys.com/','https://www.ncsbn.org/nursing-regulation/licensure.page','https://www.ncsbn.org/nursing-regulation/discipline.page','https://www.ncsbn.org/nursing-regulation/board-of-nursing.page','https://www.ncsbn.org/nursing-regulation/licensure/verification.page','https://www.ncsbn.org/nursing-regulation/licensure/compact.page','https://www.ncsbn.org/nursing-regulation/practice.page','https://www.ncsbn.org/nursing-regulation/education.page','https://www.ncsbn.org/nursing-regulation/discipline/nursys.page','https://www.ncsbn.org/nursing-regulation/discipline/alternative-to-discipline.page',
'https://www.ada.org/resources/licensure/licensure-dental-students','https://www.ada.org/resources/licensure/state-dental-boards','https://www.aavsb.org/public-resources/find-a-board','https://www.aavsb.org/public-resources/license-lookup','https://www.nabp.pharmacy/about/boards-of-pharmacy/','https://nabp.pharmacy/programs/cpe-monitor/','https://nabp.pharmacy/programs/verify-before-you-buy/','https://www.ptcompact.org/Verify','https://www.fsbpt.org/Free-Resources/Licensing-Authorities-Contact-Information','https://www.aswb.org/licenses/',
'https://www.aswb.org/licenses/how-to-get-a-license/','https://www.aswb.org/licenses/protecting-the-public/','https://www.nbcc.org/Search/CounselorFind','https://www.nasba.org/stateboards/','https://cpaverify.org/','https://www.aicpa-cima.com/resources/landing/cpa-verify','https://www.ncarb.org/get-licensed/state-licensing-boards','https://www.ncees.org/licensure/','https://www.ncees.org/member-licensing-boards/','https://www.ncees.org/records/',
'https://www.americanbar.org/groups/legal_education/resources/bar_admissions/','https://www.americanbar.org/groups/legal_education/resources/bar_admissions/bar-admissions-basic-overview/','https://www.ncbex.org/character-and-fitness','https://www.ncbex.org/exams/mpre','https://www.ncbex.org/exams/ube','https://www.ncbex.org/score-services','https://www.ncbex.org/statistics-research','https://www.ncbex.org/character-and-fitness/jurisdiction-information','https://www.ncbex.org/exams/jurisdiction-information','https://www.ncbex.org/',
'https://www.avvo.com/','https://www.martindale.com/','https://www.justia.com/lawyers','https://lawyers.findlaw.com/','https://www.lawyers.com/','https://www.nolo.com/lawyers/','https://www.healthgrades.com/','https://www.vitals.com/','https://www.doximity.com/','https://www.psychologytoday.com/us/therapists',
'https://www.faa.gov/licenses_certificates/airmen_certification','https://amsrvs.registry.faa.gov/airmeninquiry/','https://www.faa.gov/licenses_certificates/airmen_certification/airmen_inquiry','https://www.faa.gov/licenses_certificates/airmen_certification/airmen_services','https://www.faa.gov/licenses_certificates/airmen_certification/airmen_faq','https://www.faa.gov/licenses_certificates/airmen_certification/medical_certification','https://www.faa.gov/licenses_certificates/airmen_certification/foreign_license_verification','https://www.faa.gov/licenses_certificates/airmen_certification/airmen_certification_branches','https://www.faa.gov/licenses_certificates/airmen_certification/sport_pilot','https://www.faa.gov/licenses_certificates/airmen_certification/aircraft_dispatcher',
'https://www.fcc.gov/licensing-databases','https://www.fcc.gov/wireless/universal-licensing-system','https://wireless2.fcc.gov/UlsSearch/searchLicense.jsp','https://wireless2.fcc.gov/UlsSearch/searchAdvanced.jsp','https://wireless2.fcc.gov/UlsSearch/searchLicense.jsp?licKey=','https://www.fcc.gov/media/radio/public-and-broadcasting','https://www.fcc.gov/media/television/public-and-broadcasting','https://www.fcc.gov/ecfs/','https://www.fcc.gov/reports-research/maps','https://www.fcc.gov/reports-research',
'https://www.maritime.dot.gov/education/maritime-academies','https://www.dco.uscg.mil/nmc/','https://www.dco.uscg.mil/nmc/merchant_mariner_credential/','https://www.dco.uscg.mil/nmc/medical_certificate/','https://www.dco.uscg.mil/nmc/record_request/','https://www.dco.uscg.mil/nmc/checklist/','https://www.dco.uscg.mil/nmc/credentialing_process/','https://www.dco.uscg.mil/nmc/examinations/','https://www.dco.uscg.mil/nmc/training_assessments/','https://www.dco.uscg.mil/nmc/contact/',
'https://www.dol.gov/agencies/eta/apprenticeship','https://www.apprenticeship.gov/','https://www.apprenticeship.gov/apprenticeship-job-finder','https://www.apprenticeship.gov/partner-finder','https://www.apprenticeship.gov/employers','https://www.apprenticeship.gov/career-seekers','https://www.apprenticeship.gov/data-and-statistics','https://www.apprenticeship.gov/investments-tax-credits-and-tuition-support','https://www.apprenticeship.gov/registered-apprenticeship-program','https://www.apprenticeship.gov/educators',
'https://www.onetonline.org/','https://www.onetcenter.org/database.html','https://www.onetcenter.org/dictionary.html','https://www.onetcenter.org/taxonomy.html','https://www.onetcenter.org/reports.html','https://www.onetcenter.org/dataCollection.html','https://www.careeronestop.org/Toolkit/Training/find-certifications.aspx','https://www.careeronestop.org/Toolkit/Training/find-licenses.aspx','https://www.careeronestop.org/LocalHelp/EmploymentAndTraining/find-WIOA-training-programs.aspx','https://www.careeronestop.org/LocalHelp/AmericanJobCenters/american-job-centers.aspx',
'https://www.bls.gov/oes/','https://www.bls.gov/ooh/','https://www.bls.gov/emp/','https://www.bls.gov/cps/','https://www.bls.gov/nls/','https://www.bls.gov/cew/','https://www.bls.gov/lau/','https://www.bls.gov/jlt/','https://www.bls.gov/data/','https://www.bls.gov/developers/',
'https://www.opm.gov/policy-data-oversight/classification-qualifications/','https://www.opm.gov/policy-data-oversight/classification-qualifications/general-schedule-qualification-standards/','https://www.opm.gov/policy-data-oversight/classification-qualifications/classifying-general-schedule-positions/','https://www.opm.gov/policy-data-oversight/classification-qualifications/federal-wage-system-qualifications/','https://www.opm.gov/policy-data-oversight/assessment-and-selection/','https://www.opm.gov/policy-data-oversight/hiring-information/','https://www.opm.gov/policy-data-oversight/veterans-services/','https://www.opm.gov/policy-data-oversight/workforce-restructuring/','https://www.opm.gov/policy-data-oversight/data-analysis-documentation/','https://www.opm.gov/data/',
'https://www.usajobs.gov/','https://www.usajobs.gov/Search/Results','https://www.usajobs.gov/Help/working-in-government/','https://www.usajobs.gov/Help/how-to/account/profile/','https://www.usajobs.gov/Help/how-to/search/','https://www.usajobs.gov/Help/how-to/job-announcement/','https://www.usajobs.gov/Help/how-to/application/','https://www.usajobs.gov/Help/faq/','https://www.usajobs.gov/Help/working-in-government/unique-hiring-paths/','https://www.usajobs.gov/Help/working-in-government/pay-and-leave/',
'https://www.dol.gov/agencies/vets','https://www.dol.gov/agencies/vets/programs','https://www.dol.gov/agencies/vets/programs/tap','https://www.dol.gov/agencies/vets/programs/hvrp','https://www.dol.gov/agencies/vets/programs/jobs-for-veterans-state-grants','https://www.dol.gov/agencies/vets/programs/federal-contractor-program','https://www.dol.gov/agencies/vets/programs/stand-down','https://www.dol.gov/agencies/vets/programs/userr','https://www.dol.gov/agencies/vets/programs/veterans-employment-services','https://www.dol.gov/agencies/vets/resources'
];
const urls=[...new Set(roots)].slice(0,200);
if(urls.length!==200) throw new Error(`Pantheon batch 12 expected 200 distinct URLs, got ${urls.length}`);
const cats=(u:string):string[]=>/ed\.gov|nces|student|accredit|eric/i.test(u)?['education','credentials','publications']:/npi|nurs|medical|dental|pharmacy|license|ncees|nasba|ncbex|bar/i.test(u)?['credentials','professional-discipline','professional-web','employment']:/faa|fcc|uscg|maritime/i.test(u)?['credentials','professional-discipline','government-employment']:['employment','education','credentials','professional-web'];
export const PANTHEON_VERIFIED_SOURCES_BATCH_12:PantheonVerifiedSource[]=urls.map((url,i)=>({id:`b12-${String(i+1).padStart(3,'0')}`,name:`Education/credential source ${i+1}`,url,jurisdiction:'US',categories:cats(url),authority:/avvo|martindale|justia|findlaw|lawyers\.com|nolo|healthgrades|vitals|doximity|psychologytoday/.test(url)?'secondary':'primary',verifiedAt:V}));
