import type { PantheonVerifiedSource } from './batch01';
const V='2026-09-20';
/** Batch 18: public web-footprint, username, publication, developer and professional-profile sources. */
const roots=[
'https://github.com/search','https://github.com/search','https://api.github.com/','https://gist.github.com/','https://github.com/topics','https://github.com/trending','https://github.com/orgs','https://github.com/marketplace','https://github.com/collections','https://github.com/sponsors',
'https://gitlab.com/explore/projects','https://gitlab.com/explore','https://gitlab.com/explore/projects','https://gitlab.com/explore/groups','https://gitlab.com/explore/catalog','https://gitlab.com/public','https://gitlab.com/users/sign_in','https://docs.gitlab.com/api/users/','https://docs.gitlab.com/api/projects/','https://docs.gitlab.com/api/groups/',
'https://bitbucket.org/repo/all','https://bitbucket.org/product/','https://bitbucket.org/product/features','https://developer.atlassian.com/cloud/bitbucket/rest/','https://api.bitbucket.org/2.0/','https://support.atlassian.com/bitbucket-cloud/','https://www.npmjs.com/','https://www.npmjs.com/search','https://www.npmjs.com/~','https://registry.npmjs.org/',
'https://pypi.org/search/','https://pypi.org/search/','https://pypi.org/user/','https://pypi.org/project/','https://packagist.org/','https://packagist.org/packages/','https://rubygems.org/','https://rubygems.org/profiles/','https://crates.io/','https://crates.io/users/',
'https://stackoverflow.com/search','https://stackoverflow.com/users','https://stackoverflow.com/search','https://stackexchange.com/','https://stackexchange.com/users','https://stackexchange.com/sites','https://superuser.com/users','https://serverfault.com/users','https://askubuntu.com/users','https://mathoverflow.net/users',
'https://dev.to/','https://dev.to/search','https://dev.to/t/','https://hashnode.com/','https://hashnode.com/explore','https://codepen.io/','https://codepen.io/search/pens','https://replit.com/','https://replit.com/@','https://glitch.com/',
'https://www.kaggle.com/search','https://www.kaggle.com/search','https://www.kaggle.com/datasets','https://www.kaggle.com/code','https://www.kaggle.com/models','https://huggingface.co/','https://huggingface.co/models','https://huggingface.co/datasets','https://huggingface.co/spaces','https://huggingface.co/users',
'https://orcid.org/orcid-search/search','https://orcid.org/orcid-search/search','https://pubmed.ncbi.nlm.nih.gov/','https://pubmed.ncbi.nlm.nih.gov/?term=','https://pmc.ncbi.nlm.nih.gov/','https://arxiv.org/','https://arxiv.org/search/','https://arxiv.org/list/','https://export.arxiv.org/api/query','https://ui.adsabs.harvard.edu/',
'https://scholar.google.com/','https://scholar.google.com/citations','https://www.semanticscholar.org/','https://www.semanticscholar.org/search','https://api.semanticscholar.org/','https://explore.openalex.org/authors/','https://api.openalex.org/authors','https://search.crossref.org/','https://api.crossref.org/',
'https://zenodo.org/','https://zenodo.org/search','https://zenodo.org/communities','https://figshare.com/','https://figshare.com/search','https://osf.io/','https://osf.io/search/','https://dataverse.harvard.edu/','https://dataverse.harvard.edu/dataverse/harvard','https://data.mendeley.com/',
'https://dblp.org/','https://dblp.org/search','https://dblp.org/search/author','https://dblp.org/search/publ','https://search.worldcat.org/','https://viaf.org/','https://isni.org/','https://isni.org/page/search-database/',
'https://www.wikidata.org/wiki/Special:Search','https://www.wikidata.org/wiki/Special:Search','https://query.wikidata.org/','https://en.wikipedia.org/','https://en.wikipedia.org/wiki/Special:Search','https://commons.wikimedia.org/','https://commons.wikimedia.org/wiki/Special:MediaSearch','https://www.wikidata.org/wiki/Wikidata:Data_access','https://www.wikidata.org/wiki/Wikidata:SPARQL_query_service','https://www.wikidata.org/wiki/Wikidata:Main_Page',
'https://www.linkedin.com/search/results/people/','https://www.linkedin.com/search/results/people/','https://www.linkedin.com/search/results/companies/','https://www.linkedin.com/search/results/schools/','https://www.linkedin.com/jobs/','https://www.linkedin.com/company/','https://www.linkedin.com/in/','https://www.linkedin.com/pulse/','https://www.linkedin.com/feed/','https://www.linkedin.com/learning/',
'https://www.researchgate.net/search','https://www.researchgate.net/search','https://www.researchgate.net/profile/','https://www.researchgate.net/publication/','https://www.academia.edu/search','https://www.academia.edu/search','https://independent.academia.edu/','https://www.mendeley.com/','https://www.mendeley.com/search/','https://www.mendeley.com/profiles/',
'https://medium.com/search','https://medium.com/search','https://medium.com/@','https://substack.com/','https://substack.com/search','https://www.tumblr.com/','https://www.tumblr.com/search/','https://wordpress.com/','https://wordpress.com/discover','https://www.blogger.com/',
'https://www.reddit.com/search/','https://www.reddit.com/search/','https://www.reddit.com/user/','https://old.reddit.com/','https://news.ycombinator.com/','https://news.ycombinator.com/user?id=','https://lobste.rs/','https://slashdot.org/','https://slashdot.org/~','https://www.producthunt.com/',
'https://www.youtube.com/results','https://www.youtube.com/results','https://www.youtube.com/@','https://vimeo.com/','https://vimeo.com/search','https://www.twitch.tv/','https://www.twitch.tv/directory','https://soundcloud.com/','https://soundcloud.com/search','https://bandcamp.com/',
'https://www.flickr.com/search/','https://www.flickr.com/search/','https://www.flickr.com/people/','https://www.behance.net/','https://www.behance.net/search/projects','https://dribbble.com/','https://dribbble.com/search','https://www.artstation.com/','https://www.artstation.com/search','https://www.deviantart.com/',
'https://www.pinterest.com/search/','https://www.pinterest.com/search/','https://www.instagram.com/','https://www.threads.com/','https://x.com/','https://bsky.app/','https://mastodon.social/','https://www.tiktok.com/','https://www.snapchat.com/','https://www.facebook.com/',
'https://linktr.ee/','https://about.me/','https://gravatar.com/','https://en.gravatar.com/','https://keybase.io/','https://pastebin.com/','https://www.scribd.com/','https://www.slideshare.net/','https://www.goodreads.com/','https://letterboxd.com/',
'https://www.imdb.com/','https://www.imdb.com/search/name/','https://www.imdb.com/name/','https://www.allmusic.com/','https://www.discogs.com/','https://www.discogs.com/search/','https://musicbrainz.org/','https://musicbrainz.org/search','https://open.spotify.com/',
'https://www.meetup.com/','https://www.meetup.com/find/','https://www.etsy.com/search','https://www.etsy.com/search','https://www.ebay.com/sch/i.html','https://www.ebay.com/sch/i.html','https://www.patreon.com/','https://gumroad.com/','https://www.strava.com/','https://www.strava.com/athletes/',
'https://archive.org/advancedsearch.php','https://archive.org/advancedsearch.php','https://web.archive.org/','https://web.archive.org/web/','https://index.commoncrawl.org/','https://commoncrawl.org/','https://arquivo.pt/','https://arquivo.pt/textsearch','https://timetravel.mementoweb.org/','https://mementoweb.org/',
'https://www.google.com/search','https://www.bing.com/search','https://search.brave.com/search','https://duckduckgo.com/','https://search.yahoo.com/search','https://www.startpage.com/','https://www.mojeek.com/search','https://www.ecosia.org/search','https://www.qwant.com/','https://www.dogpile.com/serp'
];
const urls=[...new Set(roots)].slice(0,200);
if(urls.length!==200) throw new Error(`Pantheon batch 18 expected 200 distinct URLs, got ${urls.length}`);
const cats=(u:string):string[]=>/orcid|pubmed|arxiv|scholar|semantic|openalex|crossref|zenodo|figshare|osf|dblp|worldcat|researchgate|academia/i.test(u)?['publications','education','professional-web','identity-resolution']:/github|gitlab|bitbucket|npmjs|pypi|stackoverflow|kaggle|huggingface|dev\.to|hashnode/i.test(u)?['usernames','internet','professional-web','employment']:['social','usernames','internet','identity-resolution'];
export const PANTHEON_VERIFIED_SOURCES_BATCH_18:PantheonVerifiedSource[]=urls.map((url,i)=>({id:`b18-${String(i+1).padStart(3,'0')}`,name:`Web-footprint source ${i+1}`,url,jurisdiction:'global',categories:cats(url),authority:/orcid\.org|ncbi\.nlm\.nih\.gov/.test(url)?'primary':'secondary',verifiedAt:V}));
