import { Contract, ethers, type providers, type Wallet } from 'ethers';
import logger from '../../../logger.js';
import { pool } from '../runtime/cryptocrawl-runtime-database.js';
import { ghostWalletEngine } from './ghost-wallet-engine.js';
import { ensureGhostWalletGasReserveSchema } from './ghost-wallet-gas-reserve-schema.js';
import { ghostWalletProviderMesh, type GhostWalletChain } from './ghost-wallet-provider-mesh.js';
import { ghostWalletWorkSignal } from './ghost-wallet-work-signal.js';

const CHAIN_IDS: Record<GhostWalletChain, number> = { ethereum: 1, polygon: 137, arbitrum: 42161, optimism: 10, base: 8453, bsc: 56, avalanche: 43114 };
const NATIVE_TOKEN = '0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee';
const ERC20_ABI = ['function balanceOf(address account) view returns (uint256)'];
const MAX_BATCH = 4;
interface TypedObject { type: string; eip712: { types: Record<string, Array<{ name: string; type: string }>>; domain: Record<string, unknown>; message: Record<string, unknown>; primaryType: string } }
interface ReserveRow { reserveId: string; chain: GhostWalletChain; asset: string; amount: bigint; status: string; tradeHash: string | null; result: Record<string, unknown>; attemptCount: number; }
function validHash(value: unknown): value is string { return typeof value === 'string' && /^0x[a-fA-F0-9]{64}$/.test(value); }
function apiKey(): string { const value=process.env.GHOST_WALLET_ZEROX_API_KEY?.trim()||process.env.ZERO_EX_API_KEY?.trim()||process.env.ZEROX_API_KEY?.trim()||''; if(!value)throw new Error('GHOST_WALLET_GAS_RESERVE_ZEROX_CREDENTIALS_UNAVAILABLE'); return value; }
async function zeroEx(path:string,init:RequestInit):Promise<any>{const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),10000);timer.unref?.();try{const response=await fetch(`https://api.0x.org${path}`,{...init,signal:controller.signal,headers:{accept:'application/json','Content-Type':'application/json','0x-api-key':apiKey(),'0x-version':'v2',...(init.headers||{})}});const text=await response.text();const parsed=text?JSON.parse(text):{};if(!response.ok)throw new Error(`GHOST_WALLET_GAS_RESERVE_HTTP_${response.status}:${String(parsed?.message||'').slice(0,240)}`);return parsed;}finally{clearTimeout(timer);}}
function stripDomain(types:TypedObject['eip712']['types']){const{EIP712Domain:_ignored,...rest}=types;return rest;}
async function sign(wallet:Wallet,value:TypedObject):Promise<Record<string,unknown>>{const signature=ethers.utils.splitSignature(await wallet._signTypedData(value.eip712.domain,stripDomain(value.eip712.types),value.eip712.message));return{type:value.type,eip712:value.eip712,signature:{r:signature.r,s:signature.s,v:signature.v,signatureType:2}};}
function extractHashes(value:unknown,key=''):string[]{if(typeof value==='string')return/^(hash|transactionHash|txHash|transaction_hash|tx_hash)$/i.test(key)&&validHash(value)?[value]:[];if(Array.isArray(value))return value.flatMap(item=>extractHashes(item));if(!value||typeof value!=='object')return[];return Object.entries(value as Record<string,unknown>).flatMap(([childKey,child])=>extractHashes(child,childKey));}
function normalizeRow(value:any):ReserveRow{return{reserveId:String(value.reserve_id),chain:String(value.chain)as GhostWalletChain,asset:ethers.utils.getAddress(String(value.asset)),amount:BigInt(String(value.amount_base_units)),status:String(value.status),tradeHash:value.trade_hash?String(value.trade_hash):null,result:value.result&&typeof value.result==='object'?value.result:{},attemptCount:Number(value.attempt_count||0)};}

class GhostWalletGasReserve{
 private running=false;private draining=false;private pending=false;private timer:NodeJS.Timeout|null=null;private unsubscribe:(()=>void)|null=null;private readonly workerId=`ghost-gas-reserve:${process.pid}:${Math.random().toString(36).slice(2)}`;
 async start():Promise<void>{if(this.running)return;await ensureGhostWalletGasReserveSchema();this.running=true;this.unsubscribe=ghostWalletWorkSignal.onWake(()=>this.wake());this.wake();logger.info('[GhostWalletGasReserve] Retained-profit gas replenishment started',{component:'GhostWalletGasReserve',source:'retained_realized_ghost_profit_only',operatorPrincipalAuthority:false,firstTradeBootstrapStillRequiresNativeOrSponsor:true,zeroCapitalDependency:false});}
 stop():void{this.running=false;this.unsubscribe?.();this.unsubscribe=null;if(this.timer)clearTimeout(this.timer);this.timer=null;}
 private wake():void{if(!this.running)return;this.pending=true;if(!this.draining)queueMicrotask(()=>{void this.drain();});}
 private schedule():void{if(!this.running)return;if(this.timer)clearTimeout(this.timer);this.timer=setTimeout(()=>{this.timer=null;this.wake();},15000);this.timer.unref?.();}
 private async hydrate():Promise<void>{await pool.query(`INSERT INTO private.cryptocrawler_ghost_wallet_gas_reserve (reserve_id,source_work_id,chain,asset,amount_base_units) SELECT 'retained:'||work_id,work_id,chain,profit_asset,(payload->>'retainedAmountBaseUnits')::numeric FROM private.cryptocrawler_ghost_wallet_work WHERE kind='profit_conversion' AND profit_asset IS NOT NULL AND payload ? 'retainedAmountBaseUnits' AND (payload->>'retainedAmountBaseUnits') ~ '^[0-9]+$' AND (payload->>'retainedAmountBaseUnits')::numeric > 0 ON CONFLICT (reserve_id) DO NOTHING`);}
 private async claim():Promise<ReserveRow[]>{const result=await pool.query(`WITH c AS (SELECT reserve_id FROM private.cryptocrawler_ghost_wallet_gas_reserve WHERE status IN ('QUEUED','PREPARED','SUBMITTED','RETRYABLE') AND not_before<=now() AND (lease_until IS NULL OR lease_until<now()) AND attempt_count<max_attempts ORDER BY not_before,created_at LIMIT $2 FOR UPDATE SKIP LOCKED) UPDATE private.cryptocrawler_ghost_wallet_gas_reserve r SET lease_owner=$1,lease_until=now()+interval '60 seconds',attempt_count=r.attempt_count+1,updated_at=now() FROM c WHERE r.reserve_id=c.reserve_id RETURNING r.*`,[this.workerId,MAX_BATCH]);return result.rows.map(normalizeRow);}
 private async defer(item:ReserveRow,error:unknown):Promise<void>{const delay=Math.min(60000,1000*(2**Math.min(6,item.attemptCount)));await pool.query(`UPDATE private.cryptocrawler_ghost_wallet_gas_reserve SET status=CASE WHEN attempt_count>=max_attempts THEN 'DEAD' ELSE 'RETRYABLE' END,not_before=now()+($3::bigint*interval '1 millisecond'),lease_owner=NULL,lease_until=NULL,last_error=$4,updated_at=now() WHERE reserve_id=$1 AND lease_owner=$2`,[item.reserveId,this.workerId,delay,(error instanceof Error?error.message:String(error)).slice(0,1000)]);}
 private wallet(chain:GhostWalletChain):Wallet{const value=ghostWalletEngine.getExecutionWallet(chain);if(!value)throw new Error('GHOST_WALLET_GAS_RESERVE_CONTROLLER_WALLET_UNAVAILABLE');return value;}
 private async prepare(item:ReserveRow):Promise<ReserveRow>{const provider=await ghostWalletProviderMesh.getProvider(item.chain);if(!provider)throw new Error(`GHOST_WALLET_GAS_RESERVE_RPC_UNAVAILABLE:${item.chain}`);const wallet=this.wallet(item.chain).connect(provider);const token=new Contract(item.asset,ERC20_ABI,provider);const[tokenBefore,nativeBefore]=await Promise.all([token.balanceOf(wallet.address),provider.getBalance(wallet.address)]);if(BigInt(tokenBefore.toString())<item.amount)throw new Error('GHOST_WALLET_GAS_RESERVE_RETAINED_TOKEN_UNAVAILABLE');const params=new URLSearchParams({chainId:String(CHAIN_IDS[item.chain]),sellToken:item.asset,buyToken:NATIVE_TOKEN,sellAmount:item.amount.toString(),taker:wallet.address});const quote=await zeroEx(`/gasless/quote?${params}`,{method:'GET'});if(!quote?.liquidityAvailable||!quote?.trade)throw new Error('GHOST_WALLET_GAS_RESERVE_GASLESS_LIQUIDITY_UNAVAILABLE');if(quote?.issues?.allowance!=null&&!quote?.approval)throw new Error('GHOST_WALLET_GAS_RESERVE_APPROVAL_UNAVAILABLE');const trade=await sign(wallet,quote.trade as TypedObject);const approval=quote.approval?await sign(wallet,quote.approval as TypedObject):undefined;const minimum=BigInt(String(quote.minBuyAmount||quote.buyAmount||'0'));if(minimum<=0n)throw new Error('GHOST_WALLET_GAS_RESERVE_NATIVE_OUTPUT_INVALID');const saved=await pool.query(`UPDATE private.cryptocrawler_ghost_wallet_gas_reserve SET status='PREPARED',result=$3::jsonb,updated_at=now() WHERE reserve_id=$1 AND lease_owner=$2 RETURNING *`,[item.reserveId,this.workerId,JSON.stringify({phase:'gas_reserve_signed_before_submit',chain:item.chain,chainId:CHAIN_IDS[item.chain],asset:item.asset,amountBaseUnits:item.amount.toString(),tokenBalanceBefore:tokenBefore.toString(),nativeBalanceBeforeWei:nativeBefore.toString(),minimumNativeWei:minimum.toString(),trade,...(approval?{approval}:{}),gasFundingAuthority:'retained_realized_ghost_profit_only',operatorMonetaryInputRequired:false})]);if(!saved.rows[0])throw new Error('GHOST_WALLET_GAS_RESERVE_PREPARE_LEASE_LOST');return normalizeRow(saved.rows[0]);}
 private async submit(item:ReserveRow):Promise<ReserveRow>{const submitted=await zeroEx('/gasless/submit',{method:'POST',body:JSON.stringify({trade:item.result.trade,chainId:CHAIN_IDS[item.chain],...(item.result.approval?{approval:item.result.approval}:{})})});const hash=String(submitted?.tradeHash||'');if(!validHash(hash))throw new Error('GHOST_WALLET_GAS_RESERVE_TRADE_HASH_INVALID');const saved=await pool.query(`UPDATE private.cryptocrawler_ghost_wallet_gas_reserve SET status='SUBMITTED',trade_hash=$3,submitted_at=COALESCE(submitted_at,now()),updated_at=now() WHERE reserve_id=$1 AND lease_owner=$2 RETURNING *`,[item.reserveId,this.workerId,hash]);if(!saved.rows[0])throw new Error('GHOST_WALLET_GAS_RESERVE_SUBMIT_LEASE_LOST');return normalizeRow(saved.rows[0]);}
 private async reconcile(item:ReserveRow):Promise<boolean>{if(!item.tradeHash)return false;const status=await zeroEx(`/gasless/status/${item.tradeHash}?chainId=${CHAIN_IDS[item.chain]}`,{method:'GET'});const state=String(status?.status||'').toLowerCase();if(['failed','reverted','cancelled','canceled','expired'].includes(state))throw new Error(`GHOST_WALLET_GAS_RESERVE_TERMINAL_${state}`);const provider=await ghostWalletProviderMesh.getProvider(item.chain);if(!provider)throw new Error(`GHOST_WALLET_GAS_RESERVE_RPC_UNAVAILABLE:${item.chain}`);let receipt:providers.TransactionReceipt|null=null;for(const hash of Array.from(new Set(extractHashes(status)))){const candidate=await provider.getTransactionReceipt(hash).catch(()=>null);if(candidate?.status===0)throw new Error('GHOST_WALLET_GAS_RESERVE_TRANSACTION_REVERTED');if(candidate?.status===1){receipt=candidate;break;}}if(!receipt)return false;const wallet=this.wallet(item.chain).connect(provider);const tokenAfter=await new Contract(item.asset,ERC20_ABI,provider).balanceOf(wallet.address);const before=BigInt(String(item.result.tokenBalanceBefore||'0'));const after=BigInt(tokenAfter.toString());if(after>before||before-after<item.amount)throw new Error('GHOST_WALLET_GAS_RESERVE_SOURCE_SPEND_NOT_VERIFIED');const nativeAfter=await provider.getBalance(wallet.address);await pool.query(`UPDATE private.cryptocrawler_ghost_wallet_gas_reserve SET status='SETTLED',settlement_transaction_hash=$3,settled_at=now(),lease_owner=NULL,lease_until=NULL,result=result||$4::jsonb,last_error=NULL,updated_at=now() WHERE reserve_id=$1 AND lease_owner=$2`,[item.reserveId,this.workerId,receipt.transactionHash,JSON.stringify({phase:'gas_reserve_native_acquired',settlementTransactionHash:receipt.transactionHash,nativeBalanceAfterWei:nativeAfter.toString(),retainedProfitSpentBaseUnits:item.amount.toString(),controllerNativeGasAvailable:BigInt(nativeAfter.toString())>0n})]);return true;}
 private async process(item:ReserveRow):Promise<void>{try{let current=item;if(current.status==='QUEUED'||current.status==='RETRYABLE')current=await this.prepare(current);if(current.status==='PREPARED')current=await this.submit(current);if(current.status==='SUBMITTED'&&!(await this.reconcile(current))){await pool.query(`UPDATE private.cryptocrawler_ghost_wallet_gas_reserve SET lease_owner=NULL,lease_until=NULL,not_before=now()+interval '2 seconds',updated_at=now() WHERE reserve_id=$1 AND lease_owner=$2`,[current.reserveId,this.workerId]);}}catch(error){await this.defer(item,error).catch(()=>undefined);}}
 private async drain():Promise<void>{if(!this.running||this.draining)return;this.draining=true;try{do{this.pending=false;await this.hydrate();const batch=await this.claim();await Promise.allSettled(batch.map(item=>this.process(item)));if(batch.length===MAX_BATCH)this.pending=true;}while(this.running&&this.pending);}catch(error){logger.debug('[GhostWalletGasReserve] Reserve replenishment degraded locally',{component:'GhostWalletGasReserve',error:error instanceof Error?error.message:String(error),routeLocalFailure:true});}finally{this.draining=false;this.schedule();}}
}
export const ghostWalletGasReserve=new GhostWalletGasReserve();
export const GHOST_WALLET_GAS_RESERVE_POLICY={sourceAuthority:'retained_realized_ghost_profit_only',retainedPercent:10,operatorPrincipalAllowed:false,zeroCapitalDependency:false,sameChainNativeReserve:true,gaslessConversionPreferred:true,signedPayloadPersistedBeforeRelaySubmission:true,firstTradeBootstrapRequiresExistingNativeOrOptionalSponsor:true,sponsorIsMandatoryDependency:false,perChainFailureLocal:true} as const;