import WebSocket from 'ws';
import logger from '../../../logger.js';
import {
  createCoinbaseWebSocketJwt,
  hasCoinbaseAdvancedTradeCredentials,
} from './coinbase-advanced-trade-authority.js';
import { consumePrivateCexExecutionFrame } from './cex-private-execution-feedback.js';

const CONNECT_TIMEOUT_MS = boundedInt(process.env.CRYPTO_COINBASE_PRIVATE_WS_CONNECT_TIMEOUT_MS, 5_000, 1_000, 15_000);
const RECONNECT_MIN_MS = boundedInt(process.env.CRYPTO_COINBASE_PRIVATE_WS_RECONNECT_MIN_MS, 1_000, 250, 30_000);
const RECONNECT_MAX_MS = boundedInt(process.env.CRYPTO_COINBASE_PRIVATE_WS_RECONNECT_MAX_MS, 30_000, RECONNECT_MIN_MS, 120_000);

let socket: WebSocket | null = null;
let readyPromise: Promise<void> | null = null;
let reconnectTimer: NodeJS.Timeout | null = null;
let reconnectAttempt = 0;
let lastMessageAt: number | null = null;
let lastConnectedAt: number | null = null;
let lastError: string | null = null;
let permanentlyDisabled = false;

function boundedInt(raw: unknown, fallback: number, min: number, max: number): number {
  const parsed = Number(raw);
  return Number.isFinite(parsed) ? Math.max(min, Math.min(max, Math.trunc(parsed))) : fallback;
}

function enabled(): boolean {
  return !permanentlyDisabled
    && process.env.CRYPTO_COINBASE_PRIVATE_WS_FEEDBACK_ENABLED?.trim().toLowerCase() !== 'false'
    && hasCoinbaseAdvancedTradeCredentials();
}

function endpoint(): string {
  const configured = process.env.COINBASE_ADVANCED_USER_WS_URL?.trim();
  if (!configured) return 'wss://advanced-trade-ws-user.coinbase.com';
  if (!/^wss:\/\//i.test(configured)) throw new Error('COINBASE_ADVANCED_USER_WS_URL must be a wss:// URL');
  return configured;
}

function reconnectDelayMs(): number {
  const ceiling = Math.min(RECONNECT_MAX_MS, RECONNECT_MIN_MS * (2 ** Math.min(8, reconnectAttempt)));
  return Math.max(RECONNECT_MIN_MS, Math.floor(Math.random() * Math.max(RECONNECT_MIN_MS + 1, ceiling)));
}

function scheduleReconnect(): void {
  if (!enabled() || reconnectTimer) return;
  reconnectAttempt += 1;
  const delayMs = reconnectDelayMs();
  reconnectTimer = setTimeout(() => {
    reconnectTimer = null;
    void ensureCoinbasePrivateExecutionFeedback().catch(() => undefined);
  }, delayMs);
  reconnectTimer.unref?.();
}

function cleanupSocket(target: WebSocket): void {
  if (target !== socket) return;
  socket = null;
  scheduleReconnect();
}

async function open(): Promise<void> {
  if (!enabled()) return;
  const target = new WebSocket(endpoint(), {
    perMessageDeflate: false,
    handshakeTimeout: CONNECT_TIMEOUT_MS,
    maxPayload: 1024 * 1024,
  });

  await new Promise<void>((resolve, reject) => {
    const timeout = setTimeout(() => {
      cleanup();
      target.terminate();
      reject(new Error(`Coinbase user WebSocket connection timed out after ${CONNECT_TIMEOUT_MS}ms`));
    }, CONNECT_TIMEOUT_MS);
    timeout.unref?.();
    const onOpen = () => { cleanup(); resolve(); };
    const onError = (error: Error) => { cleanup(); reject(error); };
    const cleanup = () => {
      clearTimeout(timeout);
      target.off('open', onOpen);
      target.off('error', onError);
    };
    target.once('open', onOpen);
    target.once('error', onError);
  });

  if (!enabled()) {
    target.close();
    return;
  }

  socket = target;
  reconnectAttempt = 0;
  lastConnectedAt = Date.now();
  lastError = null;

  // Coinbase requires a subscription promptly after connect. Each channel uses a
  // distinct message; user auth is generated by the existing canonical Coinbase
  // credential/signing authority and never creates a second signer.
  target.send(JSON.stringify({
    type: 'subscribe',
    channel: 'heartbeats',
    jwt: createCoinbaseWebSocketJwt(),
  }));
  target.send(JSON.stringify({
    type: 'subscribe',
    channel: 'user',
    jwt: createCoinbaseWebSocketJwt(),
  }));

  target.on('message', data => {
    lastMessageAt = Date.now();
    let payload: Record<string, any>;
    try {
      payload = JSON.parse(data.toString());
    } catch {
      return;
    }
    if (payload.type === 'error') {
      lastError = String(payload.message || payload.reason || 'Coinbase user WebSocket error');
      logger.debug('[Coinbase Private WS] user-stream error frame received', {
        component: 'CoinbasePrivateExecutionFeedback',
        error: lastError,
        executionAuthority: false,
        settlementAuthority: false,
        economicBpsAuthority: false,
      });
      return;
    }
    consumePrivateCexExecutionFrame('coinbase', payload);
  });

  target.on('error', error => {
    lastError = error.message;
    logger.debug('[Coinbase Private WS] read-only execution feedback degraded', {
      component: 'CoinbasePrivateExecutionFeedback',
      error: error.message,
      executionAuthority: false,
      settlementAuthority: false,
      economicBpsAuthority: false,
    });
  });

  target.on('close', () => cleanupSocket(target));

  logger.info('[Coinbase Private WS] authenticated user-order feedback ready', {
    component: 'CoinbasePrivateExecutionFeedback',
    role: 'read_only_execution_state_feedback',
    submissionAuthority: 'existing_rest_settlement_adapter_only',
    signerAuthority: 'coinbase_advanced_trade_authority_only',
    executionAuthority: false,
    settlementAuthority: false,
    economicBpsAuthority: false,
  });
}

/**
 * Lazily starts Coinbase's authenticated user-order WebSocket only after the
 * process has tracked a concrete Coinbase submission. REST remains the canonical
 * submission and terminal-settlement authority; this stream only accelerates
 * fill/state awareness and exact-symbol BPS revalidation.
 */
export async function ensureCoinbasePrivateExecutionFeedback(): Promise<void> {
  if (!enabled()) return;
  if (socket?.readyState === WebSocket.OPEN) return;
  if (readyPromise) return readyPromise;
  readyPromise = open()
    .catch(error => {
      lastError = error instanceof Error ? error.message : String(error);
      scheduleReconnect();
      throw error;
    })
    .finally(() => { readyPromise = null; });
  return readyPromise;
}

export function disableCoinbasePrivateExecutionFeedback(): void {
  permanentlyDisabled = true;
  if (reconnectTimer) clearTimeout(reconnectTimer);
  reconnectTimer = null;
  const current = socket;
  socket = null;
  if (current && current.readyState < WebSocket.CLOSING) current.close();
}

export function getCoinbasePrivateExecutionFeedbackStatus() {
  return {
    observedAt: Date.now(),
    enabled: enabled(),
    connected: socket?.readyState === WebSocket.OPEN,
    reconnectAttempt,
    lastConnectedAt,
    lastMessageAt,
    lastError,
    endpoint: endpoint(),
    subscriptionChannels: ['heartbeats', 'user'] as const,
    submissionAuthority: 'existing_rest_settlement_adapter_only' as const,
    signerAuthority: 'coinbase_advanced_trade_authority_only' as const,
    executionAuthority: false as const,
    settlementAuthority: false as const,
    economicBpsAuthority: false as const,
  };
}
