export type SpectraAdapterMode =
  | 'live-telemetry'
  | 'provider-webhook'
  | 'radio-resolution'
  | 'ranging'
  | 'media'
  | 'camera'
  | 'street-imagery'
  | 'geocoder'
  | 'place-context'
  | 'weather'
  | 'earth-observation'
  | 'archive'
  | 'public-record'
  | 'generic-http';

export interface SpectraAdapterCapability {
  id: string;
  label: string;
  mode: SpectraAdapterMode;
  sourceTypes: string[];
  configured: () => boolean;
  priority: 'critical' | 'high' | 'supporting';
  supportsRealtime: boolean;
  notes: string;
}

const anyEnv = (...names: string[]) =>
  names.some(name => Boolean(String(process.env[name] || '').trim()));

export const SPECTRA_ADAPTER_CAPABILITIES: SpectraAdapterCapability[] = [
  {
    id: 'browser-geolocation',
    label: 'Browser geolocation stream',
    mode: 'live-telemetry',
    sourceTypes: ['browser_geolocation'],
    configured: () => true,
    priority: 'critical',
    supportsRealtime: true,
    notes: 'Client watchPosition observations are normalized and fused server-side.',
  },
  {
    id: 'signed-provider-webhook',
    label: 'Signed telemetry provider webhook',
    mode: 'provider-webhook',
    sourceTypes: [
      'device_gps','gnss_fix','gnss_raw','vehicle_telemetry',
      'visual_detection','network_region',
      'wifi_fingerprint','cellular','wifi_rtt','wifi_rssi','uwb_range','uwb_direction',
      'bluetooth_proximity','bluetooth_channel_sounding','ble_rssi','ble_aoa','ble_aod',
      'accelerometer','imu_gyro','magnetometer','barometer',
    ],
    configured: () => anyEnv('SPECTRA_TELEMETRY_HMAC_SECRET'),
    priority: 'critical',
    supportsRealtime: true,
    notes: 'Generic adapter for external live telemetry feeds that can POST normalized measurements.',
  },
  {
    id: 'camara-location-retrieval-ingest',
    label: 'CAMARA / GSMA network-location ingest',
    mode: 'provider-webhook',
    sourceTypes: ['network_region'],
    configured: () => anyEnv('SPECTRA_TELEMETRY_HMAC_SECRET'),
    priority: 'critical',
    supportsRealtime: true,
    notes: 'Normalizes signed CAMARA Device Location Retrieval responses into the canonical SPECTRA location pipeline.',
  },
  {
    id: 'bluetooth-scanner-ingest',
    label: 'Bluetooth scanner telemetry ingest',
    mode: 'provider-webhook',
    sourceTypes: ['bluetooth_proximity', 'ble_rssi', 'ble_aoa'],
    configured: () => anyEnv('SPECTRA_TELEMETRY_HMAC_SECRET'),
    priority: 'critical',
    supportsRealtime: true,
    notes: 'Normalizes signed BLE scanner/ranging observations into the existing multilateration path.',
  },
  {
    id: 'accessory-network-ingest',
    label: 'Accessory-network location ingest',
    mode: 'provider-webhook',
    sourceTypes: ['network_region', 'bluetooth_proximity', 'ble_rssi'],
    configured: () => anyEnv('SPECTRA_TELEMETRY_HMAC_SECRET'),
    priority: 'high',
    supportsRealtime: true,
    notes: 'Provider-neutral bridge for partner/exported accessory-network observations, including Find My / Find Hub compatible upstream feeds.',
  },
  {
    id: 'bluetooth-channel-sounding-ingest',
    label: 'Bluetooth Channel Sounding ingest',
    mode: 'provider-webhook',
    sourceTypes: ['bluetooth_channel_sounding','bluetooth_proximity'],
    configured: () => anyEnv('SPECTRA_TELEMETRY_HMAC_SECRET'),
    priority: 'critical',
    supportsRealtime: true,
    notes: 'Normalizes Bluetooth 6 Channel Sounding PBR/RTT distance measurements into canonical ranging evidence.',
  },
  {
    id: 'ble-direction-finding-ingest',
    label: 'BLE AoA/AoD direction ingest',
    mode: 'provider-webhook',
    sourceTypes: ['ble_aoa','ble_aod','bluetooth_proximity'],
    configured: () => anyEnv('SPECTRA_TELEMETRY_HMAC_SECRET'),
    priority: 'critical',
    supportsRealtime: true,
    notes: 'Preserves AoA/AoD direction, antenna-array and bearing-reference measurements; qualified geometry enters ranging fusion.',
  },
  {
    id: 'android-wifi-ranging-ingest',
    label: 'Android Wi-Fi RTT / 802.11az ingest',
    mode: 'provider-webhook',
    sourceTypes: ['wifi_rtt','wifi_fingerprint'],
    configured: () => anyEnv('SPECTRA_TELEMETRY_HMAC_SECRET'),
    priority: 'critical',
    supportsRealtime: true,
    notes: 'Normalizes 802.11mc/802.11az NTB, responder-location and Wi-Fi Aware ranging observations.',
  },
  {
    id: 'android-cellular-measurements-ingest',
    label: 'Android rich cellular measurements ingest',
    mode: 'provider-webhook',
    sourceTypes: ['cellular','cell_serving','cell_neighbor'],
    configured: () => anyEnv('SPECTRA_TELEMETRY_HMAC_SECRET'),
    priority: 'critical',
    supportsRealtime: true,
    notes: 'Preserves GSM/WCDMA/LTE/NR identifiers and rich signal metrics before radio-position resolution.',
  },
  {
    id: 'android-raw-gnss-ingest',
    label: 'Android raw GNSS ingest',
    mode: 'provider-webhook',
    sourceTypes: ['gnss_raw','gnss_fix'],
    configured: () => anyEnv('SPECTRA_TELEMETRY_HMAC_SECRET'),
    priority: 'critical',
    supportsRealtime: true,
    notes: 'Preserves GNSS clock, pseudorange/rate, ADR/carrier-frequency and C/N0 metadata; supplied fixes enter canonical fusion.',
  },
  {
    id: 'apple-nearby-interaction-ingest',
    label: 'Apple Nearby Interaction ingest',
    mode: 'provider-webhook',
    sourceTypes: ['uwb_range','uwb_direction','bluetooth_proximity'],
    configured: () => anyEnv('SPECTRA_TELEMETRY_HMAC_SECRET'),
    priority: 'critical',
    supportsRealtime: true,
    notes: 'Normalizes Nearby Interaction UWB, EDM, DL-TDOA and Bluetooth Channel Sounding observations.',
  },
  {
    id: 'android-radio-collector-ingest',
    label: 'Android multi-radio collector ingest',
    mode: 'provider-webhook',
    sourceTypes: ['cellular','gnss_raw','gnss_fix','wifi_rtt','bluetooth_proximity','bluetooth_channel_sounding','ble_rssi','ble_aoa','ble_aod'],
    configured: () => anyEnv('SPECTRA_TELEMETRY_HMAC_SECRET'),
    priority: 'critical',
    supportsRealtime: true,
    notes: 'One signed collector envelope can carry cellular, GNSS, Wi-Fi RTT and Bluetooth observations into the same telemetry batch.',
  },
  {
    id: 'ble-gateway-ingest',
    label: 'Universal BLE gateway ingest',
    mode: 'provider-webhook',
    sourceTypes: ['ble_rssi','ble_aoa','ble_aod','bluetooth_proximity','bluetooth_channel_sounding'],
    configured: () => anyEnv('SPECTRA_TELEMETRY_HMAC_SECRET'),
    priority: 'high',
    supportsRealtime: true,
    notes: 'Provider-neutral normalization for BlueZ, ESP32, Android scanners and commercial BLE/AoA gateway observations.',
  },
  {
    id: 'lorawan-observation-ingest',
    label: 'LoRa/LoRaWAN observation ingest',
    mode: 'provider-webhook',
    sourceTypes: ['network_region'],
    configured: () => anyEnv('SPECTRA_TELEMETRY_HMAC_SECRET'),
    priority: 'supporting',
    supportsRealtime: true,
    notes: 'Preserves gateway RSSI/SNR/TOA context and normalizes supplied LoRa geolocation solver results.',
  },
  {
    id: 'universal-radio-log-ingest',
    label: 'Universal radio-log ingest',
    mode: 'provider-webhook',
    sourceTypes: ['cellular','gnss_raw','wifi_rtt','bluetooth_proximity','bluetooth_channel_sounding','ble_rssi','ble_aoa','ble_aod','uwb_range','uwb_direction'],
    configured: () => anyEnv('SPECTRA_TELEMETRY_HMAC_SECRET'),
    priority: 'high',
    supportsRealtime: false,
    notes: 'Detects structured Android/modem/BLE/Wi-Fi/GNSS/LoRa records and routes them through the same canonical normalizers.',
  },
  {
    id: 'camara-location-verification-ingest',
    label: 'CAMARA location verification ingest',
    mode: 'provider-webhook',
    sourceTypes: ['network_region'],
    configured: () => anyEnv('SPECTRA_TELEMETRY_HMAC_SECRET'),
    priority: 'high',
    supportsRealtime: true,
    notes: 'Stores carrier verification results as corroborating telemetry context without fabricating a coordinate.',
  },
  {
    id: 'camara-reachability-ingest',
    label: 'CAMARA device reachability ingest',
    mode: 'provider-webhook',
    sourceTypes: ['network_region'],
    configured: () => anyEnv('SPECTRA_TELEMETRY_HMAC_SECRET'),
    priority: 'supporting',
    supportsRealtime: true,
    notes: 'Stores current carrier reachability state and freshness alongside location evidence.',
  },
  {
    id: 'android-managed-lost-mode-ingest',
    label: 'Android managed Lost Mode ingest',
    mode: 'provider-webhook',
    sourceTypes: ['device_gps'],
    configured: () => anyEnv('SPECTRA_TELEMETRY_HMAC_SECRET'),
    priority: 'critical',
    supportsRealtime: true,
    notes: 'Normalizes Android Management API LostModeLocationEvent usage-log updates supplied by an enterprise management backend.',
  },
  {
    id: 'apple-managed-lost-mode-ingest',
    label: 'Apple Managed Lost Mode ingest',
    mode: 'provider-webhook',
    sourceTypes: ['device_gps'],
    configured: () => anyEnv('SPECTRA_TELEMETRY_HMAC_SECRET'),
    priority: 'critical',
    supportsRealtime: true,
    notes: 'Normalizes supervised-device DeviceLocation responses supplied by an MDM backend.',
  },
  {
    id: 'meraki-scanning-ingest',
    label: 'Cisco Meraki Scanning API ingest',
    mode: 'provider-webhook',
    sourceTypes: ['wifi_fingerprint','bluetooth_proximity'],
    configured: () => anyEnv('SPECTRA_TELEMETRY_HMAC_SECRET'),
    priority: 'high',
    supportsRealtime: true,
    notes: 'Normalizes Meraki Wi-Fi/BLE location observations, floor-plan context and RSSI records.',
  },
  {
    id: 'cisco-spaces-location-ingest',
    label: 'Cisco Spaces location firehose ingest',
    mode: 'provider-webhook',
    sourceTypes: ['wifi_fingerprint'],
    configured: () => anyEnv('SPECTRA_TELEMETRY_HMAC_SECRET'),
    priority: 'high',
    supportsRealtime: true,
    notes: 'Normalizes DEVICE_LOCATION_UPDATE events and map/location identifiers from Cisco Spaces.',
  },
  {
    id: 'aws-iot-device-location-ingest',
    label: 'AWS IoT Device Location ingest',
    mode: 'provider-webhook',
    sourceTypes: ['gnss_fix','wifi_fingerprint','cellular','bluetooth_proximity','network_region'],
    configured: () => anyEnv('SPECTRA_TELEMETRY_HMAC_SECRET'),
    priority: 'high',
    supportsRealtime: true,
    notes: 'Normalizes AWS IoT GeoJSON positions with measurement type, horizontal/vertical accuracy and resolver timestamp.',
  },
  {
    id: 'connected-vehicle-location-ingest',
    label: 'Connected vehicle location ingest',
    mode: 'provider-webhook',
    sourceTypes: ['vehicle_telemetry'],
    configured: () => anyEnv('SPECTRA_TELEMETRY_HMAC_SECRET'),
    priority: 'high',
    supportsRealtime: true,
    notes: 'Provider-neutral bridge for fresh vehicle GPS/telemetry positions such as fleet API streams.',
  },
  {
    id: 'generic-https-json-pull',
    label: 'Configured HTTPS JSON telemetry pull',
    mode: 'live-telemetry',
    sourceTypes: [
      'device_gps','gnss_fix','vehicle_telemetry','social_geotag',
      'public_camera','traffic_cam','historical_location','public_record',
    ],
    configured: () => {
      try {
        const configured = JSON.parse(String(process.env.SPECTRA_GENERIC_JSON_ADAPTERS || '[]'));
        return Array.isArray(configured) && configured.length > 0;
      } catch {
        return false;
      }
    },
    priority: 'high',
    supportsRealtime: true,
    notes: 'Fixed HTTPS pull adapters normalize provider JSON into SPECTRA observations.',
  },
  {
    id: 'beacondb-radio-geolocation',
    label: 'beaconDB radio geolocation',
    mode: 'radio-resolution',
    sourceTypes: ['wifi_fingerprint','cellular'],
    configured: () => true,
    priority: 'high',
    supportsRealtime: true,
    notes: 'Keyless Ichnaea-compatible Wi-Fi/cellular positioning fallback for supplied radio observations.',
  },
  {
    id: 'google-radio-geolocation',
    label: 'Google radio geolocation',
    mode: 'radio-resolution',
    sourceTypes: ['wifi_fingerprint','cellular'],
    configured: () => anyEnv(
      'SPECTRA_GOOGLE_GEOLOCATION_API_KEY',
      'GOOGLE_GEOLOCATION_API_KEY',
      'GOOGLE_MAPS_API_KEY',
    ),
    priority: 'critical',
    supportsRealtime: true,
    notes: 'Resolves supplied Wi-Fi/cellular observations into coordinates and an accuracy radius.',
  },
  {
    id: 'opencellid',
    label: 'OpenCellID cell-position fallback',
    mode: 'radio-resolution',
    sourceTypes: ['cellular','cell_serving','cell_neighbor'],
    configured: () => anyEnv('OPENCELLID_API_KEY'),
    priority: 'high',
    supportsRealtime: true,
    notes: 'Independent cell-position lookup when network identifiers are available.',
  },
  {
    id: 'multilateration',
    label: 'SPECTRA multilateration',
    mode: 'ranging',
    sourceTypes: ['wifi_rtt','wifi_rssi','uwb_range','uwb_direction','bluetooth_proximity','bluetooth_channel_sounding','ble_rssi','ble_aoa','ble_aod'],
    configured: () => true,
    priority: 'critical',
    supportsRealtime: true,
    notes: 'Uses three or more range anchors for multilateration, or absolute true-north directional anchors when available, with measurement uncertainty.',
  },
  {
    id: 'structured-telemetry-import',
    label: 'Structured telemetry import',
    mode: 'live-telemetry',
    sourceTypes: ['device_gps','gnss_fix','vehicle_telemetry','social_geotag','historical_location','public_record'],
    configured: () => true,
    priority: 'high',
    supportsRealtime: false,
    notes: 'Imports timestamped GeoJSON, GPX, KML, NMEA, CSV and NDJSON location observations.',
  },
  {
    id: 'media-metadata',
    label: 'Media metadata extraction',
    mode: 'media',
    sourceTypes: ['exif_photo','exif_video','xmp_sidecar','json_sidecar'],
    configured: () => true,
    priority: 'critical',
    supportsRealtime: false,
    notes: 'EXIF/XMP/IPTC/QuickTime metadata and embedded coordinates/timestamps.',
  },
  {
    id: 'wikimedia-geosearch',
    label: 'Wikimedia geotagged media',
    mode: 'media',
    sourceTypes: ['social_geotag'],
    configured: () => true,
    priority: 'supporting',
    supportsRealtime: false,
    notes: 'Nearby geotagged media context.',
  },
  {
    id: 'flickr-geosearch',
    label: 'Flickr geotagged media',
    mode: 'media',
    sourceTypes: ['social_geotag'],
    configured: () => anyEnv('FLICKR_API_KEY'),
    priority: 'supporting',
    supportsRealtime: false,
    notes: 'Nearby public photo metadata when Flickr is configured.',
  },
  {
    id: 'kartaview',
    label: 'KartaView street imagery',
    mode: 'street-imagery',
    sourceTypes: ['visual_detection'],
    configured: () => true,
    priority: 'supporting',
    supportsRealtime: false,
    notes: 'Nearby geotagged street imagery, capture time and directional context.',
  },
  {
    id: 'external-camera-json',
    label: 'Configured external camera directory',
    mode: 'camera',
    sourceTypes: ['traffic_cam','public_camera'],
    configured: () => {
      try {
        const feeds = JSON.parse(String(process.env.SPECTRA_CAMERA_JSON_FEEDS || '[]'));
        return Array.isArray(feeds) && feeds.length > 0;
      } catch {
        return false;
      }
    },
    priority: 'high',
    supportsRealtime: true,
    notes: 'Provider-neutral camera directory adapter for configured JSON feeds with geospatial field mappings.',
  },
  {
    id: 'trafficland',
    label: 'TrafficLand camera network',
    mode: 'camera',
    sourceTypes: ['traffic_cam','public_camera'],
    configured: () =>
      Boolean(String(process.env.TRAFFICLAND_API_KEY || '').trim())
      && Boolean(String(process.env.TRAFFICLAND_SYSTEM || '').trim()),
    priority: 'high',
    supportsRealtime: true,
    notes: 'Nationwide camera metadata/images where the configured account has coverage.',
  },
  {
    id: 'arcgis-camera-feeds',
    label: 'Configured ArcGIS/511 camera feeds',
    mode: 'camera',
    sourceTypes: ['traffic_cam','public_camera'],
    configured: () => anyEnv('SPECTRA_CAMERA_ARCGIS_FEEDS'),
    priority: 'high',
    supportsRealtime: true,
    notes: 'State/local DOT and 511 camera layers registered through configuration.',
  },
  {
    id: 'nominatim',
    label: 'OpenStreetMap Nominatim',
    mode: 'geocoder',
    sourceTypes: ['historical_location','public_record'],
    configured: () => true,
    priority: 'high',
    supportsRealtime: false,
    notes: 'Address/place search and regional candidate resolution.',
  },
  {
    id: 'census-geocoder',
    label: 'US Census Geocoder',
    mode: 'geocoder',
    sourceTypes: ['historical_location','public_record'],
    configured: () => true,
    priority: 'high',
    supportsRealtime: false,
    notes: 'Independent U.S. address fallback.',
  },
  {
    id: 'overpass-place-context',
    label: 'OpenStreetMap Overpass place context',
    mode: 'place-context',
    sourceTypes: ['historical_location','public_record'],
    configured: () => true,
    priority: 'supporting',
    supportsRealtime: false,
    notes: 'Nearby named places, roads, businesses and landmarks around a candidate location.',
  },
  {
    id: 'geonames-place-context',
    label: 'GeoNames place context',
    mode: 'place-context',
    sourceTypes: ['historical_location','public_record'],
    configured: () => anyEnv('GEONAMES_USERNAME'),
    priority: 'supporting',
    supportsRealtime: false,
    notes: 'Independent nearby toponym and administrative-place context.',
  },
  {
    id: 'nws',
    label: 'National Weather Service observations',
    mode: 'weather',
    sourceTypes: ['public_record'],
    configured: () => true,
    priority: 'supporting',
    supportsRealtime: true,
    notes: 'Time/place corroboration using nearby official weather observations.',
  },
  {
    id: 'copernicus-stac',
    label: 'Copernicus STAC',
    mode: 'earth-observation',
    sourceTypes: ['satellite_imagery'],
    configured: () => true,
    priority: 'supporting',
    supportsRealtime: false,
    notes: 'Spatiotemporal Earth-observation catalogue context.',
  },
  {
    id: 'aggregate-camera-motion-context',
    label: 'Aggregate camera motion context',
    mode: 'camera',
    sourceTypes: ['traffic_cam','public_camera'],
    configured: () => true,
    priority: 'supporting',
    supportsRealtime: true,
    notes: 'Accepts bounded aggregate traffic counts, speeds, headings and congestion context without promoting scene traffic into a target location observation.',
  },
  {
    id: 'public-source-retrieval',
    label: 'Direct public source retrieval',
    mode: 'generic-http',
    sourceTypes: ['historical_location','public_record','social_geotag'],
    configured: () => true,
    priority: 'high',
    supportsRealtime: false,
    notes: 'Fetches bounded direct source pages/JSON and extracts explicit geospatial metadata before evidence admission.',
  },
  {
    id: 'common-crawl',
    label: 'Common Crawl archive index',
    mode: 'archive',
    sourceTypes: ['historical_location','public_record'],
    configured: () => true,
    priority: 'supporting',
    supportsRealtime: false,
    notes: 'Historical URL discovery used only as discovery; underlying captures remain separate evidence.',
  },
];

export function getSpectraAdapterCapabilities() {
  return SPECTRA_ADAPTER_CAPABILITIES.map(adapter => ({
    id: adapter.id,
    label: adapter.label,
    mode: adapter.mode,
    sourceTypes: adapter.sourceTypes,
    configured: adapter.configured(),
    priority: adapter.priority,
    supportsRealtime: adapter.supportsRealtime,
    notes: adapter.notes,
  }));
}
