export type SpectraAdapterMode =
  | 'live-telemetry'
  | 'provider-webhook'
  | 'provider-pull'
  | 'anchor-resolution'
  | 'radio-resolution'
  | 'ranging'
  | 'media'
  | 'camera'
  | 'street-imagery'
  | 'geocoder'
  | 'place-context'
  | 'weather'
  | 'earth-observation'
  | 'archive'
  | 'public-record'
  | 'generic-http';

export interface SpectraAdapterCapability {
  id: string;
  label: string;
  mode: SpectraAdapterMode;
  sourceTypes: string[];
  configured: () => boolean;
  priority: 'critical' | 'high' | 'supporting';
  supportsRealtime: boolean;
  notes: string;
}

const anyEnv = (...names: string[]) =>
  names.some(name => Boolean(String(process.env[name] || '').trim()));

export const SPECTRA_ADAPTER_CAPABILITIES: SpectraAdapterCapability[] = [
  {
    id: 'browser-geolocation',
    label: 'Browser geolocation stream',
    mode: 'live-telemetry',
    sourceTypes: ['browser_geolocation'],
    configured: () => true,
    priority: 'critical',
    supportsRealtime: true,
    notes: 'Client watchPosition observations are normalized and fused server-side.',
  },
  {
    id: 'android-managed-location-active',
    label: 'Android managed-device latest location',
    mode: 'provider-pull',
    sourceTypes: ['device_gps'],
    configured: () => anyEnv(
      'SPECTRA_ANDROID_MDM_LOCATION_URL_TEMPLATE',
      'SPECTRA_ANDROID_MDM_LOCATION_TOKEN',
    ),
    priority: 'critical',
    supportsRealtime: true,
    notes: 'Pulls the latest location already available from a configured Android EMM backend for an enrolled company-managed device.',
  },
  {
    id: 'apple-managed-location-active',
    label: 'Apple supervised-device latest location',
    mode: 'provider-pull',
    sourceTypes: ['device_gps'],
    configured: () => anyEnv(
      'SPECTRA_APPLE_MDM_LOCATION_URL_TEMPLATE',
      'SPECTRA_APPLE_MDM_LOCATION_TOKEN',
    ),
    priority: 'critical',
    supportsRealtime: true,
    notes: 'Pulls the latest DeviceLocation response already available from a configured MDM backend for a supervised Apple device.',
  },
  {
    id: 'cisco-spaces-active-location',
    label: 'Cisco Spaces active device location',
    mode: 'provider-pull',
    sourceTypes: ['wifi_fingerprint'],
    configured: () => anyEnv(
      'SPECTRA_CISCO_SPACES_DEVICE_URL_TEMPLATE',
      'SPECTRA_CISCO_SPACES_TOKEN',
    ),
    priority: 'high',
    supportsRealtime: true,
    notes: 'Pulls a configured Cisco Spaces device-location endpoint for a supplied device identifier and normalizes it into SPECTRA.',
  },
  {
    id: 'active-provider-adapters',
    label: 'Configured active provider/device collectors',
    mode: 'provider-pull',
    sourceTypes: [
      'device_gps','gnss_fix','gnss_raw','wifi_fingerprint','wifi_rtt',
      'cellular','nr_positioning','uwb_range','uwb_direction',
      'bluetooth_proximity','bluetooth_channel_sounding','ble_rssi','ble_aoa','ble_aod',
    ],
    configured: () => anyEnv('SPECTRA_ACTIVE_PROVIDER_ADAPTERS'),
    priority: 'critical',
    supportsRealtime: true,
    notes: 'Configured HTTPS provider/device collectors can be queried during acquisition and routed through an existing SPECTRA normalizer or the canonical telemetry schema.',
  },
  {
    id: 'configured-anchor-catalog',
    label: 'Configured radio/ranging anchor catalog',
    mode: 'anchor-resolution',
    sourceTypes: [
      'wifi_rtt','uwb_range','uwb_direction','bluetooth_channel_sounding',
      'ble_rssi','ble_aoa','ble_aod',
    ],
    configured: () => anyEnv('SPECTRA_ANCHOR_CATALOG_JSON'),
    priority: 'critical',
    supportsRealtime: true,
    notes: 'Resolves known Wi-Fi/UWB/Bluetooth anchor identifiers to configured coordinates before multilateration.',
  },
  {
    id: 'mist-location-webhook',
    label: 'Juniper Mist location webhook',
    mode: 'provider-webhook',
    sourceTypes: ['wifi_fingerprint'],
    configured: () => anyEnv('SPECTRA_INFRASTRUCTURE_WEBHOOK_AUTH'),
    priority: 'critical',
    supportsRealtime: true,
    notes: 'Normalizes Mist location webhook coordinates or calibrated floorplan X/Y observations through the canonical telemetry pipeline.',
  },
  {
    id: 'extreme-location-webhook',
    label: 'ExtremeCloud IQ presence/location webhook',
    mode: 'provider-webhook',
    sourceTypes: ['wifi_fingerprint'],
    configured: () => anyEnv('SPECTRA_INFRASTRUCTURE_WEBHOOK_AUTH'),
    priority: 'critical',
    supportsRealtime: true,
    notes: 'Normalizes ExtremeCloud IQ connected/unconnected client presence and location webhook observations.',
  },
  {
    id: 'unifi-client-location',
    label: 'UniFi client observation adapter',
    mode: 'provider-pull',
    sourceTypes: ['wifi_fingerprint'],
    configured: () => anyEnv(
      'SPECTRA_UNIFI_CLIENT_URL_TEMPLATE',
      'SPECTRA_UNIFI_API_KEY',
      'SPECTRA_ACTIVE_PROVIDER_ADAPTERS',
    ),
    priority: 'high',
    supportsRealtime: true,
    notes: 'Uses configured official UniFi Network client/API data and normalizes client/AP observations into SPECTRA.',
  },
  {
    id: 'aruba-location-stream',
    label: 'HPE Aruba Central location WSS stream',
    mode: 'live-telemetry',
    sourceTypes: ['wifi_fingerprint'],
    configured: () => anyEnv('SPECTRA_WSS_PROVIDER_ADAPTERS'),
    priority: 'critical',
    supportsRealtime: true,
    notes: 'Consumes Aruba Central CloudEvents protobuf location streams over WSS and normalizes Wi-Fi client/asset coordinates.',
  },
  {
    id: 'provider-neutral-mqtt-stream',
    label: 'Provider-neutral MQTT telemetry stream',
    mode: 'live-telemetry',
    sourceTypes: ['wifi_fingerprint','cellular','network_region','vehicle_telemetry'],
    configured: () => anyEnv('SPECTRA_MQTT_PROVIDER_ADAPTERS'),
    priority: 'critical',
    supportsRealtime: true,
    notes: 'Authenticated MQTT-over-TLS transport for configured infrastructure providers with reconnect, QoS1 acknowledgement, deduplication and health reporting.',
  },
  {
    id: 'ruckus-mqtt-location',
    label: 'RUCKUS SmartZone MQTT telemetry',
    mode: 'live-telemetry',
    sourceTypes: ['wifi_fingerprint'],
    configured: () => anyEnv('SPECTRA_MQTT_PROVIDER_ADAPTERS'),
    priority: 'high',
    supportsRealtime: true,
    notes: 'Uses the provider-neutral MQTT transport for configured SmartZone/LBS feeds after their payload is presented as a supported SPECTRA normalizer shape.',
  },
  {
    id: 'provider-neutral-wss-stream',
    label: 'Provider-neutral WSS telemetry stream',
    mode: 'live-telemetry',
    sourceTypes: ['device_gps','wifi_fingerprint','cellular','network_region','vehicle_telemetry'],
    configured: () => anyEnv('SPECTRA_WSS_PROVIDER_ADAPTERS'),
    priority: 'critical',
    supportsRealtime: true,
    notes: 'Reconnectable authenticated WSS transport for configured infrastructure providers, with deduplication and stream health reporting.',
  },
  {
    id: 'traccar-position-bridge',
    label: 'Traccar position bridge',
    mode: 'provider-pull',
    sourceTypes: ['device_gps','wifi_fingerprint','cellular'],
    configured: () => anyEnv('SPECTRA_ACTIVE_PROVIDER_ADAPTERS', 'SPECTRA_WSS_PROVIDER_ADAPTERS'),
    priority: 'critical',
    supportsRealtime: true,
    notes: 'Normalizes Traccar position events and preserves network/protocol metadata so SPECTRA can consume the mature Traccar device ecosystem without coupling to a specific tracker protocol.',
  },
  {
    id: 'openwisp-wifi-session-location',
    label: 'OpenWISP Wi-Fi session location',
    mode: 'provider-pull',
    sourceTypes: ['wifi_fingerprint'],
    configured: () => anyEnv('SPECTRA_ACTIVE_PROVIDER_ADAPTERS', 'SPECTRA_ANCHOR_CATALOG_JSON'),
    priority: 'high',
    supportsRealtime: true,
    notes: 'Maps OpenWISP Wi-Fi client sessions to configured managed-device/AP anchors, yielding bounded association-location evidence rather than an invented precise fix.',
  },
  {
    id: 'kismet-device-location',
    label: 'Kismet Wi-Fi/Bluetooth device-location bridge',
    mode: 'provider-pull',
    sourceTypes: ['wifi_fingerprint','bluetooth_proximity'],
    configured: () => anyEnv('SPECTRA_ACTIVE_PROVIDER_ADAPTERS'),
    priority: 'high',
    supportsRealtime: true,
    notes: 'Normalizes geolocated Kismet Wi-Fi/Bluetooth device records, including averaged/last geopoints and signal metadata, into the canonical telemetry path.',
  },
  {
    id: 'espresense-ble-ranging',
    label: 'ESPresense BLE indoor ranging',
    mode: 'live-telemetry',
    sourceTypes: ['ble_rssi','bluetooth_proximity'],
    configured: () => anyEnv('SPECTRA_MQTT_PROVIDER_ADAPTERS', 'SPECTRA_ANCHOR_CATALOG_JSON'),
    priority: 'high',
    supportsRealtime: true,
    notes: 'Turns ESPresense room/node distance or RSSI observations into canonical BLE ranging against configured scanner anchors for indoor multilateration.',
  },
  {
    id: 'find3-indoor-positioning',
    label: 'FIND3 Wi-Fi/Bluetooth fingerprint positioning',
    mode: 'provider-pull',
    sourceTypes: ['wifi_fingerprint','bluetooth_proximity'],
    configured: () => anyEnv('SPECTRA_ACTIVE_PROVIDER_ADAPTERS'),
    priority: 'critical',
    supportsRealtime: true,
    notes: 'Consumes GPS-calibrated FIND3 fingerprint classification results and preserves the returned probability as location confidence.',
  },
  {
    id: 'chirpstack-location-bridge',
    label: 'ChirpStack location-event bridge',
    mode: 'live-telemetry',
    sourceTypes: ['device_gps','lorawan_radio'],
    configured: () => anyEnv('SPECTRA_MQTT_PROVIDER_ADAPTERS', 'SPECTRA_WSS_PROVIDER_ADAPTERS', 'SPECTRA_ACTIVE_PROVIDER_ADAPTERS'),
    priority: 'high',
    supportsRealtime: true,
    notes: 'Normalizes ChirpStack LocationEvent coordinates and preserves device/application identity; raw LoRaWAN radio observations can continue through the existing TDOA/radio lane.',
  },
  {
    id: 'meshtastic-location-bridge',
    label: 'Meshtastic GPS/MQTT location bridge',
    mode: 'live-telemetry',
    sourceTypes: ['device_gps'],
    configured: () => anyEnv('SPECTRA_MQTT_PROVIDER_ADAPTERS', 'SPECTRA_WSS_PROVIDER_ADAPTERS'),
    priority: 'high',
    supportsRealtime: true,
    notes: 'Normalizes Meshtastic Position telemetry, including 1e-7 scaled coordinates, GPS accuracy, motion and node identity from configured mesh/MQTT streams.',
  },
  {
    id: 'cursor-on-target-location-bridge',
    label: 'Cursor-on-Target location bridge',
    mode: 'live-telemetry',
    sourceTypes: ['device_gps'],
    configured: () => anyEnv('SPECTRA_MQTT_PROVIDER_ADAPTERS', 'SPECTRA_WSS_PROVIDER_ADAPTERS'),
    priority: 'high',
    supportsRealtime: true,
    notes: 'Parses bounded CoT XML event/point telemetry with uid, event time, CE/LE uncertainty, track speed/course and callsign over configured WSS or MQTT feeds.',
  },
  {
    id: 'homeassistant-device-tracker',
    label: 'Home Assistant device tracker bridge',
    mode: 'provider-pull',
    sourceTypes: ['device_gps'],
    configured: () => anyEnv(
      'SPECTRA_HOME_ASSISTANT_STATE_URL_TEMPLATE',
      'SPECTRA_HOME_ASSISTANT_TOKEN',
      'SPECTRA_ACTIVE_PROVIDER_ADAPTERS',
    ),
    priority: 'high',
    supportsRealtime: true,
    notes: 'Normalizes owned Home Assistant device_tracker/person state coordinates and GPS accuracy; can be pulled directly from a configured HTTPS REST state endpoint.',
  },
  {
    id: 'omlox-location-hub',
    label: 'omlox Open Location Hub',
    mode: 'live-telemetry',
    sourceTypes: ['device_gps','wifi_fingerprint','bluetooth_proximity','uwb_range'],
    configured: () => anyEnv('SPECTRA_WSS_PROVIDER_ADAPTERS'),
    priority: 'critical',
    supportsRealtime: true,
    notes: 'Consumes standardized omlox location_updates or location_updates:geojson streams from configured RTLS hubs, including UWB, Wi-Fi, BLE and virtual location providers.',
  },
  {
    id: 'owntracks-location-bridge',
    label: 'OwnTracks Recorder location bridge',
    mode: 'live-telemetry',
    sourceTypes: ['device_gps'],
    configured: () => anyEnv('SPECTRA_MQTT_PROVIDER_ADAPTERS', 'SPECTRA_WSS_PROVIDER_ADAPTERS', 'SPECTRA_ACTIVE_PROVIDER_ADAPTERS'),
    priority: 'critical',
    supportsRealtime: true,
    notes: 'Normalizes OwnTracks location payloads delivered through MQTT, WebSocket, webhook or configured HTTPS pull into canonical timestamped GPS observations.',
  },
  {
    id: 'signed-provider-webhook',
    label: 'Signed telemetry provider webhook',
    mode: 'provider-webhook',
    sourceTypes: [
      'device_gps','gnss_fix','gnss_raw','vehicle_telemetry','visual_positioning',
      'visual_detection','network_region',
      'wifi_fingerprint','cellular','wifi_rtt','wifi_rssi','uwb_range','uwb_direction',
      'bluetooth_proximity','bluetooth_channel_sounding','ble_rssi','ble_aoa','ble_aod',
      'accelerometer','imu_gyro','magnetometer','barometer',
    ],
    configured: () => anyEnv('SPECTRA_TELEMETRY_HMAC_SECRET'),
    priority: 'critical',
    supportsRealtime: true,
    notes: 'Generic adapter for external live telemetry feeds that can POST normalized measurements.',
  },
  {
    id: 'camara-location-retrieval-ingest',
    label: 'CAMARA / GSMA network-location ingest',
    mode: 'provider-webhook',
    sourceTypes: ['network_region'],
    configured: () => anyEnv('SPECTRA_TELEMETRY_HMAC_SECRET'),
    priority: 'critical',
    supportsRealtime: true,
    notes: 'Normalizes signed CAMARA Device Location Retrieval responses into the canonical SPECTRA location pipeline.',
  },
  {
    id: 'bluetooth-scanner-ingest',
    label: 'Bluetooth scanner telemetry ingest',
    mode: 'provider-webhook',
    sourceTypes: ['bluetooth_proximity', 'ble_rssi', 'ble_aoa'],
    configured: () => anyEnv('SPECTRA_TELEMETRY_HMAC_SECRET'),
    priority: 'critical',
    supportsRealtime: true,
    notes: 'Normalizes signed BLE scanner/ranging observations into the existing multilateration path.',
  },
  {
    id: 'accessory-network-ingest',
    label: 'Accessory-network location ingest',
    mode: 'provider-webhook',
    sourceTypes: ['network_region', 'bluetooth_proximity', 'ble_rssi'],
    configured: () => anyEnv('SPECTRA_TELEMETRY_HMAC_SECRET'),
    priority: 'high',
    supportsRealtime: true,
    notes: 'Provider-neutral bridge for partner/exported accessory-network observations, including Find My / Find Hub compatible upstream feeds.',
  },
  {
    id: 'bluetooth-channel-sounding-ingest',
    label: 'Bluetooth Channel Sounding ingest',
    mode: 'provider-webhook',
    sourceTypes: ['bluetooth_channel_sounding','bluetooth_proximity'],
    configured: () => anyEnv('SPECTRA_TELEMETRY_HMAC_SECRET'),
    priority: 'critical',
    supportsRealtime: true,
    notes: 'Normalizes Bluetooth 6 Channel Sounding PBR/RTT distance measurements into canonical ranging evidence.',
  },
  {
    id: 'ble-direction-finding-ingest',
    label: 'BLE AoA/AoD direction ingest',
    mode: 'provider-webhook',
    sourceTypes: ['ble_aoa','ble_aod','bluetooth_proximity'],
    configured: () => anyEnv('SPECTRA_TELEMETRY_HMAC_SECRET'),
    priority: 'critical',
    supportsRealtime: true,
    notes: 'Preserves AoA/AoD direction, antenna-array and bearing-reference measurements; qualified geometry enters ranging fusion.',
  },
  {
    id: 'android-wifi-ranging-ingest',
    label: 'Android Wi-Fi RTT / 802.11az ingest',
    mode: 'provider-webhook',
    sourceTypes: ['wifi_rtt','wifi_fingerprint'],
    configured: () => anyEnv('SPECTRA_TELEMETRY_HMAC_SECRET'),
    priority: 'critical',
    supportsRealtime: true,
    notes: 'Normalizes 802.11mc/802.11az NTB, responder-location and Wi-Fi Aware ranging observations.',
  },
  {
    id: 'android-ranging-manager-ingest',
    label: 'Android RangingManager ingest',
    mode: 'provider-webhook',
    sourceTypes: ['uwb_range','uwb_direction','bluetooth_channel_sounding','wifi_rtt','ble_rssi'],
    configured: () => anyEnv('SPECTRA_TELEMETRY_HMAC_SECRET'),
    priority: 'critical',
    supportsRealtime: true,
    notes: 'Normalizes Android unified UWB, Bluetooth Channel Sounding, Wi-Fi NAN RTT and BLE RSSI ranging results.',
  },
  {
    id: 'android-uwb-sensor-fusion-ingest',
    label: 'Android UWB odometry sensor-fusion ingest',
    mode: 'provider-webhook',
    sourceTypes: ['uwb_range','uwb_direction'],
    configured: () => anyEnv('SPECTRA_TELEMETRY_HMAC_SECRET'),
    priority: 'critical',
    supportsRealtime: true,
    notes: 'Normalizes AndroidX UWB Precise/Imprecise/Drifting sensor-fusion results and prevents odometry-only drift from becoming an absolute live fix.',
  },
  {
    id: 'nr-positioning-ingest',
    label: '5G NR positioning ingest',
    mode: 'provider-webhook',
    sourceTypes: ['nr_positioning','cellular'],
    configured: () => anyEnv('SPECTRA_TELEMETRY_HMAC_SECRET'),
    priority: 'critical',
    supportsRealtime: true,
    notes: 'Normalizes 5G PRS, DL/UL-TDOA, multi-RTT, AoA/AoD, carrier-phase and solved network positioning results.',
  },
  {
    id: 'android-cellular-measurements-ingest',
    label: 'Android rich cellular measurements ingest',
    mode: 'provider-webhook',
    sourceTypes: ['cellular','cell_serving','cell_neighbor'],
    configured: () => anyEnv('SPECTRA_TELEMETRY_HMAC_SECRET'),
    priority: 'critical',
    supportsRealtime: true,
    notes: 'Preserves GSM/WCDMA/LTE/NR identifiers and rich signal metrics before radio-position resolution.',
  },
  {
    id: 'android-raw-gnss-ingest',
    label: 'Android raw GNSS ingest',
    mode: 'provider-webhook',
    sourceTypes: ['gnss_raw','gnss_fix'],
    configured: () => anyEnv('SPECTRA_TELEMETRY_HMAC_SECRET'),
    priority: 'critical',
    supportsRealtime: true,
    notes: 'Preserves GNSS clock, pseudorange/rate, ADR/carrier-frequency and C/N0 metadata; supplied fixes enter canonical fusion.',
  },
  {
    id: 'gnss-precision-solution-ingest',
    label: 'RTK / PPP precision GNSS solution ingest',
    mode: 'provider-webhook',
    sourceTypes: ['gnss_fix','gnss_raw'],
    configured: () => anyEnv('SPECTRA_TELEMETRY_HMAC_SECRET'),
    priority: 'critical',
    supportsRealtime: true,
    notes: 'Normalizes RTK/NRTK/VRS/PPP/PPP-RTK/SBAS/DGNSS solutions with NTRIP/RTCM, RTKLIB and Galileo HAS correction metadata, covariance, ambiguity status and protection levels.',
  },
  {
    id: 'apple-nearby-interaction-ingest',
    label: 'Apple Nearby Interaction ingest',
    mode: 'provider-webhook',
    sourceTypes: ['uwb_range','uwb_direction','bluetooth_proximity'],
    configured: () => anyEnv('SPECTRA_TELEMETRY_HMAC_SECRET'),
    priority: 'critical',
    supportsRealtime: true,
    notes: 'Normalizes Nearby Interaction UWB, EDM, DL-TDOA and Bluetooth Channel Sounding observations.',
  },
  {
    id: 'android-radio-collector-ingest',
    label: 'Android multi-radio collector ingest',
    mode: 'provider-webhook',
    sourceTypes: ['cellular','gnss_raw','gnss_fix','wifi_rtt','bluetooth_proximity','bluetooth_channel_sounding','ble_rssi','ble_aoa','ble_aod'],
    configured: () => anyEnv('SPECTRA_TELEMETRY_HMAC_SECRET'),
    priority: 'critical',
    supportsRealtime: true,
    notes: 'One signed collector envelope can carry cellular, GNSS, Wi-Fi RTT and Bluetooth observations into the same telemetry batch.',
  },
  {
    id: 'ble-gateway-ingest',
    label: 'Universal BLE gateway ingest',
    mode: 'provider-webhook',
    sourceTypes: ['ble_rssi','ble_aoa','ble_aod','bluetooth_proximity','bluetooth_channel_sounding'],
    configured: () => anyEnv('SPECTRA_TELEMETRY_HMAC_SECRET'),
    priority: 'high',
    supportsRealtime: true,
    notes: 'Provider-neutral normalization for BlueZ, ESP32, Android scanners and commercial BLE/AoA gateway observations.',
  },
  {
    id: 'lorawan-observation-ingest',
    label: 'LoRa/LoRaWAN observation ingest',
    mode: 'provider-webhook',
    sourceTypes: ['network_region'],
    configured: () => anyEnv('SPECTRA_TELEMETRY_HMAC_SECRET'),
    priority: 'supporting',
    supportsRealtime: true,
    notes: 'Preserves gateway RSSI/SNR/TOA context and normalizes supplied LoRa geolocation solver results.',
  },
  {
    id: 'universal-radio-log-ingest',
    label: 'Universal radio-log ingest',
    mode: 'provider-webhook',
    sourceTypes: ['cellular','gnss_raw','wifi_rtt','bluetooth_proximity','bluetooth_channel_sounding','ble_rssi','ble_aoa','ble_aod','uwb_range','uwb_direction'],
    configured: () => anyEnv('SPECTRA_TELEMETRY_HMAC_SECRET'),
    priority: 'high',
    supportsRealtime: false,
    notes: 'Detects structured Android/modem/BLE/Wi-Fi/GNSS/LoRa records plus RTKLIB .pos precision solutions and routes them through the same canonical normalizers.',
  },
  {
    id: 'camara-location-verification-ingest',
    label: 'CAMARA location verification ingest',
    mode: 'provider-webhook',
    sourceTypes: ['network_region'],
    configured: () => anyEnv('SPECTRA_TELEMETRY_HMAC_SECRET'),
    priority: 'high',
    supportsRealtime: true,
    notes: 'Stores carrier verification results as corroborating telemetry context without fabricating a coordinate.',
  },
  {
    id: 'camara-reachability-ingest',
    label: 'CAMARA device reachability ingest',
    mode: 'provider-webhook',
    sourceTypes: ['network_region'],
    configured: () => anyEnv('SPECTRA_TELEMETRY_HMAC_SECRET'),
    priority: 'supporting',
    supportsRealtime: true,
    notes: 'Stores current carrier reachability state and freshness alongside location evidence.',
  },
  {
    id: 'camara-number-verification-ingest',
    label: 'CAMARA number verification ingest',
    mode: 'provider-webhook',
    sourceTypes: ['identity_binding'],
    configured: () => anyEnv('SPECTRA_TELEMETRY_HMAC_SECRET'),
    priority: 'high',
    supportsRealtime: true,
    notes: 'Stores network number-possession verification as subject-binding evidence.',
  },
  {
    id: 'camara-device-identifier-ingest',
    label: 'CAMARA device identifier ingest',
    mode: 'provider-webhook',
    sourceTypes: ['identity_binding'],
    configured: () => anyEnv('SPECTRA_TELEMETRY_HMAC_SECRET'),
    priority: 'high',
    supportsRealtime: true,
    notes: 'Stores IMEI/IMEISV/TAC subscriber-device binding context from the network provider.',
  },
  {
    id: 'camara-kyc-match-ingest',
    label: 'CAMARA operator KYC match ingest',
    mode: 'provider-webhook',
    sourceTypes: ['identity_binding'],
    configured: () => anyEnv('SPECTRA_TELEMETRY_HMAC_SECRET'),
    priority: 'high',
    supportsRealtime: true,
    notes: 'Stores operator KYC match results as subject identity-binding evidence.',
  },
  {
    id: 'android-managed-lost-mode-ingest',
    label: 'Android managed Lost Mode ingest',
    mode: 'provider-webhook',
    sourceTypes: ['device_gps'],
    configured: () => anyEnv('SPECTRA_TELEMETRY_HMAC_SECRET'),
    priority: 'critical',
    supportsRealtime: true,
    notes: 'Normalizes Android Management API LostModeLocationEvent usage-log updates supplied by an enterprise management backend.',
  },
  {
    id: 'apple-managed-lost-mode-ingest',
    label: 'Apple Managed Lost Mode ingest',
    mode: 'provider-webhook',
    sourceTypes: ['device_gps'],
    configured: () => anyEnv('SPECTRA_TELEMETRY_HMAC_SECRET'),
    priority: 'critical',
    supportsRealtime: true,
    notes: 'Normalizes supervised-device DeviceLocation responses supplied by an MDM backend.',
  },
  {
    id: 'meraki-scanning-ingest',
    label: 'Cisco Meraki Scanning API ingest',
    mode: 'provider-webhook',
    sourceTypes: ['wifi_fingerprint','bluetooth_proximity'],
    configured: () => anyEnv(
      'SPECTRA_INFRASTRUCTURE_WEBHOOK_AUTH',
      'SPECTRA_TELEMETRY_HMAC_SECRET',
    ),
    priority: 'high',
    supportsRealtime: true,
    notes: 'Accepts native Meraki Scanning API validator/secret payloads or signed canonical provider delivery, and normalizes Wi-Fi/BLE locations, floor-plan context and RSSI records.',
  },
  {
    id: 'cisco-spaces-location-ingest',
    label: 'Cisco Spaces location firehose ingest',
    mode: 'provider-webhook',
    sourceTypes: ['wifi_fingerprint'],
    configured: () => anyEnv('SPECTRA_TELEMETRY_HMAC_SECRET'),
    priority: 'high',
    supportsRealtime: true,
    notes: 'Normalizes DEVICE_LOCATION_UPDATE events and map/location identifiers from Cisco Spaces.',
  },
  {
    id: 'aws-iot-device-location-ingest',
    label: 'AWS IoT Device Location ingest',
    mode: 'provider-webhook',
    sourceTypes: ['gnss_fix','wifi_fingerprint','cellular','bluetooth_proximity','network_region'],
    configured: () => anyEnv('SPECTRA_TELEMETRY_HMAC_SECRET'),
    priority: 'high',
    supportsRealtime: true,
    notes: 'Normalizes AWS IoT GeoJSON positions with measurement type, horizontal/vertical accuracy and resolver timestamp.',
  },
  {
    id: 'arcore-geospatial-pose-ingest',
    label: 'ARCore Geospatial / VPS ingest',
    mode: 'provider-webhook',
    sourceTypes: ['visual_positioning'],
    configured: () => anyEnv('SPECTRA_TELEMETRY_HMAC_SECRET'),
    priority: 'critical',
    supportsRealtime: true,
    notes: 'Normalizes ARCore GeospatialPose/VPS latitude, longitude, altitude and calibrated 68%-radius accuracy into SPECTRA.',
  },
  {
    id: 'connected-vehicle-location-ingest',
    label: 'Connected vehicle location ingest',
    mode: 'provider-webhook',
    sourceTypes: ['vehicle_telemetry'],
    configured: () => anyEnv('SPECTRA_TELEMETRY_HMAC_SECRET'),
    priority: 'high',
    supportsRealtime: true,
    notes: 'Provider-neutral bridge for fresh vehicle GPS/telemetry positions such as fleet API streams.',
  },
  {
    id: 'generic-https-json-pull',
    label: 'Configured HTTPS JSON telemetry pull',
    mode: 'live-telemetry',
    sourceTypes: [
      'device_gps','gnss_fix','vehicle_telemetry','social_geotag',
      'public_camera','traffic_cam','historical_location','public_record',
    ],
    configured: () => {
      try {
        const configured = JSON.parse(String(process.env.SPECTRA_GENERIC_JSON_ADAPTERS || '[]'));
        return Array.isArray(configured) && configured.length > 0;
      } catch {
        return false;
      }
    },
    priority: 'high',
    supportsRealtime: true,
    notes: 'Fixed HTTPS pull adapters normalize provider JSON into SPECTRA observations.',
  },
  {
    id: 'mylnikov-open-radio-geolocation',
    label: 'Mylnikov open Wi-Fi/cell geolocation',
    mode: 'radio-geolocation',
    sourceTypes: ['wifi_fingerprint','cellular'],
    configured: () => true,
    priority: 'high',
    supportsRealtime: true,
    notes: 'Keyless open-data resolver for supplied BSSIDs and MCC/MNC/LAC/cell IDs, including bounded multi-observation refinement.',
  },
  {
    id: 'beacondb-radio-geolocation',
    label: 'beaconDB radio geolocation',
    mode: 'radio-resolution',
    sourceTypes: ['wifi_fingerprint','cellular'],
    configured: () => true,
    priority: 'high',
    supportsRealtime: true,
    notes: 'Keyless Ichnaea-compatible Wi-Fi/cellular positioning fallback for supplied radio observations.',
  },
  {
    id: 'google-radio-geolocation',
    label: 'Google radio geolocation',
    mode: 'radio-resolution',
    sourceTypes: ['wifi_fingerprint','cellular'],
    configured: () => anyEnv(
      'SPECTRA_GOOGLE_GEOLOCATION_API_KEY',
      'GOOGLE_GEOLOCATION_API_KEY',
      'GOOGLE_MAPS_API_KEY',
    ),
    priority: 'critical',
    supportsRealtime: true,
    notes: 'Resolves supplied Wi-Fi/cellular observations into coordinates and an accuracy radius.',
  },
  {
    id: 'opencellid',
    label: 'OpenCellID cell-position fallback',
    mode: 'radio-resolution',
    sourceTypes: ['cellular','cell_serving','cell_neighbor'],
    configured: () => anyEnv('OPENCELLID_API_KEY'),
    priority: 'high',
    supportsRealtime: true,
    notes: 'Independent cell-position lookup when network identifiers are available.',
  },
  {
    id: 'multilateration',
    label: 'SPECTRA multilateration',
    mode: 'ranging',
    sourceTypes: ['wifi_rtt','wifi_rssi','uwb_range','uwb_direction','bluetooth_proximity','bluetooth_channel_sounding','ble_rssi','ble_aoa','ble_aod'],
    configured: () => true,
    priority: 'critical',
    supportsRealtime: true,
    notes: 'Uses three or more range anchors for multilateration, or absolute true-north directional anchors when available, with measurement uncertainty.',
  },
  {
    id: 'structured-telemetry-import',
    label: 'Structured telemetry import',
    mode: 'live-telemetry',
    sourceTypes: ['device_gps','gnss_fix','vehicle_telemetry','social_geotag','historical_location','public_record'],
    configured: () => true,
    priority: 'high',
    supportsRealtime: false,
    notes: 'Imports timestamped GeoJSON, GPX, KML, NMEA, CSV and NDJSON location observations.',
  },
  {
    id: 'media-metadata',
    label: 'Media metadata extraction',
    mode: 'media',
    sourceTypes: ['exif_photo','exif_video','xmp_sidecar','json_sidecar'],
    configured: () => true,
    priority: 'critical',
    supportsRealtime: false,
    notes: 'EXIF/XMP/IPTC/QuickTime metadata and embedded coordinates/timestamps.',
  },
  {
    id: 'wikimedia-geosearch',
    label: 'Wikimedia geotagged media',
    mode: 'media',
    sourceTypes: ['social_geotag'],
    configured: () => true,
    priority: 'supporting',
    supportsRealtime: false,
    notes: 'Nearby geotagged media context.',
  },
  {
    id: 'flickr-geosearch',
    label: 'Flickr geotagged media',
    mode: 'media',
    sourceTypes: ['social_geotag'],
    configured: () => anyEnv('FLICKR_API_KEY'),
    priority: 'supporting',
    supportsRealtime: false,
    notes: 'Nearby public photo metadata when Flickr is configured.',
  },
  {
    id: 'kartaview',
    label: 'KartaView street imagery',
    mode: 'street-imagery',
    sourceTypes: ['visual_detection'],
    configured: () => true,
    priority: 'supporting',
    supportsRealtime: false,
    notes: 'Nearby geotagged street imagery, capture time and directional context.',
  },
  {
    id: 'external-camera-json',
    label: 'Configured external camera directory',
    mode: 'camera',
    sourceTypes: ['traffic_cam','public_camera'],
    configured: () => {
      try {
        const feeds = JSON.parse(String(process.env.SPECTRA_CAMERA_JSON_FEEDS || '[]'));
        return Array.isArray(feeds) && feeds.length > 0;
      } catch {
        return false;
      }
    },
    priority: 'high',
    supportsRealtime: true,
    notes: 'Provider-neutral camera directory adapter for configured JSON feeds with geospatial field mappings.',
  },
  {
    id: 'trafficland',
    label: 'TrafficLand camera network',
    mode: 'camera',
    sourceTypes: ['traffic_cam','public_camera'],
    configured: () =>
      Boolean(String(process.env.TRAFFICLAND_API_KEY || '').trim())
      && Boolean(String(process.env.TRAFFICLAND_SYSTEM || '').trim()),
    priority: 'high',
    supportsRealtime: true,
    notes: 'Nationwide camera metadata/images where the configured account has coverage.',
  },
  {
    id: 'public-arcgis-camera-discovery',
    label: 'Public ArcGIS camera discovery',
    mode: 'camera',
    sourceTypes: ['traffic_cam','public_camera'],
    configured: () => true,
    priority: 'high',
    supportsRealtime: true,
    notes: 'Searches anonymous ArcGIS Online public content near a map area and queries matching public traffic-camera layers.',
  },
  {
    id: 'arcgis-camera-feeds',
    label: 'Configured ArcGIS/511 camera feeds',
    mode: 'camera',
    sourceTypes: ['traffic_cam','public_camera'],
    configured: () => anyEnv('SPECTRA_CAMERA_ARCGIS_FEEDS'),
    priority: 'high',
    supportsRealtime: true,
    notes: 'State/local DOT and 511 camera layers registered through configuration.',
  },
  {
    id: 'nominatim',
    label: 'OpenStreetMap Nominatim',
    mode: 'geocoder',
    sourceTypes: ['historical_location','public_record'],
    configured: () => true,
    priority: 'high',
    supportsRealtime: false,
    notes: 'Address/place search and regional candidate resolution.',
  },
  {
    id: 'census-geocoder',
    label: 'US Census Geocoder',
    mode: 'geocoder',
    sourceTypes: ['historical_location','public_record'],
    configured: () => true,
    priority: 'high',
    supportsRealtime: false,
    notes: 'Independent U.S. address fallback.',
  },
  {
    id: 'fcc-antenna-structure-context',
    label: 'FCC antenna structure context',
    mode: 'place-context',
    sourceTypes: ['public_record'],
    configured: () => true,
    priority: 'supporting',
    supportsRealtime: false,
    notes: 'Queries public FCC/HIFLD antenna-structure geography near an existing map candidate as context only.',
  },
  {
    id: 'noaa-cors-context',
    label: 'NOAA CORS reference-station context',
    mode: 'place-context',
    sourceTypes: ['public_record'],
    configured: () => true,
    priority: 'supporting',
    supportsRealtime: false,
    notes: 'Queries public NOAA CORS reference-station locations near an existing map candidate as context only.',
  },
  {
    id: 'wzdx-public-road-context',
    label: 'USDOT WZDx public road/work-zone context',
    mode: 'public-record',
    sourceTypes: ['public_record'],
    configured: () => true,
    priority: 'supporting',
    supportsRealtime: true,
    notes: 'Discovers active no-key USDOT WZDx feeds and ingests nearby work-zone or field-device GeoJSON as road context only.',
  },
  {
    id: 'mobilitydatabase-gtfs-rt-catalog',
    label: 'MobilityDatabase public GTFS-RT catalog',
    mode: 'public-record',
    sourceTypes: ['public_record'],
    configured: () => true,
    priority: 'supporting',
    supportsRealtime: true,
    notes: 'Discovers active no-auth GTFS-Realtime feed metadata from the public MobilityData catalog.',
  },
  {
    id: 'hootenanny-conflated-map-context',
    label: 'Hootenanny conflated map context',
    mode: 'place-context',
    sourceTypes: ['public_record'],
    configured: () => anyEnv('SPECTRA_HOOTENANNY_BASE_URL', 'SPECTRA_HOOTENANNY_MAP_ID'),
    priority: 'high',
    supportsRealtime: false,
    notes: 'Queries a configured Hootenanny conflated map by bounding box so roads, buildings and POIs from multiple source datasets can strengthen map matching without becoming target telemetry.',
  },
  {
    id: 'overpass-place-context',
    label: 'OpenStreetMap Overpass place context',
    mode: 'place-context',
    sourceTypes: ['historical_location','public_record'],
    configured: () => true,
    priority: 'supporting',
    supportsRealtime: false,
    notes: 'Nearby named places, roads, businesses and landmarks around a candidate location.',
  },
  {
    id: 'geonames-place-context',
    label: 'GeoNames place context',
    mode: 'place-context',
    sourceTypes: ['historical_location','public_record'],
    configured: () => anyEnv('GEONAMES_USERNAME'),
    priority: 'supporting',
    supportsRealtime: false,
    notes: 'Independent nearby toponym and administrative-place context.',
  },
  {
    id: 'nws',
    label: 'National Weather Service observations',
    mode: 'weather',
    sourceTypes: ['public_record'],
    configured: () => true,
    priority: 'supporting',
    supportsRealtime: true,
    notes: 'Time/place corroboration using nearby official weather observations.',
  },
  {
    id: 'copernicus-stac',
    label: 'Copernicus STAC',
    mode: 'earth-observation',
    sourceTypes: ['satellite_imagery'],
    configured: () => true,
    priority: 'supporting',
    supportsRealtime: false,
    notes: 'Spatiotemporal Earth-observation catalogue context.',
  },
  {
    id: 'aggregate-camera-motion-context',
    label: 'Aggregate camera motion context',
    mode: 'camera',
    sourceTypes: ['traffic_cam','public_camera'],
    configured: () => true,
    priority: 'supporting',
    supportsRealtime: true,
    notes: 'Accepts bounded aggregate traffic counts, speeds, headings and congestion context without promoting scene traffic into a target location observation.',
  },
  {
    id: 'public-source-retrieval',
    label: 'Direct public source retrieval',
    mode: 'generic-http',
    sourceTypes: ['historical_location','public_record','social_geotag'],
    configured: () => true,
    priority: 'high',
    supportsRealtime: false,
    notes: 'Fetches bounded direct source pages/JSON and extracts explicit geospatial metadata before evidence admission.',
  },
  {
    id: 'common-crawl',
    label: 'Common Crawl archive index',
    mode: 'archive',
    sourceTypes: ['historical_location','public_record'],
    configured: () => true,
    priority: 'supporting',
    supportsRealtime: false,
    notes: 'Historical URL discovery used only as discovery; underlying captures remain separate evidence.',
  },
];

export function getSpectraAdapterCapabilities() {
  return SPECTRA_ADAPTER_CAPABILITIES.map(adapter => ({
    id: adapter.id,
    label: adapter.label,
    mode: adapter.mode,
    sourceTypes: adapter.sourceTypes,
    configured: adapter.configured(),
    priority: adapter.priority,
    supportsRealtime: adapter.supportsRealtime,
    notes: adapter.notes,
  }));
}
