use_default_settings: true
general:
  debug: false
  instance_name: "Lexara Search"
search:
  safe_search: 0
  formats:
    - json
server:
  bind_address: "0.0.0.0"
  port: 8080
  limiter: false
  image_proxy: false
  secret_key: "GENERATED_AT_BUILD"
outgoing:
  request_timeout: 1.8
  max_request_timeout: 2.0
